### ISSUE TITLE
Cipher Tool not getting started in Windows and Linux

### ISSUE THREAD

**Issue by RidmiR** [wso2/micro-integrator#1030]
**Description:**
When running the Cipher tool .bat and .sh,  its throwing below error,

_**Could not find or load main class org.wso2.ciphertool.CipherTool**_

**Suggested Labels:**
Priority/High

**Affected Product Version:**
MI.1.1.0

**OS, DB, other environment details and versions:**    
Windows, Linux

**Steps to reproduce:**

_In windows_
Go MI pack > bin 
run  ciphertool.bat

_In Linux_
Go MI pack > bin
run  ciphertool.sh

**Comment by sdkottegoda** [comment]
The cipher tool workes as expected in a windows invironment. The issue here was that the pack was not extracted correctly.
