### ISSUE TITLE
Monitoring Dashboard doesn't loads in Normal window for second time.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1031]
**Description:**
When monitoring dashboard is started and logged in , the UI doesn't load for the second time ( after restarting dashboard ) in normal window. it loads in private window.

**OS, DB, other environment details and versions:**    
Chrome Version :  75.0.3770.100

**Comment by sachithKay** [comment]
Fixed in https://github.com/wso2/micro-integrator/pull/1043
