### ISSUE TITLE
Need to update securevault.bat file before run the securevault.bat file

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/micro-integrator#1038]
**Description:**
Need to update the following configuration in the securevault.bat file before encrypting passwords in synapse configurations in secure vault implementation for windows.

**Default configuration in securevault.bat.**

`set CARBON_CLASSPATH=.\conf
FOR %%c in ("%CARBON_HOME%\wso2\components\plugins\org.wso2.micro.integrator.security*.jar") DO set
CARBON_CLASSPATH=!CARBON_CLASSPATH!;".\wso2\components\plugins\%%~nc%%~xc"`

**Before run the securevault.bat file we need to update it as shown bellow.**

`set CARBON_CLASSPATH=.\conf
FOR %%c in ("%CARBON_HOME%\wso2\components\plugins\org.wso2.micro.integrator.security*.jar") DO (
set CARBON_CLASSPATH=!CARBON_CLASSPATH!;".\wso2\components\plugins\%%~nc%%~xc")
`

Documentation link : https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/encrypting-synapse-passwords/

**Suggested Labels:**
securevault, micro.integrator

**Affected Product Version:**
WSO2 Micro Integrator 1.1.0

**OS, DB, other environment details and versions:**    
Windows

**Comment by sdkottegoda** [comment]
Resolving since the fix is merged.
