### ISSUE TITLE
[DOC] Running the Micro Integrator on containers - Fix inaccurate carbonapps location

### ISSUE THREAD

**Issue by knightbeat** [wso2/micro-integrator#1039]
**Description:**
The COPY location given for the Dockerfile is inaccurate in https://docs.wso2.com/display/EI650/Installing+WSO2+Micro+Integrator#InstallingWSO2MicroIntegrator-MicroIntegratorwithDocker. 

It is given on the doc as (note: **wso2ei**), 
`COPY <directoy_path>/<capp_name> /home/wso2ei/wso2mi/repository/deployment/server/carbonapps`

which needs to be amended as (note **wso2carbon**),
`COPY <directoy_path>/<capp_name> /home/wso2carbon/wso2mi/repository/deployment/server/carbonapps`

**Comment by sdkottegoda** [comment]
@knightbeat We have modified the documentation with the correct information. Thank you very much for the information.
