### ISSUE TITLE
Not updated RbbitMQ configurations in axis2.xml after setting up RabbitMQ configs in TOML

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/micro-integrator#1040]
**Description:**
Not updated RbbitMQ configurations in axis2.xml after setting up RabbitMQ config's using TOML file (deployement.toml).

**Suggested Labels:**
RabbitMQ

**Suggested Assignees:**
Dhanushka Madushan

**Affected Product Version:**
WSO2 Micro Integrator 1.1.0

**OS, DB, other environment details and versions:**    
Ubuntu

**Steps to reproduce:**
1. Setup RabbitMQ configs TOML file.(deployement.toml)
2. Run micro-integrator.sh script.
3. Checked axis2.xml file. ( RabbitMQ transportReceiver and transportSender configurations)

**Comment by madushadhanushka** [comment]
**Work around**
This issue was due to issue with template file in <MI_HOME>/repository/resources/conf/templates/conf/axis2/axis2.xml.j2 file. Temporary you can fix this issue by replace following section in axis2.xml.j2 file,
```
    <transportReceiver name="{{transport.rabbitmq.sender.name}}" class="org.apache.axis2.transport.rabbitmq.RabbitMQSender">
        <parameter name="AMQPConnectionFactory" locked="false">
            {% for parameter_key,parameter_value in transport.rabbitmq.sender.AMQPConnectionFactory.parameter.items() %}
            <parameter name="{{parameter_key}}" locked="false">{{parameter_value}}</parameter>
            {% endfor %}
        </parameter>
    </transportReceiver>
```
with following section.
```
    <transportSender name="{{transport.rabbitmq.sender.name}}" class="org.apache.axis2.transport.rabbitmq.RabbitMQSender">
        <parameter name="AMQPConnectionFactory" locked="false">
            {% for parameter_key,parameter_value in transport.rabbitmq.sender.AMQPConnectionFactory.parameter.items() %}
            <parameter name="{{parameter_key}}" locked="false">{{parameter_value}}</parameter>
            {% endfor %}
        </parameter>
    </transportSender>
```
