### ISSUE TITLE
Data services - Cannot add event triggers in MI

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1046]
**Description:**
Currently [1] is not supported in MI

[1] https://docs.wso2.com/display/EI6xx/Receiving+Notifications+from+Data+Services

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
Closing since this has not received a higher demand for a considerable period.
