### ISSUE TITLE
Cannot mask sensitive data in Logs

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1048]
**Description:**
Currently there is no OOB support to mask sensitive data in logs (log4j2) as in https://docs.wso2.com/display/ADMIN44x/Masking+Sensitive+Information+in+Logs

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
Duplicate issue https://github.com/wso2/micro-integrator/issues/2007 is used to track this. Hence, resolving here.
