### ISSUE TITLE
No Console for Micro-Integrator?

### ISSUE THREAD

**Issue by dhananjay41996** [wso2/micro-integrator#1063]
**Description:**
Is there any provision for a UI console for micro-integrator in future versions?

**Suggested Assignees:**

**Comment by Nirothipan** [comment]
There is no UI console available in the distribution OOB but still you can use the plugin Monitoring Dashboard which caters the similar requirement 
https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/working-with-monitoring-dashboard/

**Comment by sdkottegoda** [comment]
Closing the issue since it is answered. Please feel free to re-open the issue for further concerns.
