### ISSUE TITLE
Unable to find documentation regarding environment-specific configuration 

### ISSUE THREAD

**Issue by kropiwnickij** [wso2/micro-integrator#1066]
**Description:**
Unable to find documentation regarding environment-specific configuration:  https://ei.docs.wso2.com/en/latest/micro-integrator/overview/introduction/

I am trying to find best practices regarding wso2mi deployment in Docker in mature architectures including multi-stage environments, where configuration differs from env to env: like endpoints, DB connections, credentials.

In previous wso2ei it was possible by deployment separate CAR files with GOV config to specific enviroments, however in Dockerized world approach should be more build once, deploy anywhere.

Target would be to deploy same Docker image and have it parametrized over ENV configuration following 12 factor-app principles.

If this is not possible what is recommended pattern to build, package, deploy and promote wso2 micro integration services?

**Suggested Labels:**
docs,wso2mi

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
Hi @kropiwnickij 

Absolutely sorry for the delay. The documentation is now available at https://ei.docs.wso2.com/en/latest/micro-integrator/develop/injecting-parameters/ 

Please let us know if you have further concerns.

**Comment by sdkottegoda** [comment]
Resolving the issue with the previous answer.
