### ISSUE TITLE
[CAPP][Deployment] need to introduce car app deployment order

### ISSUE THREAD

**Issue by milindaperera** [wso2/micro-integrator#1068]
**Description:**
When at deployment, there will be interdependent artifacts deployed in multiple capps. So we need to figure out approach to control the capp at startup in the MI. 

AFAIK currently it get deployed in alphabetical order, which is hard to maintain when multiple teams developing multiple components and it is limitation which is not worth renaming or rebuilding or duplicating mediation artifacts. Simply need approach to take control of order that CApps get deployed.

This will provide following advantages:
- Reuse mediation artifacts
- When multiple teams engage in development and share artifacts
- Easy for CIDC, no need to duplicate capp creation, and no need to maintain multiple repositories that create capps containing overlapping artifacts.
- increase modularity

**Comment by tishan89** [comment]
Will not be adding the improvement in near futuer
