### ISSUE TITLE
Add org.apache.activemq.SERIALIZABLE_PACKAGES as system property 

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#1069]
**Description:**
When using message processors with Active MQ as broker users need to explicitly whitelist packages that can be exchanged using ObjectMessages. Because ObjectMessage objects depend on Java serialization of marshal/unmarshal object payload and the process is considered as malicious. 

We can do that by using org.apache.activemq.SERIALIZABLE_PACKAGES system property, which is interpreted by the broker and the ActiveMQ client library. We can add the system property in micro integrator script as follow to overcome the issue,
`-Dorg.apache.activemq.SERIALIZABLE_PACKAGES="*"`

As we do not have the system property set we get the following exception while using message processors with Active MQ broker.
`java.lang.ClassNotFoundException: Forbidden class org.apache.synapse.message.store.impl.commons.StorableMessage! This class is not trusted to be serialized as ObjectMessage payload.`

More details about this can be found in [1].

[1] http://activemq.apache.org/objectmessage.html

**Comment by SMicroSun** [comment]
I also have this problem, I am directly running a JAR package, according to your solution, or not

**Comment by Vathsan** [comment]
> I also have this problem, I am directly running a JAR package, according to your solution, or not

Which version of MI are you using? Could you please elaborate the scenario?
