### ISSUE TITLE
Add basic startup test case for Monitoring Dashboard

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1090]
**Description:**
For monitoring dashboard , we don't have any integration tests. We need to have at least one and check whether it startup without any error logs.

**Comment by sdkottegoda** [comment]
We need to write a UI test framework for this. Hence we will not be able to do this for MI-1.2.0

**Comment by Nirothipan** [comment]
We can write a startup test, just to check the logs whether it starts up properly. We can improve it to UI tests later may be.
