### ISSUE TITLE
Create Helm resources for WSO2 MI

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1097]
**Description:**

When we used RabbitMQ, a whole cluster setup with persistent volumes etc can be configured using [Helm](https://helm.sh/). We need to create Helm packages for EI as well for easy deployment. Amazon EKS comes with [Helm support](https://docs.aws.amazon.com/eks/latest/userguide/helm.html). 

RabbitMQ is having this: 
https://github.com/helm/charts/tree/master/stable/rabbitmq

**Affected Product Version:**
MI 1.1.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
https://github.com/wso2/micro-integrator/issues/689

**Comment by arunans23** [comment]
The helm charts are available from MI 1.2.0
