### ISSUE TITLE
Support for Kubernetes vault secrets implementations

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1098]
**Description:**

Rather using WSO2 way to secure the passwords (and keep the master password in a plain text file as we need to start the container automatically :P), people would like to use 

* [Docker secrets](https://docs.docker.com/engine/swarm/secrets/) if on docker    
* Run a sidecar  with vault secrets of on K8S. [Hashicorp](https://www.hashicorp.com/blog/whats-next-for-vault-and-kubernetes/) is a popular choice. 

so that all their passwords are centrally managed. Thus it will be a good improvement if WSO2 MI can support those vault integrations Out of the Box. We can even consider developing a separate sideCar, so that anyone who need  vault integration can use. 

**Affected Product Version:**
MI 1.1.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Comment by abeykoon** [comment]
Can we configure Hashicorp  as the vault in this approach? 
[https://kubernetes.io/docs/concepts/configuration/secret/](https://kubernetes.io/docs/concepts/configuration/secret/)
[https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/](https://www.hashicorp.com/blog/injecting-vault-secrets-into-kubernetes-pods-via-a-sidecar/)

**Comment by sachithKay** [comment]
No this provides support for kubernetes and docker secrets only. We are not providing out of the box support for hashicorp. We will provide an extension point for users to implement third party vaults. Closing this issue since we already provide support docker and k8 secret support.
