### ISSUE TITLE
Add basic testing tools to the underlying OS of WSO2 MI Docker image

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1102]
**Description:**

Even if we test the developed MI image and move to prod, there are instances we need to troubleshoot the issues then and there, because some issues are environment specific (For an example check if a service is reachable from within a pod). For that we need basic tools like **telnet, pin, curl** coming with the OS of MI image. Currently what we noticed the basic image we have does not have any (pls check the WUM updated one). People cannot install as internet is not routable from within pods. 

**Affected Product Version:**
MI 1.1.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Comment by sachithKay** [comment]
The alpine based image does not provide much networking tools as it is expected to be lightweight. However there are alternatives such as **netcat(nc), netstat, ping and wget** as alternatives that can be used for network monitoring and trouble shooting. 
If the user requires functionalities such as CURL, the ubuntu or centOS based images which are more bulky.
Also, users can create a custom image from the base image with CURL and other required tool support.
Closing this issue, hence there are alternatives.
