### ISSUE TITLE
Cannot run Cipher-tool on Windows 10

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1104]
**Description:**

Cannot run cipher tool on Windows 10. What is tried is the following flow. 

1. Run cipher tool on the development machine. 
2. Get the updated deployment.yaml file (secrets section is encrypted) and copy it into the MI image 

Developers may be using windows at development suite. 

**Affected Product Version:**
MI 1.1.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Comment by Nirothipan** [comment]
Duplicate issue https://github.com/wso2/micro-integrator/issues/1095
