### ISSUE TITLE
Cipher tool deletes other configuration elements of deployment.yaml file

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1106]
**Description:**

When there are other elements in deployment.sh file, when cipher tool is ran, all other configs of the file is removed! Also, when there are other configs in deployment.yaml file Cipher tool gives errors. 

1. Add configs relevant to enabling rabbitMQ transport receiver and sender to deployment.yaml file. 
2. Run cipher-tool.sh 
3. It will give an error and all your rabbitMQ related configs will get removed from the file. 

**Affected Product Version:**
MI 1.1.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Comment by sajinieKavindya** [comment]
The issue could be reproduced with the following steps,

1. Add the following [secrets] configuration section in between any configuration sections in the deployment.toml file. (not at the ending)
2. Run cipher-tool.sh
3. It will give the following error and all other configurations right down the [secrets] configs section will be gone.

```
Exception in thread "main" java.lang.NullPointerException
	at java.lang.String.concat(String.java:2027)
	at org.wso2.ciphertool.CipherTool.updateDeploymentConfigurationWithEncryptedKeys(CipherTool.java:381)
	at org.wso2.ciphertool.CipherTool.main(CipherTool.java:75)
```
