### ISSUE TITLE
Issue in WUM updated docker image w:r:t public docker image

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1107]
**Description:**

Ideally, public docker image and the updated images should be consistent in all aspects other than the bug fixes. There is a path change between the two when come to public Docker image of MI 1.1.0 and its updated one.

**Vanilla pack (public)** - COPY apps/HelloWorldAppCompositeApplication_1.0.0.car /home/wso2carbon/wso2mi/repository/deployment/server/carbonapps
**WUM updated pack**  - COPY apps/HelloWorldAppCompositeApplication_1.0.0.car /home/wso2carbon/wso2mi-1.1.0/repository/deployment/server/carbonapps

We need to agree on a convention and update images.

**Affected Product Version:**
MI 1.1.0

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Comment by sdkottegoda** [comment]
The issue is due to the fact that the the server home in the public image (/home/wso2carbon/wso2mi) is different from what's in the private docker registry (/home/wso2carbon/wso2mi-1.1.0). We need to update the path of the image in the docker hub for this.
