### ISSUE TITLE
Image not found in documentation

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/micro-integrator#1109]
**Description:**
URL : https://ei.docs.wso2.com/en/latest/micro-integrator/develop/installing-WSO2-Integration-Studio/

Image for get tooling updates is not available in "Get the latest updates" section

<img width="273" alt="Screenshot 2020-01-01 at 13 58 10" src="https://user-images.githubusercontent.com/38608578/71639564-cdf40e00-2c9e-11ea-9a65-7f1d40f66063.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by nilminiwso2** [comment]
Fixed from this PR: https://github.com/wso2/docs-ei/pull/1062
