### ISSUE TITLE
Custom message builders and formatters configured for blocking mode in deployment.toml are not getting updated

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#1130]
**Description:**
Custom message builders and formatters configured for blocking mode in deployment.toml are not getting updated to axis2_blocking_client.xml. 

**Suggested Labels:**
Bug

**Affected Product Version:**
MI 1.1.0

**Steps to reproduce:**
1. Add custom message builders and formatters in deployment.toml for blocking mode as mentioned in [1]. You may also add the following sample configuration,
```
[[custom_message_builders.blocking]]
content_type = "application/scim+json"
class = "org.wso2.carbon.integrator.core.json.JsonStreamBuilder"

[[custom_message_formatters.blocking]]
content_type = "application/scim+json"
class = "org.wso2.carbon.integrator.core.json.JsonStreamFormatter"
```

2. Start Micro Integrator

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/references/config-catalog/#custom-message-builder-blocking-mode

**Comment by sdkottegoda** [comment]
Changes to the documentation are added by https://github.com/wso2/docs-ei/pull/1111
