### ISSUE TITLE
Issue in Prometheus for Monitoring document

### ISSUE THREAD

**Issue by orifux** [wso2/micro-integrator#1131]
**Description:**
Following doc  https://ei.docs.wso2.com/en/next/micro-integrator/administer-and-observe/monitoring_with_prometheus/
the - targets parameter should be set to port 9191 in prometheus.yml file. But when I checked the target state in prometheus (http://localhost:9090/targets)  it was "down" and there was an error message "connection refused".
After I set the - targets parameter to 9201 it worked fine. 
 
**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**
micro-integrator 7.0.1

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
Thank you for reporting this issue. We will correct the documentation accordingly.

**Comment by sdkottegoda** [comment]
Resolving since we have fixed the issue in the documentation.
