### ISSUE TITLE
[Magento Connector]Api Url is not found. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1135]
**Steps to reproduce:**
1. Configure Magento server [1]. 
2. Login to http://localhost:8888/magento/admin page. 
3. Go to System-> Extensions -> Integrations -> Add a new Integration
4. Provide all the permissions in API tab. 
5. It will generate Consumer Key, consumer secret, access token, access token secret for a given integration. 
<img width="1284" alt="Screen Shot 2020-02-10 at 5 35 00 PM" src="https://user-images.githubusercontent.com/31693103/74148700-10105800-4c2c-11ea-9c9f-b5e9f9ca05ba.png">

6. Then go to the Customers tab and create a new customer. 
<img width="1343" alt="Screen Shot 2020-02-10 at 5 36 26 PM" src="https://user-images.githubusercontent.com/31693103/74148710-16063900-4c2c-11ea-835f-cf8996ce8d67.png">

7. Create the following ESB solution project which includes the following proxy service through Integration Studio and deploy it in the micro Integrator. 
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy name="MagentoProxy" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence>
            <log level="custom">
                <property expression="$body//urn:apiUser" name="apiUser" xmlns:urn="wso2.connector.magento.createCustomer"/>
            </log>
            <log level="custom">
                <property expression="$body//urn:apiKey" name="apiKey" xmlns:urn="wso2.connector.magento.createCustomer"/>
            </log>
            <log level="custom">
                <property expression="$body//urn:apiUrl" name="apiUrl" xmlns:urn="wso2.connector.magento.createCustomer"/>
            </log>
            <magento.init>
                <apiUser xmlns:urn="wso2.connector.magento.createCustomer">{$body//urn:apiUser}</apiUser>
                <apiKey xmlns:urn="wso2.connector.magento.createCustomer">{$body//urn:apiKey}}</apiKey>
                <apiUrl xmlns:urn="wso2.connector.magento.createCustomer">{$body//urn:apiUrl}</apiUrl>
            </magento.init>
            <magento.getCustomerInfo>
                <customerId xmlns:urn="wso2.connector.magento.createCustomer">{$body//urn:customerID}</customerId>
            </magento.getCustomerInfo>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </target>
</proxy>

```
8. Invoke the proxy with the following payload. 
```
<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:urn="wso2.connector.magento.createCustomer">
   <soapenv:Header/>
   <soapenv:Body>
         <urn:apiUser>connector</urn:apiUser>
         <urn:apiKey>2yiroca7e5svh2ef15rwhpla9entm9ze</urn:apiKey>
         <urn:apiUrl>http://localhost/magento/index.php/api/v2_soap/index/</urn:apiUrl>
         <urn:customerID>1</urn:customerID>
   </soapenv:Body>
</soapenv:Envelope> 
```

**Expected**: Get customer information. 
**Actual**: Getting the following response. 
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html>
    <head>
        <title>404 Not Found</title>
    </head>
    <body>
        <h1>Not Found</h1>
        <p>The requested URL /magento/index.php/api/v2_soap/index/ was not found on this server.</p>
    </body>
</html>
```

**Affected Product Version:**
mi 1.1.0

 

[1] - https://medium.com/@isuruuy/configuring-magento2-using-mamp-server-7fbedc35297d
[2] - https://docs.wso2.com/display/ESBCONNECTORS/Working+with+Cart+Customers+in+Magento

**Comment by GDLMadushanka** [comment]
This connector is depricated as in https://store.wso2.com/store/assets/esbconnector/details/046bfb35-4b63-4bc9-b8ae-ab91f93af144
