### ISSUE TITLE
[Gmail Connector]Error in receiving the draft list/ reading a draft. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1140]
**Description:**
Getting the following error in obtaining the draft lists. 
```
{
    "error": {
        "errors": [
            {
                "domain": "global",
                "reason": "required",
                "message": "Login Required",
                "locationType": "header",
                "location": "Authorization"
            }
        ],
        "code": 401,
        "message": "Login Required"
    }
}
```
The doc[2] stated about a pageToken, but it has no information on how to obtain the page token or whether it is mandatory. 
The same issue happens while reading a draft. This issue has the configs for listdraft feature. 

**Steps to reproduce:**
1. Obtain userId, access token, client secret, clientID and refresh token[1] and include them in the api resource gmail.init property in the below api in step2.
2. Create an ESB Solution Project with the following API resource included.
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/gmailconnector" name="GmailConnector" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="POST">
        <inSequence>
            <property expression="json-eval($.to)" name="to" scope="default" type="STRING"/>
            <property expression="json-eval($.subject)" name="subject" scope="default" type="STRING"/>
            <property expression="json-eval($.messageBody)" name="messageBody" scope="default" type="STRING"/>
            <property expression="json-eval($.cc)" name="cc" scope="default" type="STRING"/>
            <property expression="json-eval($.maxResults)" name="maxResults" scope="default" type="STRING"/>
            <gmail.init>
                <userId></userId>
                <accessToken></apiUrl>
                <clientId></clientSecret>
                <refreshToken></refreshToken>
            </gmail.init>
            <gmail.createDraft>
                <to>{$ctx:to}</to>
                <subject>{$ctx:subject}</subject>
                <from>isuruuy@gmail.com</from>
                <messageBody>{$ctx:messageBody}</messageBody>
                <cc>{$ctx:cc}</cc>
                <bcc>{$ctx:bcc}</bcc>
                <id>{$ctx:id}</id>
                <threadId>{$ctx:threadid}</threadId>
                <contentType>{$ctx:contentType}</contentType>
            </gmail.createDraft>
            <gmail.listDrafts>
                <maxResults>{$ctx:maxResults}</maxResults>
            </gmail.listDrafts>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```
3. Make sure the Gmail connector has been added to the ESB Solution Project, as well as the Connector Exporter project.
4. Deploy the artifacts in the Micro Integrator.
5. Invoke the API with the following payload.
```
{
     "to":"user1@msn.com",
     "subject":"AA111A",
     "messageBody":"this is the test23011110",
     "cc":"user2@gmail.com",
     "maxResults":10
}
```

**Expected**: The Draft list should be retrieved. 
**Actual**: Above mentioned 401 error occurs. 

**Affected Product Version:**
mi-1.1.0

[1] - https://docs.wso2.com/display/EI660/Using+the+Gmail+Connector
[2] - https://docs.wso2.com/display/ESBCONNECTORS/Working+with+Drafts+in+Gmail#WorkingwithDraftsinGmail-listDrafts

**Comment by isuruuy429** [comment]
This issue occurs when we use two methods with init. Let's say we want to create a label and read the existing labels, we get this issue.

**Comment by GDLMadushanka** [comment]
This issue happens due to the Authorization: Bearer header is getting removed by the second gamil operation. After the init operation it sets the header. But its getting removed from the respose from Gmail to the second operation. To avoid this users can use registryPath configuration in init operation to save the token in registry and set the header again before the next operation.
