### ISSUE TITLE
Additional logs related to TCPEventServer getting printed at the server startup

### ISSUE THREAD

**Issue by malakaganga** [wso2/micro-integrator#115]
**Description:**
Following additional logs getting printed at the server startup

INFO - ManagementModeConfigurationLoader CEP started in Persistence enabled HA mode
2019-04-24 14:01:51,722 INFO  [org.wso2.micro.integrator.integration.ServerLogReader] - [2019-04-24 14:01:51,722] [micro-integrator]  INFO - TCPEventServer EventServer starting event listener on 0.0.0.0:11010
2019-04-24 14:01:51,728 INFO  [org.wso2.micro.integrator.integration.ServerLogReader] - [2019-04-24 14:01:51,728] [micro-integrator]  INFO - EventHandler Event Management TCPEventServer for EventReceiver started on port 11010

**Comment by a5anka** [comment]
@malakaganga What happens if we disable all modes in eventProcessorConfiguration?

**Comment by a5anka** [comment]
@malakaganga Why did we change from single mode to HA mode in #97? Isn't more suitable to have a single mode instead of HA mode since MI is by default in non clustered mode?

**Comment by malakaganga** [comment]
> @malakaganga Why did we change from single mode to HA mode in #97? Isn't it more suitable to have the single mode instead of the HA mode since MI is by default in non clustered mode?

With the single mode, in OSGI logs null pointer exception was thrown continuously since configuration context is missing but if we are to solve that issue lot of kernel features may need to be packed so as an alternative this approach has been taken.

**Comment by a5anka** [comment]
Shouldn't we fix that issue in the upstream project? Looks like a bug in the dependent component or the way we use it. Do we know the specific reason for getting the NullPointer?
