### ISSUE TITLE
Add hot deployment support for log4j2 properties

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#1156]
**Description:**
Currently, MI does not support hot deployment for log4j2 properties. We can update the log level and get logger data using MI CLI. The hot deployment support should be implemented so that the log levels can be updated using MI CLI.

**Comment by Nirothipan** [comment]
@Vathsan  did we included this to the docs ?

**Comment by Vathsan** [comment]
> @Vathsan did we include this to the docs ?

We have included this in using-wire-logs documentation [1]. We need to include this in other relevant docs. I have created a doc issue [2] to track this. 

[1] https://github.com/wso2/docs-ei/pull/1152
[2] https://github.com/wso2/micro-integrator/issues/1366
