### ISSUE TITLE
DataService - Issue in Documentation

### ISSUE THREAD

**Issue by stefanonegri** [wso2/micro-integrator#1173]
**Description:**
the documentation regarding the data service is missing or incomplete in the following cases:
Output mapping:
https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/data-services/creating-data-services/#add-output-mapping
Output mapping element: https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/data-services/creating-data-services/#add-output-mapping-element
Also it is not clear for the following:
Add SQL: https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/data-services/creating-data-services/#add-an-sql and
Add Input mapping: https://ei.docs.wso2.com/en/latest/micro-integrator/develop/creating-artifacts/data-services/creating-data-services/#add-input-mapping
**Suggested Labels:**
Documentation

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
Closing since the related issue is closed.
