### ISSUE TITLE
Add carbon coordination into the MI clustering

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#1185]
**Description:**
Add carbon coordination into the WSO2 MI. Carbon Coordination initially designed for Clustering implementation in MI. It has inbuilt RDBMS based clustering implementation. This feature should move into the MI and all carbon dependent components should be removed.

**Affected Product Version:**
MI 7.0.x

**Comment by sdkottegoda** [comment]
Addressed by https://github.com/wso2/micro-integrator/pull/1172
