### ISSUE TITLE
Add integration tests for clustering tasks

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#1187]
**Description:**
Integration tests should be written to test the Task coordination implementation in MI clustering mode.

**Affected Product Version:**
7.0.x

**Comment by Nirothipan** [comment]
Added in https://github.com/wso2/micro-integrator/pull/1362  ,  https://github.com/wso2/micro-integrator/pull/1356 & https://github.com/wso2/micro-integrator/pull/1343

**Comment by Nirothipan** [comment]
More tests added in https://github.com/wso2/micro-integrator/pull/1374 , https://github.com/wso2/micro-integrator/pull/1372 & https://github.com/wso2/micro-integrator/pull/1376
