### ISSUE TITLE
Unknown error occurred when login to  Monitoring Dashboard due to not trusted certs

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1222]
**Description:**
Due to different kernel versions, different certs are being packed and the UX is not better for the first time. Hence $subejct.

**Comment by Nirothipan** [comment]
This seems we have to redirect the url to .../management/login if it is not trusted to manually trust.

**Comment by sdkottegoda** [comment]
Resolved by https://github.com/wso2/product-mi-tooling/pull/27
