### ISSUE TITLE
Rename keystore/ trustore location configurations in deployment.toml

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#1228]
**Description:**
keystore "file_name" configuration should be renamed to "location" in deployment toml. Current configuration as follows. 
```
listener.keystore.file_name = "keystore location"
sender.keystore.file_name = "keystore location"
```
This confuguration should be changes as follows.
```
listener.keystore.location = "keystore location"
sender.keystore.location = "keystore location"
```

**Related Issues:**
https://github.com/wso2/docs-ei/issues/908

**Comment by madushadhanushka** [comment]
Related unmerged PR https://github.com/wso2/micro-integrator/pull/1053

**Comment by Nirothipan** [comment]
Above PR is merged
