### ISSUE TITLE
[New Connector] WSO2 MI Minio connector 

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1274]
**Description:**
[Minio](https://min.io/), released under the Apache v2.0 license and written in Go, enables developers to store unstructured data on any cloud infrastructure, either public and private. Using Minio, app developers can containerize storage, apps and security all at the same time, hooking into the same resources.

As it trends as a object storage for containrized platforms WSO2 MI better contain a connector to support that. There is a SDK  for that. It is used as a replacement for Amazon S3. 

Following are some resources 
1. https://min.io/
2. https://www.eweek.com/storage/minio-s-new-gen-object-storage-server-fits-container-trend
3. https://min.io/resources/docs/CPG-MinIO-reference-architecture.pdf

**Comment by minhtranes** [comment]
Looking for the same connector.
We are previously using Amazon S3 connector 1.x.x to work with Minio. However, after migrate to MI, using Amazon S3 2.x.x, then it doesn't work any more.
