### ISSUE TITLE
Fix default kafka inbound endpoint

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1289]
**Description:**
$subject.

Since this is not compatible with latest kafka versions we have documented custom one https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-kafka/ . We need to make the custom one as the deault.

**Comment by tishan89** [comment]
Revisit
- Dual channel support
- Transaction support with receiver and sender
