### ISSUE TITLE
Message Processors are scheduled in paused stated when hot deployed.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1301]
**Description:**
$subject.

**Steps**

- Deploy a MP in MI.
- Delete the file and add it again.
- It will be scheduled and be in paused state.

**Comment by Vathsan** [comment]
Similar to https://github.com/wso2/micro-integrator/issues/1071

**Comment by Nirothipan** [comment]
> Similar to #1071

This issue happens only when hot deployment is enabled. #1071 seems to be something else and we have to look into it differently.
