### ISSUE TITLE
function replace in property not support in mi now but work in esb

### ISSUE THREAD

**Issue by caihemm** [wso2/micro-integrator#1305]
**Description:**

Evaluation of the XPath expression replace($ctx:gggg,'xxxx','tttt') resulted in an error
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
Hi @caihemm 

You need to add the following property to <MI_HOME>/conf/deployment.toml in order to configure WSO2 Micro Integrator with xpath 2.0 since 'replace' is an xpath 2.0 function.
```
[mediation]
# synapse.properties
synapse.enable_xpath_dom_failover=true
```
We will modify our documentation to mention this lcearly. Thank you for reporting the issue.

**Comment by sdkottegoda** [comment]
Hi @caihemm
We are closing this issue since the resolution has been shared. Please re-open the issue for further concerns.

**Comment by sdkottegoda** [comment]
We have also modified the official documentation to have this information. Thank you very much for raising this issue.

**Comment by srinivaskancharla** [comment]
Hello @sdkottegoda 
I am writing this question in different context, we have wso2mi deployed in container.
We have to add new parameter in synapse.properties. For that we tried adding below to deployment.toml under [mediator]
synapse.commons.json.json.output.autoPrimitive=false

but when the container is running, we could not see this configuration reflecting there, only see default configurations. 
How to add this property to synapse.properties, so that this can be available when the container starts.

**Comment by arunans23** [comment]
@srinivaskancharla Can you try adding it as below?

```
[mediation]
synapse.enable_auto_primitive=false
```

As per the [key mapping](https://github.com/wso2/micro-integrator/blob/master/distribution/src/resources/config-tool/key-mappings.json#L91) defined, you can use the above way to define the property. The use the full property name, you have to define it under synapse_properties section like below.

```
[synapse_properties]
'synapse.commons.json.output.autoPrimitive'=false
```

**Comment by srinivaskancharla** [comment]
@arunans23 , thanks for your reply Arun.
Do you mean by adding below to deployment.toml
[mediation]
synapse.enable_auto_primitive=false

autmatically adds the below to synapse.properties?
synapse.commons.json.output.autoPrimitive'=false

automatically adds

**Comment by arunans23** [comment]
> @arunans23 , thanks for your reply Arun. Do you mean by adding below to deployment.toml [mediation] synapse.enable_auto_primitive=false
> 
> autmatically adds the below to synapse.properties? synapse.commons.json.output.autoPrimitive'=false

yes
