### ISSUE TITLE
[Docker] Tooling support to apply secure vault in a docker exporter project

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#1320]
**Description:**
Currently there is no proper UX to apply secure vault when building a docker exporter project. 
Only way to to apply secure vault in a docker environment is to manually create a docker image [1] (without using the exporter project).

**Requirement**
Provide tooling support to create necessary files and for secure vault and copy them to the docker image.
[1] https://medium.com/@HasithaAbeykoon/applying-secure-vault-to-wso2-micro-integrator-f3a11912047

**Comment by tishan89** [comment]
@sachithKay What needs to be done regarding this issue?

**Comment by sachithKay** [comment]
This issue has been resolved with the latest studio release.
