### ISSUE TITLE
Add Tracing and Monitoring section to getting started guide

### ISSUE THREAD

**Issue by a5anka** [wso2/micro-integrator#133]
[Getting started guide](https://github.com/wso2/micro-integrator/tree/master/examples/getting-started)

- [x] Add section on monitoring
- [ ] Add section on tracing

**Comment by sdkottegoda** [comment]
Comprehensive instructions have been added to the official documentation at https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/using-the-analytics-dashboard/
