### ISSUE TITLE
User management in Micro Integrator

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1334]
**Description:**
Currently we have a way to plug in a user store and run based on it https://ei.docs.wso2.com/en/latest/micro-integrator/setup/user_stores/setting_up_ro_ldap/. However we don't have a way to manage users like adding or removing user names or roles.

We need to come up with a solution for this.

**Comment by sdkottegoda** [comment]
At the moment we are not focusing on the capability of managing users. We will consider this in a future release.

**Comment by sachithKay** [comment]
Added user management with: https://github.com/wso2/micro-integrator/pull/1439.
