### ISSUE TITLE
VFS SMB not working

### ISSUE THREAD

**Issue by DMadhuranga** [wso2/micro-integrator#1337]
**Description:**
When running the broker, it throws the following error.
`[2020-03-31 11:58:09,200]  WARN {org.apache.synapse.transport.vfs.VFSTransportListener} - Failed to resolve the file URI: smb://192.168.1.104/test/in, in attempt 1, Badly formed URI "smb://192.168.1.104/test/in". Retrying in 30000 milliseconds.
`

**Steps to reproduce:**
Follow this [example](https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/file-processing/Accessing_Windows_Share_Using_VFS_Transport/). 

In windows, if the **sbm** is changed to **file** in the URL, it works.
In linux, nothing works.

**Related Issues:**
https://github.com/wso2/devstudio-tooling-ei/issues/860

**Comment by sachithKay** [comment]
The the above occurs when you do not add the jcifs jar to the MI lib directory (as this is not bundled by default). This is not a runtime issue. Please refer the issue: https://github.com/wso2/product-ei/issues/4087.

**Comment by sachithKay** [comment]
Closing this with https://github.com/wso2/micro-integrator/issues/1618
