### ISSUE TITLE
Add studio connector project to all connector scenario docs

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1338]
**Description:**
Please execute the $Subject. 

1. Decide on a place to host the connector project zip files. 
2. Please note that this is the workplace that is zipped. We need to tell the users to point the unzipped folder as the `workplace` when stating the Studio. 

We may use another common page for this with a placeholder for the zip link if possible.

**Comment by samgnaniah** [comment]
Fixed with https://github.com/wso2/docs-ei/pull/1341
