### ISSUE TITLE
Verify startup time

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#1344]
Even though the distribution starts up locally under 5s, it takes much longer in some operating systems and in docker. This task is to verify the startup time in each environment and to fix related issues.

- [ ] ubuntu

- [ ] mac

- [ ] windows

- [ ] docker in mac (All docker images)

- [ ] docker in ubuntu (All docker images)

**Comment by sachithKay** [comment]
Mac (local): 4 seconds
Docker (Mac):
   centos: 7 seconds
   ubuntu: 8 seconds
   alpine: 7 seconds

**Comment by sdkottegoda** [comment]
Ubuntu-18.04 (local): 4 seconds

Docker:
centos: 23 seconds
ubuntu: 24 seconds
alpine: 23 seconds

**Comment by Nirothipan** [comment]
**Docker**: 19.03.6

- Ubuntu : 
  - First Startup 32.56 sec
  - Second Startup 13.70 sec

- Centos : 
  - First Startup 19.94 sec
  - Second Startup 17.19 sec

- Alpine : 
  - First Startup 34.20 sec
  - Second Startup 13.68 sec

**Comment by sajinieKavindya** [comment]
Mac (local): 4 seconds

- Ubuntu : 
  - First Startup 3.95 sec
  - Second Startup 4.30 sec

- Centos : 
  - First Startup 3.82 sec
  - Second Startup 4.98 sec

- Alpine : 
  - First Startup 4.07 sec
  - Second Startup 4.93 sec

**Comment by sachithKay** [comment]
Windows.
- Initial startup: 10.25 secs
- Consecutive starts: 7.5 seconds

**Comment by sachithKay** [comment]
Closing the issue as we have acceptable startup times on average.
