### ISSUE TITLE
[Testing]WSO2 NetSuite Connector

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1346]
- Testing the compatibility in WSO2 EI 6.6.0
- Testing the compatibility in WSO2 MI 1.1.0
- Create an Integration Scenario. 
- Documentation

**Comment by isuruuy429** [comment]
mail: [Writing an Integration Scenario for NetSuite Connector]

**Comment by abeykoon** [comment]
This is on-hold for the moment as we need to purchase.

**Comment by abeykoon** [comment]
This is on-hold until we purchase the account.
