### ISSUE TITLE
Commented builders/formatters in the default axis2.xml need to be added as custom builders/formatters in deployment.toml

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#1347]
**Description:**
Add the following configuration to the deployment.toml
```
[message_formatters]
text_html = "org.apache.axis2.transport.http.ApplicationXMLFormatter"

[message_builders]
text_html = "org.apache.axis2.builder.ApplicationXMLBuilder"
```
This will not add the correct builder and the formatter. 

The reason is that we have not templated the in axis2.xml.j2. We need to template these popular content types.

**Comment by sajinieKavindya** [comment]
Currently, we have templated the following content-types with a default message builder and a formatter in axis2.xml.j2 file.

Summary of the content-types that have a default msg formatter and builder specified.

| Content-type  | Msg. Formatter | Msg. Builder |
| ------------- | ------------- | ------------- | 
| application/x-www-form-urlencoded  | &#x2611; | &#x2611; |
| multipart/form-data  | &#x2611;  | &#x2611; |
| application/xml | &#x2611; | &#x2611; |
| text/xml | &#x2611; |  |
| application/soap+xml | &#x2611; |
|  text/plain | &#x2611; | &#x2611; |
| application/json | &#x2611; | &#x2611; |
| application/json/badgerfish | &#x2611; | &#x2611;|
| text/javascript  | &#x2611; | &#x2611; |
| application/octet-stream  | &#x2611; | &#x2611; |
| application/binary | &#x2611; | &#x2611; |

For any other content-type that is not listed above with a  &#x2611; sign, the **org.apache.axis2.transport.http.SOAPMessageFormatter** will be taken as the corresponding message formatter, while the **org.apache.axis2.builder.SOAPBuilder** is taken as the corresponding message builder according to the code base.

Therefore, for these content-types, you may have to go with custom_message_builders or custom_message_formatters as shown in the below example. This will manipulate the incoming/outgoing payload from the WSO2 Micro Integrator for a particular content-type according to the specified class implementation of builder or formatter. Click [here](https://ei.docs.wso2.com/en/latest/micro-integrator/setup/message_builders_formatters/message-builders-and-formatters/#writing-a-custom-message-builder-and-formatter) for more information on custom message builders and formatters in WSO2 Micro Integrator.

```
[[custom_message_builders]]
content_type = "x-application/hessian"
class="org.apache.synapse.format.hessian.HessianMessageBuilder"
```
```
[[custom_message_formatters]]
content_type = "x-application/hessian"
class="org.apache.synapse.format.hessian.HessianMessageFormatter"
```

**Comment by sajithaliyanage** [comment]
Since `text/html` is a popular content type widely used, we may need to template relevant message builder and formatter with default values. 

Related issue: https://github.com/wso2/integration-studio-examples/issues/58

**Comment by Nirothipan** [comment]
Shall we include all the default configs as commented out in toml

**Comment by arunans23** [comment]
https://github.com/wso2/micro-integrator/pull/1689
