### ISSUE TITLE
Car files are not deploying according to Alphabetical order

### ISSUE THREAD

**Issue by dinuish94** [wso2/micro-integrator#1349]
**Description:**
Car files are not being deployed according to alphabetical order.

**Product version:**
MI 1.1.0

**Comment by abeykoon** [comment]
Is it possible to write an automated test case for this?

**Comment by dinuish94** [comment]
@abeykoon Unless the fix for this is removed intentionally or if the deployment is rewritten, IMO it is highly unlikely this would break due to regression.
