### ISSUE TITLE
Remove synapse-configs folder 

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#136]
**Description:**

We deploy to micro integrator via EI Tooling. EI tooling always creates a CAPP which is deployable to Micro Integrator. 

As there is no Web UI or any place we can create and deploy individual artifacts. Thus better to remove `synapse-configs` folder altogether and keep `carbonapps` folder only. 

There are some more deployment specific folders like `axis2modules`, `axis2services` etc which is not relevant to MI usecase.

**Comment by a5anka** [comment]
IMO it is better to keep the synapse folder since users can add individual files (proxies, sequences etc) instead of carbon apps. It can help users for quick testing. Therefore I think we should keep it

**Comment by abeykoon** [comment]
For quick testing they can use Tooling debugging functionality or [Unit Testing Framework ](https://github.com/wso2/product-ei/tree/master/gh-docs/synapse-unit-testing-framework) at the development time in the tooling itself.
