### ISSUE TITLE
[docs] Update docs on support dynamically adding log4j2 properties via MI CLI

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#1366]
**Description:**
PR [1] adds dynamic changing of log4j2 properties. The properties can be updated using MI CLI.
We have already updated the using-wire-logs documentation [2]. We need to update other relevant docs as well. 
[1] https://github.com/wso2/micro-integrator/pull/1157
[2] wso2/docs-ei#1152

**Comment by sdkottegoda** [comment]
Issue moved to [wso2/docs-ei #1409](https://github.com/wso2/docs-ei/issues/1409) via [**ZenHub**](https://www.zenhub.com/)
