### ISSUE TITLE
[Docs] Support for dynamic names in property mediator

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/micro-integrator#1368]
**Description:**
Updating the documentation related to $subject. We need to update the property mediator configuration section at[1] with the following new feature.

From the PR https://github.com/wso2/wso2-synapse/pull/1510, we have added the dynamic name support for the property mediator. Now users can add dynamic property names within the `{` and `}` brackets inside the name attribute. Some examples can find below.

Examples:
```
<property name="{get-property('propertyName')}" expression="$ctx:propertyValue" />
<property name="{$ctx:propertyName}" expression="$ctx:propertyValue" />
<property name="{json-eval({$ctx:propertyName})}" expression="$ctx:propertyValue" />
```
**Note:** 
The property mediator can not have a static name like `{name}` further since above fix uses the same logic used in defining the sequence mediator key attribute.

**Suggested Labels:**
Type/Documentation

**Affected Product Version:**
MI 1.2.0

[1] - https://ei.docs.wso2.com/en/latest/micro-integrator/references/mediators/property-Mediator/

**Comment by sdkottegoda** [comment]
Issue moved to [wso2/docs-ei #1408](https://github.com/wso2/docs-ei/issues/1408) via [**ZenHub**](https://www.zenhub.com/)
