### ISSUE TITLE
Document how to enable JMS 2.0 support

### ISSUE THREAD

**Issue by a5anka** [wso2/micro-integrator#137]

**Comment by Nirothipan** [comment]
Do we need to pack the JMS jars by default in lib directory as in EI ?

**Comment by Nirothipan** [comment]
Or only in endorsed directory

**Comment by Nirothipan** [comment]
Do we need to pack the jars to support broker integration in lib directory as in EI or only in endorsed directory and modify the lauch.ini. IMO packing it in endorsed is enough.

**Comment by sdkottegoda** [comment]
I think we need to pack the jar in MI since the user experience between MI and EI should not differ much.

**Comment by a5anka** [comment]
Since we need to keep the MI distribution light weight let's not add JMS jars. 
@Nirothipan What are the already existing JMS related JARs in MI?

**Comment by Nirothipan** [comment]
> I think we need to pack the jar in MI since the user experience between MI and EI should not differ much.

Do we need to pack all our 3 jars to connect with WSO2 MB as in EI ? or just javax.jms-2.0 jar only in lib.

**Comment by Nirothipan** [comment]
> Since we need to keep the MI distribution light weight let's not add JMS jars.
+1

> @Nirothipan What are the already existing JMS related JARs in MI?

We have this geronimo.specs.wso2:geronimo-jms_1.1_spec jar in endorsed directory which is coming from kernel. We can replace it with jms 2.0 jar

**Comment by a5anka** [comment]
Shall we remove  geronimo.specs.wso2:geronimo-jms_1.1_spec jar as well :)

**Comment by a5anka** [comment]
Let's use the updated launch.ini file in product-ei here too.

**Comment by Nirothipan** [comment]
> Shall we remove geronimo.specs.wso2:geronimo-jms_1.1_spec jar as well :)

Then we need to ask the user to copy jms 2.0 jar in lib and endorsed as well and update the docs accordingly. Since this is specific for MI. Doesn't that increase the no. of steps ?

**Comment by a5anka** [comment]
Yes. We need to update the docs. I already changed the PR title to match that. Why do we need to copy it to both lib and endorsed? Isn't it enough to copy to lib?

**Comment by Nirothipan** [comment]
> Yes. We need to update the docs. I already changed the PR title to match that.
> 
> Why do we need to copy the JAR to both lib and endorsed? Isn't it enough to copy to lib?

I think it is enough to copy to endorsed only. @indikasampath2000  could you please clarify on this ?

**Comment by indikasampath2000** [comment]
You can find the purpose of the `endorsed` folder in here[1]. Copying jar into `lib` folder only exporting packages to the runtime. There could be problems when it comes to package import by different bundles because of both system bundle and third party jar exporting the same.

[1] https://medium.com/@maryamzi/wso2-what-does-carbon-home-lib-endorsed-endorse-15632e602428

**Comment by Nirothipan** [comment]
Thank you . I've replaced the gerenimo jms with jms 2.0 in endorsed directory and removed the entry forn launch.ini file https://github.com/wso2/micro-integrator/pull/138

**Comment by Nirothipan** [comment]
As we have packed JMS 2.0 jar and removed the javax.jms entry from launch.ini file , we don't need to document anything specific to MI. The documents on how to connect to broker can be found from EI doc space. Hence closing.
