### ISSUE TITLE
CLI binary distribution

### ISSUE THREAD

**Issue by SanojPunchihewa** [wso2/micro-integrator#139]
### Description
The binaries generated for the CLI tool are platform dependent. Need a proper way of distributing the binaries

**Comment by a5anka** [comment]
What if we generate three different distributions for Linux, Mac and Windows?

@kasun04 @isudana @nandika @indikasampath2000 thoughts?

**Comment by isudana** [comment]
Why CLI tool has become platform dependent? Is it because of GO lang?

**Comment by a5anka** [comment]
Yes

**Comment by isudana** [comment]
I'm +1 for having platform dependent distributions for the CLI tool as long as it is independently distributable from micro integrator runtime.

**Comment by abeykoon** [comment]
In ubuntu we build with arch flags and then we can separately create installers for Windows and Mac.

**Comment by dakshika** [comment]
we can have distributions for each OS. Also, we need to provide formulas such as Homebrew, PSGallery or Snap depending on the user preferences. Normally CLI users don't like to download ZIP files and do the extraction. we need to provide direct executable from the server. 

ex: Curl -L <URLTOFILE>

then we need to give instructions on how to set permissions etc.

**Comment by a5anka** [comment]
We will proceed with separating the CLI distribution from MI distribution and having platform dependent distributions for CLI. Please raise if you have any concerns.

**Comment by dakshika** [comment]
+1 for separating from MI distribution, @a5anka  Do we have a seperate repo for this?  Or is it same inside main repo as a pkg? IMO if we can have inside main repo its much easier for outside contributors to identify. WDYT?

**Comment by a5anka** [comment]
@dakshika It is in the same repo as a module.
