### ISSUE TITLE
Update the doc Working With Micro Integrator.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#140]
**Description:**
The document working with MI [1] instructs to create MI from EI using profile-creator script and proceed. We need to update this as it is available now as a separate run time.

[1] - https://docs.wso2.com/display/EI6xx/Working+with+the+Micro+Integrator

Also we need to update the folder paths in that document since we have restructured it.

In case, if we are going only with git docs, we may need to remove the above docs since it is no more valid.

**Comment by a5anka** [comment]
You can refer https://github.com/wso2/micro-integrator/blob/master/doc/working-with-the-micro-integrator.md for updated details.

**Comment by Nirothipan** [comment]
Closing as this is being tracked in https://github.com/wso2/product-ei/issues/3869
