### ISSUE TITLE
Issue in Getting Started Guide 

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#142]
**Description:**

Following [doc](https://github.com/wso2/micro-integrator/tree/master/examples/getting-started) 

It states to execute command 

`$ docker build -t wso2/mi-order-process-be . `

But it did not states from where it needs to run this. By inspecting I could find it needs to run from 

`/micro-integrator/examples/getting-started/order-process-be`

It is not clear in the document

**Comment by abeykoon** [comment]
Also, better specify a working curl command instead of 

`http://localhost:8291/order`

For me, from browser it returned a 405 code.

**Comment by abeykoon** [comment]
curl -v -X POST -H "Content-Type:application/json" "http://localhost:8291/order" works. We better place that

**Comment by a5anka** [comment]
AFAIK @sajithaliyanage is already working on fixing this.

**Comment by sajithaliyanage** [comment]
Fixes are done in 
https://github.com/wso2/micro-integrator/pull/149
