### ISSUE TITLE
Bash into micro integrator image does not work

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#143]
**Description:**

`docker exec -it <containerIdOrName> bash `

should give access to bash of micro integrator image. But it gives below error once executed.

`OCI runtime exec failed: exec failed: container_linux.go:344: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown`

**Comment by a5anka** [comment]
You can't use bash with micro-integrator base image. Instead, use `sh`.

```
docker exec -it <containerIdOrName> sh
```
