### ISSUE TITLE
Facilitate enabling  Prometheus publishing via a system property 

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#147]
**Description:**

Currently it is disabled by default in promethus-conf.xml and we have to edit this file to enable it.

```
<PrometheusPublishingConfig>
    <Enabled>false</Enabled>
</PrometheusPublishingConfig>
```

We need this to be facilitated via a system property in order to have seamless integration with docker for MI.

**Comment by a5anka** [comment]
Did we document this somewhere in Gtihub docs? Please ignore if we have already done.

**Comment by Nirothipan** [comment]
> Did we document this somewhere in Gtihub docs? Please ignore if we have already done.

Yes , it is mentioned in configuring Prometheus with Mi doc https://github.com/wso2/micro-integrator/pull/146/files#diff-b5b27bac60458f039bbd8cb7505a021cR403
