### ISSUE TITLE
Remove NO_ENTITY_BODY property from all the connectors that sets a payload

### ISSUE THREAD

**Issue by rosensilva** [wso2/micro-integrator#1491]
**Description:**
If we read a file from a connector, a simple HTTP get request cannot get a response without explicitly removing the NO_ENTITY_BODY property. 
Similarly, all the mediators which are setting a payload should remove this property automatically. (mediators like Read Email Operation, File Read Operation, etc.).

**Comment by Nirothipan** [comment]
@rosensilva  this is applicable to the connector operations isn't it ? AFAIR , we have it in all the mediators

**Comment by rosensilva** [comment]
> @rosensilva this is applicable to the connector operations isn't it ? AFAIR , we have it in all the mediators

Yes, I have corrected the title, and let's add the connectors label.
