### ISSUE TITLE
[Doc] Document RabbitMQ Transport configs correctly

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1498]
**Description:**

From MI 2.1.0 to MI 2.2.0 RabbitMQ configurations to put at `deployment.toml` has changed. 

Refer to following issues: 
1. https://github.com/wso2/micro-integrator/issues/1041
2. https://github.com/wso2/micro-integrator/issues/1040

We need to update document pages to catch this information. 

At the end of the day to enable RabbitMQ sender and configure it, you need to have following. 

```
[transport.rabbitmq]
sender_enable = true

[[transport.rabbitmq.sender]]
name = "AMQPConnectionFactory"
parameter.hostname = "localhost"
parameter.port = 5672
parameter.username = "guest"
parameter.password = "guest"
```

The update should go to the reference. 
https://ei.docs.wso2.com/en/latest/micro-integrator/references/config-catalog/#rabbitmq-sender

**Comment by abeykoon** [comment]
Please note that we need to have a note in MI 2.1.0 document space, that updated config looks like this as we have released a WUM update for this.

**Comment by Nirothipan** [comment]
The docs already have the changes which are present in 1.2.0  ( WUM updated pack ) . Added a note about the mentioned two issues in https://github.com/wso2/docs-ei/pull/1494/files if the user doesn't have a wum update.
