### ISSUE TITLE
Data-service responds with XML although outputType is set to a different format

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/micro-integrator#1520]
**Description:**
When using data service, although the output type of results is set, it returns an XML. User has to use Accept header in order to receive results with expected content-type.

**Affected Product Version:**
1.1.0

**Steps to reproduce:**
1. Create a data service. 
2. Provide output type as `json`

eg: ``<result outputType="json">
    {
    "employees": {
        "employee": [
            {
                "first_name": "$first_name"
            }
        ]
    }
}</result>``

3. Deploy artifacts and send a request. 
4. You will receive an XML response.
5. This was solved when an Accept header is set to application/json.

**Comment by chanikag** [comment]
This is by design. Inside the dataservice, the processing is happening in XML. According to the Accept header, the payload is formatted and it is constructed according to the given format. If Accept header is not set explicitly, by default it is considered as application/xml
