### ISSUE TITLE
The top level object cannot be an array issue in dataservices

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/micro-integrator#1522]
**Description:**
When the top-level object is an array in output mapping, DS Fault : `The top level object cannot be an array` occurs.
.
**Affected Product Version:**
1.1.0

**Steps to reproduce:**
1. configure a data service
2. configure output mapping similar to the following payload.

```
<result outputType="json">
{
     "employee": [
            {
                "first_name": "$first_name"
            }
      ]
}
</result>
```
3. Deploy the CAPP and start the server.
4. ``DS Fault Message: The top level object cannot be an array`` will be logged.

**Comment by chanikag** [comment]
This is because we are converting the generated XML format to JSON. We have documented this in our docs https://docs.wso2.com/display/EI660/Using+JSON+with+Data+Services.

However I couldn't find that in the MI docs. @nilminiwso2 shall we include that in MI docs if it is not already done.
