### ISSUE TITLE
Support updating state of message processor using MI CLI

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#1538]
**Description:**
We can use the management api to activate or deactivate the message processor by sending send REST calls [1]. We need to add this feature to CLI.

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/working-with-management-api/#post-message-processors

**Suggested Labels:**
Improvement

**Comment by sachithKay** [comment]
Related issue: https://github.com/wso2/micro-integrator/issues/1539
