### ISSUE TITLE
[Improvement] Retrieve Environment Variables using get-property

### ISSUE THREAD

**Issue by fjunior87** [wso2/micro-integrator#1542]
**Description:**
On WSO2 EI 6.6.0 we are able to retrieve Environment variables using the scope env[1]. This is needed on MI as it is targeted for Container deployment.

[1] https://docs.wso2.com/display/EI660/Property+Mediator+

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
Micro Integrator 1.1.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

Add this to the synapse config and also add the environment variable to the system before running WSO2 MI:

```
 <log>
           <property name="DB_URL" expression="get-property('env','DB_URL')" />
 </log>
```

This will print null, but it works fine in EI 6.6.0

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed in https://github.com/wso2/wso2-synapse/pull/1451

**Comment by sdkottegoda** [comment]
Closing since the answer is provided. Please re-open for further concerns.
