### ISSUE TITLE
Include GDPR compliance

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#1570]
**Description:**
This is a task to validate if we are going to add the anonymization tool or not and to change/verify https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/about_forgetme_tool/

**Comment by Vathsan** [comment]
The forget me tool that we pack in EI worked fine with MI 1.1.0. As the size of the tool that we pack inside EI is ~18MB for MI we can host the tool somewhere and point it in our docs (to reduce the pack size).

**Comment by sdkottegoda** [comment]
Related issue: https://github.com/wso2/micro-integrator/issues/1048

**Comment by sachithKay** [comment]
Hosten: https://github.com/wso2-docs/WSO2_EI/pull/70
