### ISSUE TITLE
Port fixes done to carbon mediation

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#1574]
This issue is a long running task to keep porting the fixes done for carbon-mediation

**Comment by Nirothipan** [comment]
Verified upto PR No.1425 and created issues .

**Comment by Nirothipan** [comment]
Verified upto PR No.1439

**Comment by arunans23** [comment]
Verified upto PR No.1525

**Comment by Vathsan** [comment]
Verified upto PR No.1540

**Comment by Vathsan** [comment]
Verified upto PR No.1574

**Comment by Nirothipan** [comment]
Verified upto PR No. 1608
