### ISSUE TITLE
Add Proxy Profiles support in blocking transport

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#1580]
@Drifftr commented on [Tue Jun 11 2019](https://github.com/wso2/product-ei/issues/4131)

**Description:**
Currently proxy profiles support is added only to non blocking transport. Its better if we can have the same support in blocking transport too.

Doc - https://docs.wso2.com/display/EI640/Working+with+Proxy+Servers 
Related PR - https://github.com/wso2/wso2-synapse/pull/447

**Affected Product Version:**
EI 6.5.0

**Related Issues:**
N/A

**Comment by Vathsan** [comment]
As a solution we can set JVM parameters at the server startup as follows,
 ./wso2server.sh -Dhttp.nonProxyHosts =10.|localhost|127.0.0.1|.\.[domain.com](http://domain.com/)

Please refer to https://ei.docs.wso2.com/en/7.2.0/micro-integrator/setup/configuring_proxy_servers/#for-blocking-service-calls, for more details.
