### ISSUE TITLE
Implement CLI command to generate a report for Transaction Count summary

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/micro-integrator#1637]
**Description:**
Need to provide the report generation support to the CLI tool which generates a readable file (most probably in csv format) that will contain all the data relevant to transaction count for a given period of time. 

This report will be then used as the input to the decryption tool and produced the decrypted version will be used in WSO2 internally.

**Affected Product Version:**
MI-1.2.0 alpha

**OS, DB, other environment details and versions:**    
N/A

**Comment by arunans23** [comment]
Implemented with https://github.com/wso2/product-mi-tooling/pull/39
