### ISSUE TITLE
JSON transformer is not working when deployed via CAPP

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/micro-integrator#1659]
**Description:**
JSON transform mediator is not working when the media type of the schema file is "application/json"
It's working correctly when the media type is "Unknown" 

When we add a JSON schema file (*.json) to the registry from the management console media type set as "Unknown". 
In tooling, it set the media type as application/json

**Suggested Labels:**
Bug

**Affected Product Version:**
EI 6.6.0 

**Steps to reproduce:**
Create and compare sample setup using the management console and tooling

**Comment by arunans23** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1558
