### ISSUE TITLE
Log4j2 custom log levels are not getting printed in the logs

### ISSUE THREAD

**Issue by GDLMadushanka** [wso2/micro-integrator#1671]
**Description:**
When we create a sample JAVA program to log to a custom log level, its working fine.
http://www.kswaughs.com/2016/01/log4j-2-custom-log-level-example.html

But, when we do the same with a class mediator, new log levels are getting rounded up to their nearest log levels.
![Screenshot from 2020-06-09 17-11-52](https://user-images.githubusercontent.com/8251118/84502814-a6d24b80-acd6-11ea-90e5-4c6b41b46726.png)

Class mediator
```
package com.wso2.sample;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.synapse.MessageContext;
import org.apache.synapse.mediators.AbstractMediator;


public class Log4j2CustomLogger extends AbstractMediator {

    public boolean mediate(MessageContext messageContext) {

        Logger logger = LogManager.getLogger();
        logger.log(Level.FATAL,"This is a fatal level message");
        logger.log(Level.ERROR,"This is an error level message");
        logger.log(Level.WARN,"This is a warn level message");
        logger.log(Level.INFO,"This is an info level message");
        logger.log(Level.DEBUG,"This is a debug level message");
        logger.log(Level.getLevel("FLOW_ERROR"),"This is a flow_error level message");
        logger.log(Level.getLevel("FLOW_INFO"),"This is a flow_info level message");
        logger.log(Level.getLevel("FLOW_DEBUG"),"This is a flow_debug level message aaaaaaa");

        return true;
    }
}
```
log4j2.properties configuration
```
customLevels=FLOW_ERROR,FLOW_INFO,FLOW_DEBUG
customLevel.FLOW_ERROR=250
customLevel.FLOW_INFO=350
customLevel.FLOW_DEBUG=550
```

**Suggested Labels:**
Bug

**Comment by malakaganga** [comment]
This limitation originates in pax logging, which we are used to expose log4j2 as an OSGI bundle. Hence, we cannot provide a  fix for this. 
I checked the pax logging code and currently, this seems not possible with their implementation of their Log4jv2Logger. The levels are being truncated and lost in pax logging itself [1].
Hence closing this issue.

[1] - https://github.com/ops4j/org.ops4j.pax.logging/blob/master/pax-logging-api/src/main/java/org/ops4j/pax/logging/log4jv2/Log4jv2Logger.java#L175.L186
