### ISSUE TITLE
Add mandatory parameter support for Sequence Templates

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1673]
**Description:**

[Sequence Templates](https://ei.docs.wso2.com/en/latest/micro-integrator/references/synapse-properties/template-properties/) facilitates developers to parameterize a specific logic in WSO2 EI. 

### Improvement 1 - mandatory parameters and default values

Currently, it does not specify parameters optional or mandatory. This makes calling the template to fail in the runtime if all the mandatory parameters are not fed in properly. 

Improvement is introducing following attributes to the parameters. 

1. isMandatory - specifies if a parameter is mandatory
2. defaultValue - optionally provide a default value for the optional parameter. If caller has not provided the parameter, this is used if available. 

i.e

`<parameter name="param1" isMandatory="true" defaultValue="defautVal"/>`

Following are the cases needed to be addressed ($ctx:test1 evaluates to value1)

1. Call like the old way (**backward compatibility**)

```
    <parameter name="param1"/>
    
    <call-template target="MyTemplate">
        <with-param name="param1" value="{$ctx:test1}"/>
    </call-template>
```
    
    result = value1
    
2. When calling provide mandatory value **(happy path)**

```
   <parameter name="param1" isMandatory="true" />
    
   <call-template target="MyTemplate">
        <with-param name="param1" value="{$ctx:test1}"/>
    </call-template> 
```
    
    result = value1

3. When calling do not provide optional value, but a default is available

```
   <parameter name="param1" isMandatory="false" defaultValue="defautVal"/>
   
    <call-template target="MyTemplate">
    </call-template>
```
    
    result = defautVal

4.  When calling do not provide optional value, but a default is not available

```
   <parameter name="param1" isMandatory="false" />
   
    <call-template target="MyTemplate">
    </call-template>
```
    
    result = null
    
5. When calling provide optional parameter with empty value **(allow to pass empty if required)**

```
    <parameter name="param1" isMandatory="true" />
    
   <call-template target="MyTemplate">
        <with-param name="param1" value=""/>
    </call-template> 
```
    
    result = ""
    

6. When calling do not provide mandatory param. Also a default value is not provided in the template

```
   <parameter name="param1" isMandatory="true"/>
   
   <call-template target="MyTemplate"> 
   </call-template> 
```
   
   result - onerror sequence specified at the Template sequence is executed. Proper **error codes** and **error messages** specifying which parameter is not provided needs to be provided.
     

    
7. When calling provide mandatory parameter that will **evaluates to null in the runtime**

  ```
 <parameter name="param1" isMandatory="true" defaultValue="defautVal"/>
   
   <call-template target="MyTemplate">
        <with-param name="param1" value="{$ctx:nonExistingProperty}"/>
    </call-template>
```
    
    result = null -----> should we validate this, as this is runtime? Currently, this is not done. 

### Improvement 2 - Error sequence for call-template

When come to error handling, developers can specify a onerror sequence for templates as below. 

`<template name="MyTemplate" xmlns="http://ws.apache.org/ns/synapse" onError="TemplateFaultSeq">`

However, this logic is internal to the template. The caller of the template has no control over error handling. To improve this, capability to specify an error sequence is brought in. 

```
 <call-template target="MyTemplate" onError="TemplateFaultSeq">
       <with-param name="param1" value="{$ctx:nonExistingProperty}"/>
 </call-template> 
```

**Affected Product Version:**

All ESB/EI/MI versions

**Comment by abeykoon** [comment]
I am working on a fix which will address scenarios 1-5. 
Marking this critical as this functionality is important for connector implementations.

**Comment by abeykoon** [comment]
Error code suggested - `500101`
Error message - mandatory parameter 'x' required by SequenceTemplate 'y' is not provided.

**Comment by Nirothipan** [comment]
Related issue https://github.com/wso2/micro-integrator/issues/1561

**Comment by abeykoon** [comment]
fixed by PR: https://github.com/wso2/wso2-synapse/pull/1559

**Comment by abeykoon** [comment]
documentation aspect: https://github.com/wso2/micro-integrator/issues/1697

**Comment by sdkottegoda** [comment]
Duplicated by https://github.com/wso2/micro-integrator/issues/1561
