### ISSUE TITLE
Issue when Re Deploying Message Processor

### ISSUE THREAD

**Issue by malakaganga** [wso2/micro-integrator#1676]
**Description:**
If you deploy a message processor in 2 nodes clusterwith status as deactivated (maybe message store become a failure) then undeploy the Capp and again deploy it (with status active) still the Message Processor will be in Deactivated state

This is due to registry entry not getting deleted at the Capp undeployment

**Comment by Nirothipan** [comment]
Fixed in https://github.com/wso2/micro-integrator/pull/1705 . 
Related Issue https://github.com/wso2/micro-integrator/issues/1700
