### ISSUE TITLE
When the Message Processor gets deactivated due to an issue, it keeps deactivated state even after restarting the server. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1700]
**Description:**
After redeploying a carbon application / restarted the server, the Message Processor goes to a Paused state. 

If the Message Processor gets deactivated due to some issue (as an example, the endpoint not existing), even if the car file is redeployed and the server is restarted, the message processor is in the PAUSED state. 

```
[2020-06-17 17:22:23,953]  INFO {ScheduledMessageProcessor} - Started message processor. [Processor1].
[2020-06-17 17:22:23,953]  INFO {AbstractQuartzTaskManager} - Task paused: [ESB_TASK][MSMP_Processor1_0]
[2020-06-17 17:22:23,954]  INFO {ScheduledMessageProcessor} - Successfully deactivated the message processor [Processor1]
```
In /mi-home/registry/governance/repository/components/org.apache.synapse.message.processor/Processor1.properties file, 
**MESSAGE_PROCESSOR_STATE=PAUSED**

Tested pack: https://wso2.org/jenkins/job/products/job/micro-integrator/lastSuccessfulBuild/artifact/distribution/target/wso2mi-1.2.0-SNAPSHOT.zip

[JMSMessageStoreCompositeApplication_1.0.0.car.zip](https://github.com/wso2/micro-integrator/files/4792291/JMSMessageStoreCompositeApplication_1.0.0.car.zip)

**Comment by ThijsFTW** [comment]
Still an issue with Integration Studio 8.2.0!!!!!!!!!!!!!

**Comment by lghoon** [comment]
yes!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! big issue...

**Comment by kalaiyarasiganeshalingam** [comment]
Encountered this issue with WSO2MI-4.3.0-alpha as well.

**Comment by joeypat** [comment]
Best solution I've found with this using wso2MI-4.3.0 is going into your home folder and searching for the name of your message processor. Delete all files relating to it and restart your server. An annoying work around but it worked for me. Hope it helps!
