### ISSUE TITLE
[Hot Deployment]When it deploys with the same name of the synapse artifacts which are already deployed, it does not throw an error. 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1706]
**Description:**
When we have already deployed a set of synapse artifacts through one carbon application, and if we are going to deploy another carbon application with the same synapse names, it does not throw an error. Instead, it just ignores. 

**Steps to Reproduce**
1. Start the micro integrator.
2. Deploy the RabbitMQMessageStoreCompositeApplication_1.0.0.car application. 
3. Then deploy the JMSMessageStoreCompositeApplication_1.0.0.car carbon application (hot deployment). 

The both .car apps have proxies as proxy1. 
**Expected**: It should throw an error in the carbon logs. 
**Actual**: It ignores the artifacts as below. 
```
[2020-06-17 22:33:54,403]  WARN {ProxyServiceDeployer} - Hot deployment thread picked up an already deployed proxy - Ignoring
[2020-06-17 22:33:54,404]  WARN {ProxyServiceDeployer} - Hot deployment thread picked up an already deployed proxy - Ignoring
```

**Tested Environment**
- Pack:
https://wso2.org/jenkins/job/products/job/micro-integrator/lastSuccessfulBuild/artifact/distribution/target/wso2mi-1.2.0-SNAPSHOT.zip

- Stand-alone server and in the 2 node cluster. 

[carbonapps.zip](https://github.com/wso2/micro-integrator/files/4794149/carbonapps.zip)

**Comment by Nirothipan** [comment]
The behavior is same in EI 6.6.0 as well. Basically we are simple  ignoring the duplicate proxies in https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/deployers/ProxyServiceDeployer.java#L70
