### ISSUE TITLE
Check which connector icons needs to be updated 

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1748]
**Description:**

Some connectors in the below list still has old icons. Need to find and update them. 
Example: https://ei.docs.wso2.com/en/latest/micro-integrator/references/connectors/redis-connector/redis-connector-example/

File connector
Kafka connector
Salesforce
DB event listener
Microsoft dynamics 365 - not done
Google firebase
Gmail
LDAP
Slack
FHIR
ISO8583
Amazon S3
Salesforce REST
Amazon Lambda
ServiceNow
Magento 
Salesforce inbound EP
ISO 8583 inboundEP
Workday - not done
Netsuite - not done
Amazon Simple Queue Service
Amazon SQS Inbound EP
Microsoft Azure Storage
PCML AS400
SMPP
SF Bulk (SFDC)
Redis
Amazon dynamo DB
BigQuery
Google pub/sub
Google Spreadsheet
SMPP -  Streaming Inbound Endpoint

**Comment by tishan89** [comment]
@abeykoon I found another doc issue related to connectors. it was a small fix too.. can we set a date and get minor connector doc improvements done
