### ISSUE TITLE
Add new screenshots for common connector page

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1749]
**Description:**

As a part of EI connector improvement effort, we are revamping docs related to using connectors. The way we have structured it is, as importing a connector is common to all the connector document pages, we made a common doc and embedded it to all the connector docs. 

To do this in the common page, we have used Salesforce connector as an example. However, recently a customer has raised some concern as he is seeing  screenshots related to Salesforce when he is reading through some other connector doc. So we need to represent a "WSO2 EI Connector" in a common manner. 

Common document is [1]. 

[1]. https://github.com/wso2/docs-ei/blob/master/en/micro-integrator/docs/references/connectors/importing-connector-to-integration-studio.md

**Comment by tishan89** [comment]
@samgnaniah have we started work on this?

**Comment by samgnaniah** [comment]
@tishan89 this can be closed now.
