### ISSUE TITLE
Unit Test suit giving error while running the test case - mapping failed Error 

### ISSUE THREAD

**Issue by satyasivaprasad1982** [wso2/micro-integrator#1760]
**Description:**

While running the Unit Test Suite in Integration Stuido(7.0.2) and using using microesb runtime "WSO2 Micro Integrator 1.2.0-m4" on Windows 10, its giving error, -, looks like carriage return character (&#13;) causing the issue ?
[2020-06-28 12:14:32,970] ERROR {org.wso2.carbon.mediator.datamapper.DataMapperMediator} - DataMapper mediator : mapping failed Error while reading input stream. Script engine unable to execute the script javax.script.ScriptException: <eval>:1:36 Expected ident but found &
var inputroot={ "name": "John Doe" ,&#13;"dob": "1990-03-19" ,&#13;"ssn": "234-23-525" ,&#13;"address": "California" ,&#13;"phone": "8770586755" ,&#13;"email": "johndoe@gmail.com" ,&#13;"doctor": "thomas collins" ,&#13;"hospital": "grand oak community hospital" ,&#13;"cardNo": "7844481124110331" ,&#13;"appointment_date": "2025-06-02"&#13;}
                                    ^ in <eval> at line number 1 at column number 36 

**Suggested Labels:**

**Suggested Assignees:**

Nirothipan

**Affected Product Version:**
WSO2 Micro Integrator 1.2.0-m4
[Using_MI_1.2.0-m4_Mapping_Failed_error.log](https://github.com/wso2/micro-integrator/files/4841877/Using_MI_1.2.0-m4_Mapping_Failed_error.log)

**OS, DB, other environment details and versions:**   
Windows 10 

**Steps to reproduce:**
Created the Unit Test suite as explained in the Micro Integrator video session by Nirothipan  - "WSO2 Integration Studio - Design, Test, Debug and Deploy Integrations". While running the Unit Test using Default local server configuration(9008 and embedded MI)

**Related Issues:**

With the embedded MI that comes with Integration studio - "WSO2-Integration-Studio-7.0.2-win32-x86_64", its giving below error: 
TID: [PassThroughMessageProcessor-1enantId] [2020-06-28 13:18:09,207] ERROR {org.wso2.carbon.mediator.datamapper.DataMapperMediator} - DataMapper mediator : mapping configuration is null
TID: [PassThroughMessageProcessor-1enantId] [2020-06-28 13:18:09,211] ERROR {API_LOGGER.HealthcareAPI} - DataMapper mediator : mapping configuration is null
TID: [PassThroughMessageProcessor-1enantId] [2020-06-28 13:18:09,239]  WARN {API_LOGGER.HealthcareAPI} - Executing fault handler due to exception encountered

[Using_MI_Studio__7.0.2_Mapping_Configuration_null.log](https://github.com/wso2/micro-integrator/files/4841879/Using_MI_Studio__7.0.2_Mapping_Configuration_null.log)

**Comment by sajithaliyanage** [comment]
We have fixed a similar issue[1] in the latest Integration Studio 7.1.0-alpha pack[2]. Shall we test this scenario again with the alpha pack(only for the testing purpose) and check whether issue is still there? Also, share the Unit Test Suite artifact you have created for further analysis. 

[1] - https://github.com/wso2/micro-integrator/issues/1428
[2] - https://github.com/wso2/devstudio-tooling-ei/releases/tag/v7.1.0-alpha

**Comment by satyasivaprasad1982** [comment]
Hi,
I have downloaded the studio-v7.1.0-alpha and tried to send a Rest request, but it seems the requests are not processed. It says - 
ERROR_CODE = 0, ERROR_MESSAGE = Provided origin URL * is malformed.
Please see attached error log. 
The same code is working fine with -v7.0.2.
I think I should test the Unit Test suite after the above issues gets resolved. I have also uploaded the zipped folder structure of the projects from workspace.
[Request_not_getting_processed.log](https://github.com/wso2/micro-integrator/files/4845166/Request_not_getting_processed.log)
[HealthcareService2.zip](https://github.com/wso2/micro-integrator/files/4845179/HealthcareService2.zip)

**Comment by satyasivaprasad1982** [comment]
Hi,
I encountered another bigger issue, that is,  I opened my existing workspace with the studio of v7.1.0-alpha. 
Now, I am trying to use the same workspace with v7.0.2, I am not able to run any of the projects. Generally I do this by right clicking the composite application projects and click ' Export project Artifacts and Run' , it is giving me error - "Please select a valid carbon application project", Can you please help me on this, I am literally stuck and not able to run any of my existing projects.

Regards,
Satya
![Not_able_to_run_existing_project](https://user-images.githubusercontent.com/67531591/86008663-b8d21f00-ba36-11ea-9031-d7de88346412.PNG)
![Not_able_to_run_existing_project_next_blank_screen](https://user-images.githubusercontent.com/67531591/86008670-ba9be280-ba36-11ea-99b7-a74f46b045c8.PNG)

**Comment by satyasivaprasad1982** [comment]
Related to this, in the pom.xml, strangely it is showing the other open project artifacts as well which are no where related to the current composite project. 
![Other_Open_projects_are_shown_under_pom_xml](https://user-images.githubusercontent.com/67531591/86010275-d0aaa280-ba38-11ea-902b-edb7f03a5f47.PNG)

**Comment by Nirothipan** [comment]
> Hi,
> I have downloaded the studio-v7.1.0-alpha and tried to send a Rest request, but it seems the requests are not processed. It says -
> ERROR_CODE = 0, ERROR_MESSAGE = Provided orihttps://github.com/wso2/micro-integrator/issues/1650
> The same code is working fine with -v7.0.2.
> I think I should test the Unit Test suite after the above issues gets resolved. I have also uploaded the zipped folder structure of the projects from workspace.
> [Request_not_getting_processed.log](https://github.com/wso2/micro-integrator/files/4845166/Request_not_getting_processed.log)
> [HealthcareService2.zip](https://github.com/wso2/micro-integrator/files/4845179/HealthcareService2.zip)

We have fixed this issue https://github.com/wso2/micro-integrator/issues/1650 and for the moment , could you please open up deployment.toml in the embedded integration studio and remove the following content from it and work ( the embedded micro itnegrator can be found inside a folder named runtime in the pack ).

```json
[synapse_properties]
'synapse.rest.CORSConfig.enabled' = "true"
'synapse.rest.CORSConfig.Access-Control-Allow-Origin' = "*"
'synapse.rest.CORSConfig.Access-Control-Allow-Headers' = "content-type"
```

**Comment by rosensilva** [comment]
> Hi,
> I encountered another bigger issue, that is, I opened my existing workspace with the studio of v7.1.0-alpha.
> Now, I am trying to use the same workspace with v7.0.2, I am not able to run any of the projects. Generally I do this by right clicking the composite application projects and click ' Export project Artifacts and Run' , it is giving me error - "Please select a valid carbon application project", Can you please help me on this, I am literally stuck and not able to run any of my existing projects.
> 
> Regards,
> Satya
> ![Not_able_to_run_existing_project](https://user-images.githubusercontent.com/67531591/86008663-b8d21f00-ba36-11ea-9031-d7de88346412.PNG)
> ![Not_able_to_run_existing_project_next_blank_screen](https://user-images.githubusercontent.com/67531591/86008670-ba9be280-ba36-11ea-99b7-a74f46b045c8.PNG)

@prabushi please note the workspace issue with is-7. 0.2  to 7.1.0 alpha

**Comment by satyasivaprasad1982** [comment]
> > Hi,
> > I have downloaded the studio-v7.1.0-alpha and tried to send a Rest request, but it seems the requests are not processed. It says -
> > ERROR_CODE = 0, ERROR_MESSAGE = Provided orihttps://github.com/[/issues/1650](https://github.com/wso2/micro-integrator/issues/1650)
> > The same code is working fine with -v7.0.2.
> > I think I should test the Unit Test suite after the above issues gets resolved. I have also uploaded the zipped folder structure of the projects from workspace.
> > [Request_not_getting_processed.log](https://github.com/wso2/micro-integrator/files/4845166/Request_not_getting_processed.log)
> > [HealthcareService2.zip](https://github.com/wso2/micro-integrator/files/4845179/HealthcareService2.zip)
> 
> We have fixed this issue #1650 and for the moment , could you please open up deployment.toml in the embedded integration studio and remove the following content from it and work ( the embedded micro itnegrator can be found inside a folder named runtime in the pack ).
> 
> ```json
> [synapse_properties]
> 'synapse.rest.CORSConfig.enabled' = "true"
> 'synapse.rest.CORSConfig.Access-Control-Allow-Origin' = "*"
> 'synapse.rest.CORSConfig.Access-Control-Allow-Headers' = "content-type"
> ```

Thanks Nirothipan, now I have amended deployment.toml and I am able to run the project and send the REST requests and they are getting processed.
I proceeded to test the Unit test suit, which is my original issue. Unit Test suite is not running, it is giving an unhandled even loop exception when I click on the Run button of 'Unit Test Run Configuration' screen. I have attached the workspace log and the screenshot.
![Unit_Test_Suite_not_running](https://user-images.githubusercontent.com/67531591/86038543-bb486f00-ba5e-11ea-9f8e-77a29ba8725f.PNG)
[Workspace_Log.txt](https://github.com/wso2/micro-integrator/files/4847166/Workspace_Log.txt)

**Comment by prabushi** [comment]
> > Hi,
> > I encountered another bigger issue, that is, I opened my existing workspace with the studio of v7.1.0-alpha.
> > Now, I am trying to use the same workspace with v7.0.2, I am not able to run any of the projects. Generally I do this by right clicking the composite application projects and click ' Export project Artifacts and Run' , it is giving me error - "Please select a valid carbon application project", Can you please help me on this, I am literally stuck and not able to run any of my existing projects.
> > Regards,
> > Satya
> > ![Not_able_to_run_existing_project](https://user-images.githubusercontent.com/67531591/86008663-b8d21f00-ba36-11ea-9031-d7de88346412.PNG)
> > ![Not_able_to_run_existing_project_next_blank_screen](https://user-images.githubusercontent.com/67531591/86008670-ba9be280-ba36-11ea-99b7-a74f46b045c8.PNG)
> 
> @prabushi please note the workspace issue with is-7. 0.2 to 7.1.0 alpha
We could not replicate the mentioned behavior while migrating a workspace from 7.0.2 to 7.1.0. 
@satyasivaprasad1982 Would it be possible for you to attach your workspace? Also, as per your comment, were you able to run with the embedded MI on the 7.0.2 workspace afterward?

**Comment by prabushi** [comment]
> > > Hi,
> > > I have downloaded the studio-v7.1.0-alpha and tried to send a Rest request, but it seems the requests are not processed. It says -
> > > ERROR_CODE = 0, ERROR_MESSAGE = Provided orihttps://github.com/[/issues/1650](https://github.com/wso2/micro-integrator/issues/1650)
> > > The same code is working fine with -v7.0.2.
> > > I think I should test the Unit Test suite after the above issues gets resolved. I have also uploaded the zipped folder structure of the projects from workspace.
> > > [Request_not_getting_processed.log](https://github.com/wso2/micro-integrator/files/4845166/Request_not_getting_processed.log)
> > > [HealthcareService2.zip](https://github.com/wso2/micro-integrator/files/4845179/HealthcareService2.zip)
> > 
> > 
> > We have fixed this issue #1650 and for the moment , could you please open up deployment.toml in the embedded integration studio and remove the following content from it and work ( the embedded micro itnegrator can be found inside a folder named runtime in the pack ).
> > ```json
> > [synapse_properties]
> > 'synapse.rest.CORSConfig.enabled' = "true"
> > 'synapse.rest.CORSConfig.Access-Control-Allow-Origin' = "*"
> > 'synapse.rest.CORSConfig.Access-Control-Allow-Headers' = "content-type"
> > ```
> 
> Thanks Nirothipan, now I have amended deployment.toml and I am able to run the project and send the REST requests and they are getting processed.
> I proceeded to test the Unit test suit, which is my original issue. Unit Test suite is not running, it is giving an unhandled even loop exception when I click on the Run button of 'Unit Test Run Configuration' screen. I have attached the workspace log and the screenshot.
> ![Unit_Test_Suite_not_running](https://user-images.githubusercontent.com/67531591/86038543-bb486f00-ba5e-11ea-9f8e-77a29ba8725f.PNG)
> [Workspace_Log.txt](https://github.com/wso2/micro-integrator/files/4847166/Workspace_Log.txt)

We have already identified and fixed the mentioned [issue](https://github.com/wso2/devstudio-tooling-ei/issues/1030) after the alpha release. We will let you know once our next release is available.

**Comment by satyasivaprasad1982** [comment]
> > > Hi,
> > > I encountered another bigger issue, that is, I opened my existing workspace with the studio of v7.1.0-alpha.
> > > Now, I am trying to use the same workspace with v7.0.2, I am not able to run any of the projects. Generally I do this by right clicking the composite application projects and click ' Export project Artifacts and Run' , it is giving me error - "Please select a valid carbon application project", Can you please help me on this, I am literally stuck and not able to run any of my existing projects.
> > > Regards,
> > > Satya
> > > ![Not_able_to_run_existing_project](https://user-images.githubusercontent.com/67531591/86008663-b8d21f00-ba36-11ea-9031-d7de88346412.PNG)
> > > ![Not_able_to_run_existing_project_next_blank_screen](https://user-images.githubusercontent.com/67531591/86008670-ba9be280-ba36-11ea-99b7-a74f46b045c8.PNG)
> > 
> > 
> > @prabushi please note the workspace issue with is-7. 0.2 to 7.1.0 alpha
> 
> We could not replicate the mentioned behavior while migrating a workspace from 7.0.2 to 7.1.0.
> @satyasivaprasad1982 Would it be possible for you to attach your workspace? Also, as per your comment, were you able to run with the embedded MI on the 7.0.2 workspace afterward?

The issue is there with the backward compatibility - that is going back to v7.0.2 from 7.1.0
Steps to replicate issue:
1. Create a workspace or project using v7.0.2, run the project using the integrated MI.
2. Open the same workspace using 7.1.0, run the project using the integrated MI.
3. Now, go back to the 7.0.2 and open the same workspace and try to run the project using the integrated MI. You can see the problem that I reported - "Please select a valid carbon application project"

**Comment by tishan89** [comment]
Original issue is fixed and going back and forth between older versions is a rare occurrence. Also the issue is stale for several months. Hence closing this off. Feel free to reopen.
