### ISSUE TITLE
Capability to enable tracing dynamically

### ISSUE THREAD

**Issue by sdkottegoda** [wso2/micro-integrator#1763]
**Description:**
This issue is for dynamically enabling tracing for synapse artifacts. There are 2 options we need to think about.

1. Enabling tracing globally.
2. Enabling tracing per artifact.

IMO, enabling tracing globally will be the better approach since it'll be a one time task. However, the performance impact in this approach will be higher. Allowing bother options will be the best if time permits.

**Comment by tishan89** [comment]
We will be going ahead with option two. Also please consider that there shouldn't be a requirement to re-deploy the artifact

**Comment by Nirothipan** [comment]
Management API support is added in 
https://github.com/wso2/micro-integrator/pull/1786
https://github.com/wso2/micro-integrator/pull/1785
https://github.com/wso2/micro-integrator/pull/1779
https://github.com/wso2/micro-integrator/pull/1782
https://github.com/wso2/micro-integrator/pull/1784

**Comment by Nirothipan** [comment]
Dashboard support is added with https://github.com/wso2/product-mi-tooling/pull/52
