### ISSUE TITLE
Datasources are missing in the dashboard

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1812]
**Description:**
Currently dashboard doesn't have datasources listed.

The suggested approach for implementing this feature includes the following subtasks.

- [x] https://github.com/wso2/product-mi-tooling/issues/234
- [x] https://github.com/wso2/product-mi-tooling/issues/233
- [x] https://github.com/wso2/docs-apim/issues/5044

**Comment by dulanjalidilmi** [comment]
This will be implemented by https://github.com/wso2/micro-integrator/issues/1997

**Comment by dulanjalidilmi** [comment]
These would be the initial templates for datasource page

![MI_Monitoring_Dashboard-DataSources](https://user-images.githubusercontent.com/38608578/97426607-b676c780-1939-11eb-963f-977b0cb30c6d.jpg)
![MI_Monitoring_Dashboard-DataSources_Navigational_Panel](https://user-images.githubusercontent.com/38608578/97426623-bb3b7b80-1939-11eb-9dd3-449f49a6dead.jpg)

**Comment by SanojPunchihewa** [comment]
Updated design for the data sources will be as follows,

![data-source-list](https://user-images.githubusercontent.com/18748929/139805411-5e45ae79-2d3c-4b7a-a979-b09f74ed3b16.png)

![data-source-detailed](https://user-images.githubusercontent.com/18748929/139805492-17e6dc24-4888-4fd2-bc45-a8629b2d9a3e.png)
