### ISSUE TITLE
Dashboard JDBC Message Store Passwords are in plaintext

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1813]
**Description:**
The passwords are in plain text in the dashboard

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed in 
https://github.com/wso2/product-mi-tooling/pull/65
https://github.com/wso2/micro-integrator/pull/1850
