### ISSUE TITLE
Priviledge user cannot add users from the dashboard

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1814]
**Steps to reproduce:**
1. The deployment.toml configs are as below. 
```
[user_store]
type = "read_only_ldap"
connection_url = "ldap://10.110.5.230:10389"
connection_name = "uid=admin,ou=system"
connection_password = "admin"
user_search_base = "ou=Users,dc=wso2,dc=org"

[internal_apis.file_user_store]
enable = false

[[management_api.authorization_handler.resources]]
path = "/user"

````

2. Start WSO2 Identity Server and ldap configs are listed as above.
3. Start micro integrator and the dashboard. 
4. Create an admin user which is user1. 
5. Login to the dashboard with user1 credentials. 
6. Go to users and try to add a new user. 

**Expected**: The user should be added. 
**Actual**: The user cannot be added. Getting 'Unknown error occurred while processing request. Please check server logs'. But there are no error logs in the carbon log.

**Comment by Nirothipan** [comment]
Should be same as https://github.com/wso2/micro-integrator/issues/1805
