### ISSUE TITLE
Secret creation does not work in CLI, if you execute the command in CLI home folder 

### ISSUE THREAD

**Issue by arunans23** [wso2/micro-integrator#1825]
**Description:**

Secret creation does not work in CLI, if you execute the command in the CLI home folder. Currently it works only if you specifically run the command inside <CLI-HOME>/bin

**Affected Product Version:**
MI 1.2.0-beta

**Comment by Nirothipan** [comment]
Its a limitation and should be already in docs

**Comment by Nirothipan** [comment]
Fixed in https://github.com/wso2/product-mi-tooling/pull/63 . Need to update docs.

**Comment by Nirothipan** [comment]
Fixed in https://github.com/wso2/product-mi-tooling/pull/63 . Need to update docs.
