### ISSUE TITLE
Enables and Disable Stats/Tracing in Artifacts (using dashboard and CLI)

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/micro-integrator#1830]
**Description:**
In WSO2 Integration Studio, it is possible to enable/disable statistics as well as tracing for the following artifacts:

- rest API
- poxy service
- inbound endpoint
- sequence
- endpoint

Can we enable these functions for the **Micro Integrator Dashboard** and the **CLI** as well?

**Affected Product Version:**
EI 7.1.0 

**OS, DB, other environment details and versions:**    
MacOS

**Comment by tishan89** [comment]
Support for endpoint is added https://github.com/wso2/product-mi-tooling/pull/79
