### ISSUE TITLE
[Dashboard] Rabbitmq message store message count appears as -1

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1831]
**Description:**
$subject.

<img width="1334" alt="Screen Shot 2020-07-10 at 4 12 56 PM" src="https://user-images.githubusercontent.com/6702569/87146232-42e87600-c2c8-11ea-8a09-efcf2db20431.png">

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
In synapse it is implemented for In Memory and JDBC , other will return -1 https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/message/store/AbstractMessageStore.java#L172 . I think we can just skip this attribute in Dashbaord ( not display ) , wydt

**Comment by Nirothipan** [comment]
Removed the attribute as per offline discussion https://github.com/wso2/product-mi-tooling/pull/69
