### ISSUE TITLE
Incorrect url is returned for an API with version 

### ISSUE THREAD

**Issue by prabushi** [wso2/micro-integrator#1837]
**Description:**
The URL returned for an API with a version using the MI CLI is incorrect. 
**Example API configuration:**
```
<?xml version="1.0" encoding="UTF-8"?>
<api context="/HelloWorld" name="HelloWorld" version="2.0.0" version-type="url" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET">
        <inSequence>
            <payloadFactory media-type="json">
                <format>{"Hello":"World"}</format>
                <args/>
            </payloadFactory>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>

```

**Expected:**
http://localhost:8290/HelloWorld/2.0.0

**Returned:**
http://localhost:8290/HelloWorld

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
WSO2 MI 1.2.0-beta

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Fixed in https://github.com/wso2/micro-integrator/pull/1851
