### ISSUE TITLE
NATS support

### ISSUE THREAD

**Issue by a5anka** [wso2/micro-integrator#184]
Currently, we have to rely on extensions to allow communication with NATS servers. It is better if we can support this by default.

- [x] NATS connector
- [ ] NATS Inbound Endpoint

**Comment by sdkottegoda** [comment]
NATS connector support has been added by https://github.com/wso2-extensions/esb-connector-nats

The NATS unbound endpoint is under implementation

**Comment by sdkottegoda** [comment]
Reopen
The following tasks are remaining

1. Re-open and test https://github.com/wso2/micro-integrator/pull/1636 and https://github.com/wso2/carbon-mediation/pull/1402 
2. Write documentation
3. Write integration tests
