### ISSUE TITLE
Modify connector archetype so that licence.txt file get packed in the connector distribution 

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1852]
**Description:**

Currently, we have LICENCE.txt file in the connector repository and the archetype, but it is not added to the connector.zip file.
Let's modify the connector archetype to pack the  LICENCE.txt to the distribution (update pom.xml)

**Comment by abeykoon** [comment]
At the same time let's add sample icons to the archetype as well. Following are the icons. 
![icon-large](https://user-images.githubusercontent.com/4967046/87510820-e2738300-c691-11ea-970b-09d51b1655be.png)
![icon-small](https://user-images.githubusercontent.com/4967046/87510824-e43d4680-c691-11ea-9145-289ce5a9fe35.png)
![wso2](https://user-images.githubusercontent.com/4967046/87510827-e56e7380-c691-11ea-9522-cae5ac38f10c.png)

**Comment by dinuish94** [comment]
Shall we update the license headers as well?

**Comment by dinuish94** [comment]
The following dependency in the pom.xml,
```xml
        <dependency>
            <groupId>org.wso2.ei</groupId>
            <artifactId>org.wso2.carbon.integrator.core</artifactId>
            <version>${product.ei.version}</version>
        </dependency>
```

should be updated as 
```xml
        <dependency>
            <groupId>org.wso2.carbon.mediation</groupId>
            <artifactId>org.wso2.carbon.integrator.core</artifactId>
            <version>${carbon.mediation.version}</version>
        </dependency>
```

**Comment by niruhan** [comment]
Adding license to the build zip is done in https://github.com/wso2-extensions/archetypes/pull/28
