### ISSUE TITLE
Improve the SAP adaptor to support inner table and structs

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/micro-integrator#1854]
**Description:**
To allow the use of deep structures in the import parameter it is necessary to evaluate all the different node types. Therefore the sap adaptor should be improved to nest structures inside structures, tables inside structures, and structures inside tables.

**Suggested Labels:**
EI-6.6.0, MI1.1.0

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**
Correspoding EI Issue : https://github.com/wso2/product-ei/issues/5195

**Comment by tishan89** [comment]
Closing since feature is done
