### ISSUE TITLE
"This page isn’t working" is shown after trusting the Management API from the browser

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/micro-integrator#1871]
**Description:**
After adding the micro integrator instance to the browser as a trusted source by directing the browser to https://<machine_ip>:9164/management, the browser will display the following page with 401 error. This is not a good first-time experience for the prospects IMHO. As a suggestion, we can give a meaningful message on the page or redirect to the dashboard if possible. 

<img width="843" alt="Screen Shot 2020-07-16 at 3 35 14 PM" src="https://user-images.githubusercontent.com/17607360/87667876-b7b82600-c788-11ea-97ec-e4eeca6866fd.png">

**Suggested Labels:**
type/improvement

**Affected Product Version:**
MI-1.1.0

**Comment by Nirothipan** [comment]
We have  fixed this for the next release https://github.com/wso2/micro-integrator/pull/1864
