### ISSUE TITLE
[Salesforce Rest] Refresh call is getting called each time

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1904]
When the access token is expired , refresh token call is getting called for each execution and in addition its response is printed in the log and we need to avoid that too.

```bash
[2020-07-21 20:48:05,372]  INFO {RefreshAccessToken} - {proxy:CSVToSalesForce} Refresh call response : HttpResponseProxy{
```

**Comment by niruhan** [comment]
Fixed with https://github.com/wso2-extensions/esb-connector-salesforcerest/pull/44 and https://github.com/wso2/carbon-mediation/pull/1453
