### ISSUE TITLE
Upgrade HTTP Core NIO Dependnecy

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#1933]
We are using an older http core nio which is 4.3.3 and the latest is 5.0.1 https://github.com/apache/httpcomponents-core. It is better if we update this  as the master is more active and we lag far behind.

**Comment by arunans23** [comment]
Since Httpcore 5.x has a significant change, it was decided to upgrade to the latest Httpcore version in 4.4.x series.
