### ISSUE TITLE
Keystore file location cannot be defined in the deployment.toml

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#1940]
**Description:**
The filename has to be defined for the keystore file instead of the location. Earlier we could define the file location.

```
<Security>
 <KeyStore>            
           <Location>${carbon.home}/repository/resources/security/wso2carbon.jks</Location>
            <Type>JKS</Type>
            <Password>wso2carbon</Password>
            <KeyAlias>wso2carbon</KeyAlias>
         <KeyPassword>wso2carbon</KeyPassword>
        </KeyStore>
</Security>
```

[1] https://ei.docs.wso2.com/en/7.1.0/micro-integrator/references/config-catalog/#primary-keystore

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
Closing this issue since it is fixed via https://github.com/wso2/micro-integrator/pull/1965
