### ISSUE TITLE
RabbitMQ blocking transport sender cannot configure in the deployment.toml file

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/micro-integrator#1942]
**Description:**

The following configuration does not work.
```
[transport.blocking.rabbitmq]
sender_enable = true
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
wso2mi-1.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
Closing the issue, since it is fixed in master.
