### ISSUE TITLE
Issue in cipher tool when an empty password is provided

### ISSUE THREAD

**Issue by dilini-muthumala** [wso2/micro-integrator#1947]
**Description:**
When running the Micro Integrator, without password-persist file it asks to provide the password. When we enter the correct password it proceeds and starts the server. When we enter a wrong password it gives an error. But when we hit enter without giving any password still it starts the server similarly as in the case we enter the correct password.

**Affected Product Version:**
The issue exists in micro integrator-1.1.0 & micro integrator-1.2.0 

**Steps to reproduce:**
- Use a WSO2 Micro Integrator-1.1.0 pack
- Run cipher tool. For that, navigate to <WSO2 MI>/bin and execute `./ciphertool.sh -Dconfigure`. Password of the keystore shipped by default with WSO2 MI is 'wso2carbon'
- First you can add password-persist file with default password to <WSO2 MI> Home and run the server. It starts without prompting for password
- Now remove the password persist file and start the server, now it asks to provide the password
- When you give a wrong password it gives an error mentioning the password is wrong
- When you give the correct password it proceeds and starts the server.
- When you hit enter without giving any password still it starts the server similarly as in the case we enter the correct password, which is wrong and it suppose to give an error.

**Comment by Vathsan** [comment]
This is fixed for MI 1.2.0 in https://github.com/wso2-support/carbon-secvault/pull/1
