### ISSUE TITLE
Embedded MI Resource

### ISSUE THREAD

**Issue by Stiff-uc** [wso2/micro-integrator#1952]
**Description:**
Defining inbound endpoints using keys from registry resource projects is reading incorrect data from resource file content

**Affected Product Version:**
MI-1.2.0

**OS, DB, other environment details and versions:**    
WSO2 Integration Studio: 7.1.0 integrated MI

**Steps to reproduce:**
Create file inbound endpoint to listen a folder as follows:
<parameter key="conf:/custom/someurl.txt" name="transport.vfs.FileURI"/>
Create a resource project, put a someurl.txt file in config repository under custom/ subfolder
Enter a valid path to a folder as a single line in that file
Expected result (works well in MI-1.1.0):
Inbound endpoint will catch up that value and start polling the folder.
Actual result:
Inbound endpoint reads a line from someurl.txt and adds '\r\n'
logs are spamming with:
[2020-08-21 10:38:32,899]  WARN {FilePollingConsumer} - Unable to access or read file or directory : C:\temp\IN
. Reason: The file does not exists!

See the code I see in org.wso2.micro.integrator.registry_1.2.0.jar in class MicroIntegratorRegistry.java:986 in embedded MI:
while((line = bReader.readLine()) != null) {
  strBuilder.append(line);
  strBuilder.append(NEW_LINE_CHAR);
}

Seems like this always adds a newline even for one-line reads

**Comment by Vathsan** [comment]
@Stiff-uc Thanks for reporting the issue. We have found a fix for this issue. We will review the fix and make it available via WUM update.
