### ISSUE TITLE
Retrieve "routing key" from the RabbitMQ Inbound Endpoint consumed message.

### ISSUE THREAD

**Issue by Seralahthan** [wso2/micro-integrator#1958]
**Description:**
Current implementation of the RabbitMQ Inbound Endpoint **RabbitMQConsumer** doesn't support retrieving the **"routing key"** from the consumed message header [1]. 

There can be scenarios where two different exchanges publish message to same queue using different binding keys. 
In such cases, when consuming the message from that queue a need to identify the "routing key" of the message and use it in the mediation flow might arise. 

To handle this requirement, RabbitMQ Inbound Endpoint "RabbitMQConsumer" need to be improved to extract the "routing key" from the consumed message header. 

[1] https://github.com/wso2-support/micro-integrator/blob/support-1.2.0/components/mediation/inbound-endpoints/org.wso2.micro.integrator.inbound.endpoint/src/main/java/org/wso2/carbon/inbound/endpoint/protocol/rabbitmq/RabbitMQConsumer.java#L198

**Suggested Labels:**
Improvement

**Suggested Assignees:**

**Affected Product Version:**
MI-1.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by dbalasse** [comment]
This feature would be a great enhancement.
+1
