### ISSUE TITLE
Supporting legacy clients that cannot conduct URL encoding of API requests

### ISSUE THREAD

**Issue by lkokila** [wso2/micro-integrator#1968]
**Description:**
With regard to API resources, when legacy clients that cannot encode request URLs, send API requests with the following special characters the synapse engine does not capture the value and provides the error "Method not allowed for given API resource" or "Resource not found".
` ':', '/', '?', '#', '[', ']', '@', '!', '$', '&', '\'', '(', ')', '*', '+', ',', ';', '='`

This is a result of the findResource method (in the URITemplateBasedDispatcher class [1]) checking for the above-reserved characters while mapping the request to the resource (in the SimpleStringExpression class [2] ).

[1]. https://github.com/wso2/wso2-synapse/blob/master/modules/core/src/main/java/org/apache/synapse/rest/dispatch/URITemplateBasedDispatcher.java

[2]. https://github.com/wso2/wso2-synapse/blob/master/modules/commons/src/main/java/org/apache/synapse/commons/templates/uri/parser/SimpleStringExpression.java

**Affected Product Version:**
EI-7.1.0, APIM-3.1.0

**Steps to reproduce:**
Sample API resource
`<api context="/testContext" name="testAPI" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET" uri-template="/{testParam1}/{testParam2}}">`

Request URL ending up with the errors
`http://localhost:8290/testContext/123:456/abc,xyz`

When encoded the Request URL is as follows and the API is invoked successfully. 
`http://localhost:8290/testContext/123%3A456/abc%2Cxyz`

To support **legacy clients**, we can look into including functionality to escape special characters in the resource mapping process.

**Comment by lkokila** [comment]
A sample synapse handler to address the above requirement is available in [1]. 
[1]. https://github.com/lkokila/RequestEncodingSynapseHandler

**Comment by Nirothipan** [comment]
@lkokila since this an edge case, it would be better if we can address this via custom solution, Ideally the handler you have mentioned above and adding it as a default feature will not have a much of interest.

**Comment by lkokila** [comment]
@Nirothipan. makes sense. 

Anyhow, there's a better approach to address the above case by creating the synapse artefacts of the API resource as follows. (with a + character at the beginning of the parameters). 

```
<api context="/testContext" name="testAPI" xmlns="http://ws.apache.org/ns/synapse"> <resource methods="GET" uri-template="/{testParam1}/{testParam2}}">
---
```
The above API resource accepts requests that contain general delimiters that are not encoded as further explained in https://wso2.org/jira/browse/ESBJAVA-3435. 

A documentation update request is available in https://github.com/wso2/product-ei/issues/1482 for this. 

Thanks.

**Comment by lkokila** [comment]
I think this issue can be closed.
