### ISSUE TITLE
Tool to migrate registry data from previous ESBs to MI 1.2.0

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/micro-integrator#1977]
Currently, according to our migration instructions [1], it is necessary to migrate registry artifacts individually when migrating to MI 1.2.0 from a previous ESB. This process needs to be simplified using a tool that will help users migrate registry artifacts in bulk.

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/setup/deployment/migrating-from-esb-5.x.x/#migrating-the-registry

**Comment by wesleyforti** [comment]
+1
