### ISSUE TITLE
Implement a connector with utility functions

### ISSUE THREAD

**Issue by Asitha** [wso2/micro-integrator#1989]
**Description:**

There are some utility functions that are mostly used within Synapse that require a lot of manual effort. With this connector, we need to address the following identified utility functions 

- [ ] String operations
  - [ ] split
  - [ ] merge 
  - [ ] to lowercase
  - [ ] to uppercase
  - [ ] regex matching
  - [ ] length
  - [ ] get hash value
- [ ] Email validation
- [ ] pgp
  - [ ] encrypt and sign
  - [ ] decrypt
  - [ ] sign
  - [ ] validate 
- [ ] Generate UUID
- [ ] Date Time Operations (Similar to Java API)

**Affected Products:**
- Micro Integrator
- Integration Studio

**Comment by Asitha** [comment]
Maybe we need to split these functionalities into multiple connectors. Let's discuss...

**Comment by abeykoon** [comment]
I would like to see Strings operations out of the box in the product. 
Generate a UUID is another useful thing.

**Comment by tishan89** [comment]
Have we started any work on this?

**Comment by Asitha** [comment]
@abeykoon idea is to have these connectors pre-installed in integration studio, including CSV connector. Added UUID functionality to the list.

@tishan89 Not yet.

**Comment by tishan89** [comment]
We will need time based ones as well. i think we need to provide this as functions. 
Ex: <property value="fn:toLowercase($ctx:another_property)" name="new_property" scope="default" type="STRING"/>

**Comment by Asitha** [comment]
@tishan89 👍
