### ISSUE TITLE
[Gmail Connector] It does not receive emails constantly 

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1994]
**Description:**
When the Gmail connector is used, once the first email is sent and if the second email is sent in the next minute, it only receives the first email only. 
But if the second email is sent after one hour(approximately ), it receives the second email. No errors or warnings can be found in the log.

**Comment by arunans23** [comment]
This is the behaviour of the Gmail APIs. If you send the mail with the same content, the second mail won't be shown as received unless you send it after some time. But it will be visible in the Sent Box of the sender's mail. We cannot fix this at the connector level.
