### ISSUE TITLE
Update CLI tool and merge with APIM CLI

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/micro-integrator#1999]
**Description:**
The CLI tool in the MI should merge with the CLI tool in the APIM. We have to consider the enhancement of the MI dashboard and support them with the CLI. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by SanojPunchihewa** [comment]
Below figure shows the updated command tree for apictl
![apictl command tree](https://user-images.githubusercontent.com/18748929/101755616-18ab1680-3afb-11eb-8866-a1587f97ff02.png)

**Comment by sdkottegoda** [comment]
Closing this issue since it is resolved.
