### ISSUE TITLE
Update composite application deployer to handle versioning

### ISSUE THREAD

**Issue by indikasampath2000** [wso2/micro-integrator#2000]
**Description:**
We must ensure that removing and copying carbon applications with two different names but have the same set of artifacts would not impact the deployment. For example: let's say two carbon applications have MyAPI.xml.

MyAPICarbonApp-v1.car -> MyAPI.xml
MyAPICarbonApp-v2.car -> MyAPI.xml (modified synapse config)

In the CI/CD flow, if I remove the MyAPICarbonApp-v1.car and, at the same time, copying the MyAPICarbonApp-v2.car should successfully undeploy the MyAPICarbonApp-v1.car first and then deploy the MyAPICarbonApp-v2.car.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
According to the current axis2 implementation https://github.com/wso2/wso2-axis2/blob/d268954a968ebcc07c380d4e43e6f8421b774b62/modules/kernel/src/org/apache/axis2/deployment/repository/util/WSInfoList.java#L152, the deployer works as expected (first undeploy removed artifacts and then deploy new artifacts).
