### ISSUE TITLE
Log masking does not support for MI

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#2007]
MI does not currently support the log masking feature.

It should be supported with following configurations.

Replace the following lines in <MI_HOME>/conf/log4j2.properties file.
```
appender.CARBON_LOGFILE.layout.pattern = TID: [%tenantId] [%d] %5p {%c} - %mm%ex%n
appender.CARBON_CONSOLE.layout.pattern = [%d{DEFAULT}] %5p - %c{1} %mm%n
appender.AUDIT_LOGFILE.layout.pattern = TID: [%tenantId] [%d] %5p {%c} - %mm%ex%n
```
Add or uncomment the following line in the <MI_HOME>/conf/wso2-log-masking.properties to mask credit card informations.
```
[masking_pattern.properties]
"CREDIT_CARD_VISA" = "4[0-9]{6,}$"
"CREDIT_CARD_MASTER" = "(?:5[1-5][0-9]{2}|222[1-9]|22[3-9][0-9]|2[3-6][0-9]{2}|27[01][0-9]|2720)[0-9]{12}"
"CREDIT_CARD_AMEX" = "[34|37][0-9]{14}$"
```

**Comment by sajinieKavindya** [comment]
We need to improve the log masking feature to support the below patterns as well. 

Eg: only the username in an email address.
result: email: ********@gmail.com
