### ISSUE TITLE
Cannot deploy Registry Resource properties and Registry collections via CApps

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/micro-integrator#2009]
**Description:**
The feature to deploy registry resource properties via CApps is missing in MI-1.2.0. In EI-6.x, users can add the registry properties to the registry resources via the Management Console. But, there is no such capability in Micro Integrator Dashboard at the moment.

Therefore, we need to add this feature to deploy registry resource properties via CApps since this would be a blocker for the users who migrate from EI-6.x to EI-7.1.0 with registry properties.

**Affected Product Version:**
MI-1.2.0

**Comment by arunans23** [comment]
Fixed with https://github.com/wso2/micro-integrator/pull/1993
