### ISSUE TITLE
Masking Sensitive Information in Logs solution is invalid for MI

### ISSUE THREAD

**Issue by fatihozmen** [wso2/micro-integrator#2012]
**Description:**
Masking Sensitive Information in Logs MI solution informed in https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/logs/masking_sensitive_info_in_logs/#! doesn't work. Masking is not possible with that guide for MI. Enabling log masking feature doesn't work.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
7.1.0

**OS, DB, other environment details and versions:**    
Windows OS

**Steps to reproduce:**

**Related Issues:**

**Comment by Nirothipan** [comment]
Yes, this is a bug. we have fixed with https://github.com/wso2/micro-integrator/issues/2007. The docs need to be updated

**Comment by fatihozmen** [comment]
I actually made those changes before submit issue, please check the files I changed and add here txt version:

log4j2.porperties:
[log4j2.properties file txt ver.txt](https://github.com/wso2/micro-integrator/files/5529773/log4j2.properties.file.txt.ver.txt)

wso2-log-masking.properties
[wso2-log-masking txt ver.txt](https://github.com/wso2/micro-integrator/files/5529792/wso2-log-masking.txt.ver.txt)

![image](https://user-images.githubusercontent.com/33903008/98926900-f36dbd00-24e8-11eb-9232-1dd2c0d00a37.png)


If you see the error or missing point, I would appreciate it if you could say so.

**Comment by Nirothipan** [comment]
Hi @fatihozmen , this is not just a doc issue. This is a code level bug, even if you fix the files, it won't work unless you have a WUM update.

**Comment by fatihozmen** [comment]
> Hi @fatihozmen , this is not just a doc issue. This is a code level bug, even if you fix the files, it won't work unless you have a WUM update.

Hi Nirothipan, thank you for your help, what I need to do on WUM?

**Comment by Nirothipan** [comment]
Hi @fatihozmen , You need a WSO2 Subscription to start using the update service. Please visit https://wso2.com/updates/wum to check. Else you can get this fix in the next public release ( tentatively q1 of 2021 ). Thanks !

**Comment by fatihozmen** [comment]
I have changed and added the files you demonstrated in #2008. And it worked. Thanks for that. In LogMaskConverter.java we are masking all with defined "******" string, can we make it dynamic? Is it possible to use two regex, one for matching and one for which part we want to mask? For instance, for credit cards **** **** **** 4444 .And last question about that, if we connect MI with kafka this masking will effect the logs  collected by kafka or not?

**Comment by fatihozmen** [comment]
I figured out. Thanks for all.
