### ISSUE TITLE
Ciphertool doesn't encrypt the password in files pointed in cipher-tool.properties

### ISSUE THREAD

**Issue by serrodcal** [wso2/micro-integrator#2049]
**Description:** In a clean version of Micro-integrator 1.2.0 (recently downloaded) Ciphertool doesn't encrypt the files are pointed in `cipher-tool.properties`.

**Suggested Labels:** bug

**Suggested Assignees:**

**Affected Product Version:** 1.2.0

**OS, DB, other environment details and versions:**   MacOS Catalina 10.15.7, JDK 1.8.0 revision 202

**Steps to reproduce:**

1. Go to `<MI_HOME>/bin`.
2. Execute `./ciphertool.sh -Dconfigure`

The files are pointed within `cipher-tool.properties` file should be modified to avoid clear passwords.

Below, I provide the output of the Ciphertool:

```

Encrypting using Internal KeyStore.
{type: JKS, alias: wso2carbon, path: /Users/sa23xj/Desktop/wso2ei-7.0.2/micro-integrator/repository/resources/security/wso2carbon.jks}

[Please Enter Internal KeyStore Password of Carbon Server : ]

Internal KeyStore of Carbon Server is initialized Successfully


Encryption is done Successfully


Secret Configurations are written to the property file successfully
```

**Related Issues:**

**Comment by arunans23** [comment]
In MI 1.2.0, configuration files are not edited directly. All the configurations should be done via deployment.toml file. Hence if you are defining clear passwords, add them under the secrets section, encrypt them and then refer to them in the configs.
https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/encrypting_plain_text/#step-3-accessing-secrets

**Comment by serrodcal** [comment]
> In MI 1.2.0, configuration files are not edited directly. All the configurations should be done via deployment.toml file. Hence if you are defining clear passwords, add them under the secrets section, encrypt them and then refer to them in the configs.
> https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/encrypting_plain_text/#step-3-accessing-secrets

That's true, but in that scenario if somebody can access to the machine he will be able to get the password in text plain from some files like axis2.xml or carbon.xml, right?

In WSO2 ESB 5.0.0, we could use ciphertool to avoid having text plain password in those files we point out in ciphertool-tool.properties (using xpath).

**Comment by arunans23** [comment]
> > In MI 1.2.0, configuration files are not edited directly. All the configurations should be done via deployment.toml file. Hence if you are defining clear passwords, add them under the secrets section, encrypt them and then refer to them in the configs.
> > https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/encrypting_plain_text/#step-3-accessing-secrets
> 
> That's true, but in that scenario if somebody can access to the machine he will be able to get the password in text plain from some files like axis2.xml or carbon.xml, right?
> 
> In WSO2 ESB 5.0.0, we could use ciphertool to avoid having text plain password in those files we point out in ciphertool-tool.properties (using xpath).

In MI 1.2.0, after you encrypt the secrets with the ciphertool, there will be no plain text password visible in those files.

**Comment by serrodcal** [comment]
> > > In MI 1.2.0, configuration files are not edited directly. All the configurations should be done via deployment.toml file. Hence if you are defining clear passwords, add them under the secrets section, encrypt them and then refer to them in the configs.
> > > https://ei.docs.wso2.com/en/latest/micro-integrator/setup/security/encrypting_plain_text/#step-3-accessing-secrets
> > 
> > 
> > That's true, but in that scenario if somebody can access to the machine he will be able to get the password in text plain from some files like axis2.xml or carbon.xml, right?
> > In WSO2 ESB 5.0.0, we could use ciphertool to avoid having text plain password in those files we point out in ciphertool-tool.properties (using xpath).
> 
> In MI 1.2.0, after you encrypt the secrets with the ciphertool, there will be no plain text password visible in those files.

Maybe, I'm wrong but after trying you mentioned one more time it seems like the password are still in text plain:

* deployment.toml:
```
❯ cat deployment.toml
[server]
hostname = "localhost"
# offset  = 10

[user_store]
type = "read_only_ldap"

[keystore.primary]
file_name = "repository/resources/security/wso2carbon.jks"
password = "$secret{keystore_jks_password}"
alias = "wso2carbon"
key_password = "$secret{keystore_jks_password}"

[truststore]
file_name = "repository/resources/security/client-truststore.jks"
password = "$secret{keystore_jks_password}"
alias = "symmetric.key.value"
algorithm = "AES"

[secrets]
keystore_jks_password  = "Y57zc9MASCs1gUmEqUixC2EJYJAa8WUqVJcgOMKrnmPVTUXM3btTt+xohHfc0RNU1nq5ACvyXOmUY4X2L+0MirYWqrp7AknbmZPizkNtzcEZfD/kPha9V21uA2he30wBudg2aJ2CiUJwn+ciz2oQqVTsPwSkvZ+LNWi8EjlFrMbmx5br9egtTaqfmTqOXYw6uBqccHUMx1L7e7aFLBu+G9p0XMgt1+6OTnF7hR9Vw4q6b5kq2J8EaORVfhA4cKF/mrnwYef2F/LSkVEbzQz/jPB+irDuW0IPckDg6Mzt4nyDORYT8dXmk5z1zQRMsPKjNkAaYlue9PSvhACuwOYihQ=="
```
*  `./ciphertool.sh -Dconfigure`
*  carbon.xml:
```
❯ cat carbon.xml | grep Password
            <Password>wso2carbon</Password>
            <KeyPassword>wso2carbon</KeyPassword>
            <Password>wso2carbon</Password>
            <KeyPassword>wso2carbon</KeyPassword>
            <Password>wso2carbon</Password>
                <!-- <Password>password</Password> -->
        <SvnPassword>password</SvnPassword>
        <Password>admin</Password>
```

**Comment by serrodcal** [comment]
I'm sorry, I forgot to start the Micro-integrator. After using ciphertool to start the server is needed. Now, I can see the following:

```
❯ cat carbon.xml | grep Password
            <Password>$secret{keystore_jks_password}</Password>
            <KeyPassword>$secret{keystore_jks_password}</KeyPassword>
            <Password>$secret{keystore_jks_password}</Password>
            <KeyPassword>$secret{keystore_jks_password}</KeyPassword>
            <Password>$secret{keystore_jks_password}</Password>
            <!-- <Password>password</Password> -->
        <SvnPassword>password</SvnPassword>
        <Password>admin</Password>
```

**Comment by arunans23** [comment]
I was going to suggest that next :). Glad it worked.

Resolving the issue.

**Comment by serrodcal** [comment]
Thanks a lot @arunans23 for helping. I have summarized all the steps in a Gist for those come here to check out this topic: https://gist.github.com/serrodcal/a7b4b8ec66e1533bf3f79a5313341653
