### ISSUE TITLE
Building docker image HelloWorld kubernetes results in error org.wso2.maven:mi-container-config-mapper:5.2.28

### ISSUE THREAD

**Issue by michelchristianen** [wso2/micro-integrator#2068]
Hello,

Since today I experience issues when building an image within Integration Studio. The last week I could make docker image builds towards my own dockerhub account, but since today I get strange errors and can't build even.

I get the following error. I tried it today even on a brand new laptop, and got the same error. I assume it has to do with an updated maven dependency. Last week it was working fine. It happens when using the helloworldkubernetes sample and than press build image you will run into these errors. 

BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:38 min
[INFO] Finished at: 2021-01-28T22:12:31+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.wso2.maven:mi-container-config-mapper:5.2.28:config-mapper-parser (config-mapper-parser) on project hello-k8sKubernetesExporter: Exception while parsing the deployment.toml file 
[ERROR] net.lingala.zip4j.exception.ZipException: Probably not a zip file or a corrupted zip file
[ERROR] -> [Help 1]

**Comment by arunans23** [comment]
This issue should be fixed now. Can you try it again?
