### ISSUE TITLE
Unable to Manage Tasks from Micro Integrator Dashboard

### ISSUE THREAD

**Issue by swapnil28490** [wso2/micro-integrator#2106]
**Description:**
Unable to manage Tasks from Micro Integrator Dashboard. Can see only the list of Tasks cannot edit the tasks like changing the quartz or interval etc from the dashboard.
I am new to WSO2 products so In earlier versions I guess it used to happen from Management Console, which is separated in latest releases and a dashboard is provided. Is there any way to Manage Tasks at runtime.

Please suggest a way !!

**Product Version:**
Micro Integrator 7.2

**Comment by sachithKay** [comment]
The Micro Integrator is a container friendly product with immutable concepts. Hence it does not provide a way to edit/change your synapse configurations on the fly using the dashboard. The configuration changes currently supported include, enable/disable tracing, activating/deactivating message processors, endpoints and proxy services.
If you want to change the  aspects related to tasks, you have to change your synapse configuration (related to the task) using integration studio and re-deploy your carbon application into the server.

**Comment by arunans23** [comment]
Answered. Hence closing the issue.
