### ISSUE TITLE
FreeMarker template breaks upon optional headers 

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#2122]
**Description:**

1. Define following freemaker template

```
            <payloadFactory media-type="json" template-type="freemarker">
                <format><![CDATA[{
    "Name": "${payload.user.first_name} ${payload.user.last_name}",
    "Age": "${payload.user.age}",
    "Address": "${payload.user.location.city},${payload.user.location.state.@code}",
    "MyPRoperty": "${ctx.MY_INPUT}",
    "MyHeader": "${trp.abc}"
}]]></format>
                <args/>
            </payloadFactory>
```

2. Invoke without defining HTTP header `abc`
3. Template breaks with the following message

```
[2021-03-09 07:05:28,990] ERROR {PayloadFactoryMediator} - {api:FreeMarkerTest} Error parsing FreeMarker template, Syntax error or invalid reference : trp.abc At line: 6 column: 20
```

**Comment by tharakamd** [comment]
FreeMarker provides ways to handle this type of missing value. Refer to this [doc](https://freemarker.apache.org/docs/dgui_quickstart_template.html#autoid_8). Therefore the template writer should properly handle these types of scenarios. According to the doc, we can handle this error like bellow,

```json
"MyHeader": "${trp.abc!""}"
```

**Comment by tharakamd** [comment]
Fixed with the PR https://github.com/wso2/docs-apim/pull/3305
