### ISSUE TITLE
Freemarker template does not support optional inputs 

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#2124]
**Description:**

1. Define following free marker template. It will convert input json to XML 

```
<user>
    <Name>${payload.first_name} ${payload.last_name}</Name>
    <Age>${payload.age}</Age>
    <Address>${payload.location.city}, ${payload.location.state.code}</Address>
</user>
```

2. Invoke with following payload. Note that age is not present. 

```
{
"first_name": "John",
"last_name": "Deo",
    "location": {
        "state": {
            "code": "NY",
            "name": "New York"
        },
        "city": "Manhattan"
    }
}
```

It cannot parse and given an error. What is expected is

```
<user>
    <Name>John Deo</Name>
    <Age></Age>
    <Address>Manhattan, NY</Address>
</user>
```

**Comment by abeykoon** [comment]
If we have 

```
"age": "",
```

it works. Is this the expected behaviour? How can we achieve above scenario?

**Comment by tharakamd** [comment]
FreeMarker provides ways to handle this type of missing value. Refer this [doc](https://freemarker.apache.org/docs/dgui_quickstart_template.html#autoid_8). Therefore the template writer should properly handle these types of scenarios.

**Comment by tharakamd** [comment]
Fixed with the PR https://github.com/wso2/docs-apim/pull/3305
