### ISSUE TITLE
Dashboard cannot connect to MI instance running in a K8 environment 

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#2135]
**Description:**
When the MI instance is running inside a k8 pod, the server will provide the k8 internal cluster ip as its host. This makes it impossible for a dashboard which is running remotely (locally) to connect to the MI instance.

**Solution:**
Allow the server to configure a host value in the MI server instance itself. 

<img width="539" alt="Screen Shot 2021-03-11 at 3 05 27 PM" src="https://user-images.githubusercontent.com/22365810/110766508-3fecbd80-827b-11eb-8f10-2392350123d3.png">

**Comment by sdkottegoda** [comment]
Increasing the priority since we need to fix this.
