### ISSUE TITLE
[Dashboard] Intermittent node registering in cluster mode

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#2142]
**Description:**
- Intermittently a node is deregistered from the dashboard, while the relevant MI instance is running.
- Note that in image 1, node-2 has been been deregistered  at [2021-03-12 11:02:28,207] an in image 2 even the node-1 has been deregistered at [2021-03-12 12:12:35,779]. 
- Both nodes were running at these timestamps.

![Screen Shot 2021-03-12 at 12 08 33 PM](https://user-images.githubusercontent.com/22365810/110902996-bf869500-832c-11eb-8a06-588923e05dbf.png)
![Screen Shot 2021-03-12 at 12 15 06 PM](https://user-images.githubusercontent.com/22365810/110902990-bd243b00-832c-11eb-8147-6e541fa9e395.png)

deployment.toml config is as follows.
node-1
```
[cluster_config]
node_id = "node-1"

[task_handling]
resolving_period = "6"
resolving_frequency = "3"

[dashboard_config]
dashboard_url = "https://192.168.1.3:9743/dashboard/api/"
heartbeat_interval = 5
group_id = "mi_dev"
node_id = "dev_node_1"
```

node-2
```
[cluster_config]
node_id = "node-2"

[task_handling]
resolving_period = "6"
resolving_frequency = "3"

[dashboard_config]
dashboard_url = "https://192.168.1.3:9743/dashboard/api/"
heartbeat_interval = 5
group_id = "mi_dev"
node_id = "dev_node_2"

```

**Comment by dulanjalidilmi** [comment]
This was not reproduced locally. Hence closing this issue.
