### ISSUE TITLE
[Dashboard UI] UX issues in the log config view

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#2147]
![Screen Shot 2021-03-12 at 2 53 13 PM](https://user-images.githubusercontent.com/22365810/110920291-37f85080-8343-11eb-992f-d2ebae1677dc.png)
**Description:**
- Add Log Config -> Add Logging Configuration
- The text fields should be longer atleast to occupy 30-40% of the width given that class  names can be lengthy

**Comment by sajithaliyanage** [comment]
Add a **search box** to the Log Config view to filter loggers by class name.

**Comment by dulanjalidilmi** [comment]
> Add a **search box** to the Log Config view to filter loggers by class name.

Moved this issue to https://github.com/wso2/micro-integrator/issues/2177
