### ISSUE TITLE
Micro Integrator Dashboard - UI Strings

### ISSUE THREAD

**Issue by nilminiwso2** [wso2/micro-integrator#2176]
**Description:**

Note the following about the below screen.

- Since we use **Group ID** for the first field, let's use **Server Nodes** for the second field (instead of 'Select Nodes).
- Better to change **Group ID** to **Server Group** IMO.
- Better to change **Nodes** to **Server Nodes**. Looks more comprehensive.
- Change **API** to **APIs**. All other components are in plural form.
- Do we need the **General** heading in the navigator? It doesn't seem to serve any purpose.

<img width="1241" alt="Screenshot 2021-03-24 at 21 48 25" src="https://user-images.githubusercontent.com/21237558/112346486-004aba80-8cec-11eb-999a-88aa274665df.png">

In the below screen the term **Design** looks wrong since we are not displaying the design view of the artifacts. Let's changes this to **Overview** or **Details**. This applies to all the similar screens.

<img width="1162" alt="Screenshot 2021-03-24 at 21 55 12" src="https://user-images.githubusercontent.com/21237558/112346962-7b13d580-8cec-11eb-86f8-5c06d258d900.png">

**Affected Product Version:**
APIM 4.0.0

**OS, DB, other environment details and versions:**    
MacOS Big Sur

**Comment by dulanjalidilmi** [comment]
@nilminiwso2 We did not change term **GroupId** but we changed term **Select Nodes** to **Node IDs**. These are the terms we use in configuration files as well. In the main navigation there are two sections, **General** and **Global Settings**. The global settings are not visible for users in file based user store.

<img width="258" alt="Screenshot 2021-04-06 at 20 45 30" src="https://user-images.githubusercontent.com/38608578/113735330-c7620b00-9719-11eb-8f61-855bfd7568ea.png">

I have added a PR for other suggestions you have mentioned here. Thank you.
