### ISSUE TITLE
Improve CLI to list DSS artifacts.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#220]

**Comment by menuka94** [comment]
I have started working on this in #243.

**Comment by a5anka** [comment]
Can you explain a bit about the REST resources that you are planning to implement?

E.g. https://github.com/wso2/micro-integrator/blob/master/doc/mi-rest-api.md

**Comment by menuka94** [comment]
> Can you explain a bit about the REST resources that you are planning to implement?
> 
> E.g. https://github.com/wso2/micro-integrator/blob/master/doc/mi-rest-api.md

Here's what I have planned.

### /data-services

#### GET
##### Summary:

Retrieve Data Services

##### Description:

List available Data Services.

##### Responses

| Code | Description | Schema |
| ---- | ----------- | ------ |
| 200 | OK. List of Data Services is returned. | [DataServicesList](#DataServicesList) |

##### Example

```
curl -X GET "https://localhost:9164/management/data-services" -H "accept: application/json" -k
```

```json
{
  "count": 1,
  "list": [
    {
      "name": "findDoctor",
      "serviceGroup": "",
      "serviceNamespace": ""
    }
  ]
}
```

### /data-services?dataService={dataServiceName}

#### GET
##### Summary:

Get details of a data service

##### Description:

Retrieve details of a specified data service. Name of the data service needs to be provided to retrieve it.

##### Parameters

| Name | Located in | Description | Required | Schema |
| ---- | ---------- | ----------- | -------- | ---- |
| dataServiceName | query | Name of the Data Service | Yes | string |

##### Responses

| Code | Description | Schema |
| ---- | ----------- | ------ |
| 200 | OK. Requested Data Service is returned | [DataServiceInfo](#DataServiceInfo) |

##### Example
```
curl -X GET "https://localhost:9164/management/data-services?dataServiceName=findDoctor" -H "accept: application/json" -k
```

```json
{
  "name": "findDoctor",
  "serviceGroup": "",
  "serviceNamespace": "",    
  "queries": [
    {
      "name": "queryDoctor",
      "wsdl1_1": "http://localhost:8280/services/findDoctor?wsdl",
      "wsdl2_0": "http://localhost:8280/services/findDoctor?wsdl2"
    }
  ]
}
```

| Code | Description | Schema |
| ---- | ----------- | ------ |
| 404 | Not Found. Requested data service does not exist |  |


#### DataServicesList

| Name | Type | Description | Required |
| ---- | ---- | ----------- | -------- |
| count | integer |  |  |
| list | [ [DataServiceSummary](#DataServiceSummary) ] |  |  |


#### DataServiceInfo 

| Name | Type | Description | Required |
| ---- | ---- | ----------- | -------- |
| Service Name | string |  | Yes |
| Service Description | string |  | No |
| Service Group Name | string |  | No |
| wsdl1_1 | string |  |  |
| wsdl2_0 | string |  |  |


### DataServiceSummary

| Name | Type | Description | Required |
| ---- | ---- | ----------- | -------- |
| Service Name  | string |  | Yes |

**Comment by a5anka** [comment]
@abeykoon Please let us know your comment on this

**Comment by a5anka** [comment]
@menuka94 Shall we use the response format we used for proxy services?

```json
{
  "count": 1,
  "list": [
    {
      "name": "TestProxy",
      "wsdl1_1": "http://ThinkPad-X1-Carbon-3rd:8290/services/TestProxy?wsdl",
      "wsdl2_0": "http://ThinkPad-X1-Carbon-3rd:8290/services/TestProxy?wsdl2"
    }
  ]
}
```

**Comment by menuka94** [comment]
> @menuka94 Shall we use the same response format we used for proxy services?
> 
> ```json
> {
>   "count": 1,
>   "list": [
>     {
>       "name": "TestProxy",
>       "wsdl1_1": "http://ThinkPad-X1-Carbon-3rd:8290/services/TestProxy?wsdl",
>       "wsdl2_0": "http://ThinkPad-X1-Carbon-3rd:8290/services/TestProxy?wsdl2"
>     }
>   ]
> }
> ```

Sure. I updated the API in my preceding comment.
