### ISSUE TITLE
Implementing gracefull shutdown of micro-integrator when using mediations triggered by messaging or scheduling

### ISSUE THREAD

**Issue by Thilinika** [wso2/micro-integrator#2201]
**Description:**
WSO2 MI already supports graceful shutdown for http requests and for PTT [1] Requirement is to implement graceful shutdown of micro-integrator when using mediations triggered by messaging or scheduling.

[1] https://github.com/wso2/wso2-synapse/pull/1478 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by GThoonsen-U** [comment]
Hi,
Gracefull shutdown for mediations triggered by files discovered by polling VFS directories are also required for a full coverage of asynchronous mediations on kubernetes.
Regards

**Comment by arunans23** [comment]
Some of these requirements are mentioned here as well. https://github.com/wso2/micro-integrator/issues/2319
