### ISSUE TITLE
Provide Kerberos Mediator Support in Micro Integrator.

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#221]
**Description:**

$subject.

This mediator was introduced in EI 6.4.0 https://github.com/wso2/carbon-mediation/pull/1069/commits.
However the feature wasn't packed and was packed in EI 6.5.0 https://github.com/wso2/product-ei/pull/4032 only. 

Since the mediator is not available in Integration Studio https://github.com/wso2/product-ei/issues/2469, it is not packed in MI. 

Once it is available in Integration Studio, we need to pack this feature to MI.

**Comment by Vathsan** [comment]
Closing since this has not received a higher demand for a considerable period. Please re-open the issue if we have higher demand or added the mediator to Integration Studio.
