### ISSUE TITLE
[Dashboard] Unable to search in log configurations

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#2260]
**Description:**

![Screenshot from 2021-04-16 10-57-12](https://user-images.githubusercontent.com/24619763/114975832-8baa0c80-9ea2-11eb-8537-99088d171d4e.png)

To change log level, no explicitly way search and find rather than navigating through all loggers available

**Comment by dulanjalidilmi** [comment]
Duplicated issue https://github.com/wso2/micro-integrator/issues/2177
