### ISSUE TITLE
Using quotes when defining string values in file.properties file. 

### ISSUE THREAD

**Issue by AyeshUvindu** [wso2/micro-integrator#2267]
**Description:**

- When injecting parameters from an environment variable, the variable can be defined using single quotes.
`export test='http://google.com/partner_api'`
- When we are logging that property using a log mediator as below.
```
<log level="custom">
               <property expression="get-property('env', 'test')" name="Property read from environment"/>     
</log>
```
- We can observe below log.
`[2021-04-19 13:33:46,353]  INFO {org.apache.synapse.mediators.builtin.LogMediator} - {api:TestFilePropertyAPI} Property read from environment = http://google.com/partner_api`

- When injecting a variable using a file, if we defined the variable by enclosing the value using quotes the variable will not be properly reflected in synapse properties.
Add the below property to the file.properties file. 
`test='http://google.com/partner_api'`
Then logs the property using the below log mediator in the mediation flow.
```
<log level="custom">
        <property expression="get-property('file', 'test')" name="Property read from file"/>      
</log>
```
- We can see the quotes are also printed in the logs. In here the quotes are not removed.
`[2021-04-19 13:33:46,353]  INFO {org.apache.synapse.mediators.builtin.LogMediator} - {api:TestFilePropertyAPI} Property read from file = 'http://google.com/partner_api' `

- Some customers suggesting for an improvemnt to remove the quotes if the variables of file.properties files are enclosed with quotes.

**Suggested Labels:**
Improvement

**Comment by Vathsan** [comment]
When defining an environment variable, we do not need to wrap the value within quotes unless there are special characters. Wrapping the values with single/double quote(s) is needed when exporting the variables with special characters and it does not have any effect when retrieving the value. The library (System.getenv()) simply retrieves the value (without surrounded quotes).
https://unix.stackexchange.com/questions/16303/what-is-the-significance-of-single-and-double-quotes-in-environment-variables#:~:text=If%20the%20value%20you're,backslashes%20or%20a%20combination%20thereof.

When defining the properties in the file.properties file, we do not specifically define environment variables, we rather define properties. During runtime, the value is retrieved for the given key. It may/may not be wrapped within single/double quote(s). If the single/double quote(s) is not required, we can simply remove it from the property value.

Sample file.properties config,
```
test=helloWorld
testWithQuotes='helloWorld'
spaceWithoutQuote=hello world
spaceWithQuote='hello world'
specialChars=http://helloWorld.com
specialCharsWithQuote='http://helloWorld.com'
```

corresponding output,
`test = helloWorld, testWithQuotes = 'helloWorld', spaceWithoutQuote = hello world, spaceWithQuote = 'hello world', specialChars = http://helloWorld.com, specialCharsWithQuote = 'http://helloWorld.com'`

Therefore closing this issue. Please re-open if the requirement is different.
