### ISSUE TITLE
uri append 'jsonObject' when try to set messageType to application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by hongha1412** [wso2/micro-integrator#2272]
**Description:**
I've build an API that receive POST request and then transfer request body to other http endpoint with GET method and type application/x-www-form-urlencoded
But when i send request to http endpoint, the endpoint uri appended "jsonObject" string right before query parameter, detail in below image
![image](https://user-images.githubusercontent.com/20342243/116529026-aea6d880-a906-11eb-8271-a012ba11d3f7.png)

**Affected Product Version:**
wso2mi-1.2.0

**OS, DB, other environment details and versions:**    
OS: windows / linux (centos7)

**Comment by arunans23** [comment]
Can you log the `uri.var.command` value and check what is the value that was received?

**Comment by hongha1412** [comment]
Dear @arunans23,

I've added log config like below
![image](https://user-images.githubusercontent.com/20342243/116532302-4b1eaa00-a90a-11eb-9113-cb0cc40b025f.png)

And this is what i've got
![image](https://user-images.githubusercontent.com/20342243/116532387-612c6a80-a90a-11eb-83ab-bf0e678217e3.png)

**Comment by malakaganga** [comment]
Use <property name="REST_URL_POSTFIX" scope="axis2" action="remove"/> prior to send.
