### ISSUE TITLE
Support TOML configurations to configure carbon.xml parameters

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#2277]
**Description:**
Currently, MI does not support configuring carbon.xml properties such as "MediationFlowStatisticConfig". TOML configuration model requires adding custom configurations into the deployment.toml file and update carbon.xml parameters.
For example, the following TOML configurations should be reflected on the carbon.xml file.
```
[[server_conf]]
title = "MediationFlowStatisticConfig"

[[server_conf.param]]
key="StatWorkerCount"
value="500"

[[server_conf.param]]
key="StatWorkerIdleInterval"
value="600"
```
Relevant carbon.xml content should be as follows:
```
<MediationFlowStatisticConfig>
        <StatWorkerCount>500</StatWorkerCount>
        <StatWorkerIdleInterval>600</StatWorkerIdleInterval>
    </MediationFlowStatisticConfig>
```

**Affected Product Version:**
MI 1.1.0, 1.2.0

**Comment by arunans23** [comment]
Fixed with https://github.com/wso2/micro-integrator/pull/2276
