### ISSUE TITLE
Cant send Complex JSON Object to Data service

### ISSUE THREAD

**Issue by isurul28** [wso2/micro-integrator#2280]
**Description:**
We can send a simple JSON String to the Data service but when sending a complex JSON payload [1] it will give an error[2].

**To ovoid this issue** we have to escape the quotation marks in the payload and send it to the Data service. It is because Data service expect a predefined data base type value like String, not a JSON object.

[1]
{
   "json":[
      {
         "Project_Description":"test",
         "PROJECT_ID":"test123"
      }
   ]
}
[2]. "Value type miss match, Expected value type - '', but found - 'STRING'"

**Suggested Labels:**
future improvement

**Suggested Assignees:**

**Affected Product Version:**
MI, EI

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
Create a API which send a JSON payload to DSS to insert it to the database
Send a complex JSON payload [1]

**Related Issues:**

**Comment by malakaganga** [comment]
Since we store the above values as String in the database and it maps to the params which are in form of either int, string...., WSO2 DSS expects the json object to be in String format. We can manage this by using literal true in payload factory mediator hence closing this ticket.

```
<payloadFactory media-type="json">
            <format>{
                  "_postInsertProjectsIntoSQLDB":{
                     "json": "$1"
                          }
                       }</format>
            <args>
               <arg literal="true" evaluator="xml" expression="$ctx:inputPayload"/>
            </args>
         </payloadFactory>
```
