### ISSUE TITLE
Getting started guide improvements

### ISSUE THREAD

**Issue by a5anka** [wso2/micro-integrator#229]
- [x] Rename "Hello world sample" as "Quick start guide"
- [x] Rename "Getting started guide" as "Micro Integrator 101"
- [x] Modify the scenario diagram in "Micro Integrator 101" to show that MI is used to implement it
- [ ] Show capabilities of CLI tool in Micro Integrator 101
- [x] Add a scenario diagram to the Quick start guide
- [x] Show the synapse code used in the Quick start guide
- [x] Change the "Deploying in docker" as the main one in Micro Integrator 101.

**Comment by nilminiwso2** [comment]
-(DONE) Rename "Hello world sample" as "Quick start guide"
-(DONE: Changed to 'Developing Cloud-Native Integration')  Rename "Getting started guide" as "Micro Integrator 101"
-(DONE)  Modify the scenario diagram in "Micro Integrator 101" to show that MI is used to implement it
-(IN PROGRESS)  Show capabilities of CLI tool in Micro Integrator 101
-(DONE)  Add a scenario diagram to the Quick start guide
-(DONE)  Show the synapse code used in the Quick start guide
-(DONE)  Change the "Deploying in docker" as the main one in Micro Integrator 101.

**Comment by nilminiwso2** [comment]
-(DONE) Show capabilities of CLI tool in Micro Integrator 101: The content is reorganized in MI 7[1]. Content is also added to tutorials [2].

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/using-the-command-line-interface/
[2] https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/tutorials/sending-a-simple-message-to-a-service/#step-5-test-the-use-case
