### ISSUE TITLE
Reintroduce support to deploy capps from maven car deploy plugin

### ISSUE THREAD

**Issue by dnwick** [wso2/micro-integrator#2292]
**Description:**
Allow car deploy plugin to deploy capps 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
7.1.0 , 7.2.0 4.0.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by arunans23** [comment]
Management APIs have been introduced to deploy CApps. https://github.com/wso2/micro-integrator/pull/2427
