### ISSUE TITLE
stax2-api-x.x.x.jar is missing in MI-1.2.0

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/micro-integrator#2297]
**Description:**

Compared to EI 6.x and EI-7.1.0 runtimes, the stax2-api-3.1.4.jar file is missing in the EI-7.1.0 OSGi libs directory, which is located at <MI_HOME>/wso2/lib path. Because of this missing jar, the error `Uncaught exception java.lang.NoClassDefFoundError: org/codehaus/stax2/ri/Stax2EventFactoryImpl` occurs when the following dependency is present in a custom class mediator.

```
<dependency>
    <groupId>org.codehaus.woodstox</groupId>
    <artifactId>stax2-api</artifactId>
    <version>3.1.4</version>
</dependency>
```
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
EI-7.1.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
Resolving this since the jar is packed in ./wso2/components/plugins/stax2-api_3.1.4.jar directory. While writing a class mediator importing the said package (OSGi import) should resolve the issue.
