### ISSUE TITLE
Faulty Capps are never deleted from the faultyCapps list

### ISSUE THREAD

**Issue by tharakamd** [wso2/micro-integrator#2315]
**Description:**
When a faulty Capp is deployed, that app name is added to the faulty Capp list. But when we deploy that (remove the Capp), the Capp name is still there in the faulty Capp list.

**Affected Product Version:**
MI-1.2.0

**Steps to reproduce:**

1. Include the attached [jar.zip](https://github.com/wso2/micro-integrator/files/6557888/jar.zip) in the dropins folder.
2. Add the below line to the micro-integrator.sh file
```
-DenableTestApi=true
```
3. Add this to the internal-apis.xml file located in <MI_HOME>/conf directory.
```xml
<api name="TestApi" protocol="http https" class="com.chakray.test.internal.api.TestApi"></api>
```
4. Call the API
```
curl --location --request GET 'https://localhost:9201/test-api/test'
```
5. Call the Test API and see that it returns a empty list
6. Add a CAR in carbonapps that fails
7. Call the Test API and see that car is in the list
8. Remove the CAR
9. Call the Test API and see that car is still in the list

**Comment by arunans23** [comment]
Already fixed in master.
