### ISSUE TITLE
High-Risk licenses in wso2 MI dependency jars

### ISSUE THREAD

**Issue by Vishalj32** [wso2/micro-integrator#2327]
**Description:**

Our team was trying to upgrade the current WSO2 version from 6.5.0 to Micro-Integrator 1.2.0, we have a requirement to verify whether all the dependency jars packaged in WSO2 have a open-source license compatibility.

Upon verification our team found below high risk licenses:
- GNU General Public License with Classpath Exceptions version 2.0
- GNU General Public License v3.0 only
- GNU Lesser General Public License v3.0 only
- GNU General Public License v2.0 only
- GNU Lesser General Public License v2.1 only
- Creative Commons Attribution Share-Alike 3.0 (CC-BY-SA)

On-Risk Jars:
- GNU General Public License with Classpath Exceptions version 2.0:
axiom_1.2.11.wso2v17.jar:smtp-1.6.2.jar
axiom_1.2.11.wso2v17.jar:pop3-1.6.2.jar
jaxb-api-2.4.0-b180830.0359.jar
jaxb_2.2.5.wso2v1.jar:istack-commons-tools-2.6.1.jar

- GNU General Public License v3.0 only:
hapi_2.1.0.wso2v1.jar

- GNU Lesser General Public License v3.0 only:
json-schema-validator-all_2.2.6.wso2v7.jar:jackson-coreutils-1.8.jar
smooks_1.5.1.wso2v1.jar:milyn-edisax-parser-1.5.jar
json-schema-validator-all_2.2.6.wso2v7.jar:msg-simple-1.1.jar
smooks_1.5.1.wso2v1.jar:milyn-scribe-hibernate-1.2.4.jar
json-schema-validator-all_2.2.6.wso2v7.jar:uri-template-0.9.jar

- GNU General Public License v2.0 only:
javax.annotation-api_1.3.2.jar
com.rabbitmq.client_5.8.0.jar

- GNU Lesser General Public License v2.1 only:
org.eclipse.osgi.services_3.5.100.v20160504-1419.jar:org.osgi.service.http-3.5.0-20150611.165350-3.LIFERAY-PATCHED-1.jar

- Creative Commons Attribution Share-Alike 3.0 (CC-BY-SA):
opensaml_2.6.6.wso2v3.jar#zip:esapi-2.1.0.1.jar

Please have a look into them as they might create a compliance issue for an apache 2.0 licensing

**Suggested Labels:**
license

**Suggested Assignees:**

**Affected Product Version:**
4.0.0 or lesser

**OS, DB, other environment details and versions:**  
Windows, MacOS, Linux

**Steps to reproduce:**
NA

**Related Issues:**
NA

**Comment by GDLMadushanka** [comment]
Please find the analysis below.
Most libs are dual licenced and atleast one licence in compatible with Apache 2.0
[Licence Changes - Sheet1.pdf](https://github.com/wso2/micro-integrator/files/7624420/Licence.Changes.-.Sheet1.pdf)
