### ISSUE TITLE
[Feature] Invoke MI secrets using API

### ISSUE THREAD

**Issue by isurul28** [wso2/micro-integrator#2341]
**Description:**
According to the document[1] we can create secrets using the CLI. Introducing a feature that can invoke this function through a API (Management API).

[1].https://ei.docs.wso2.com/en/7.2.0/micro-integrator/administer-and-observe/using-the-command-line-interface/#mi-secret

**Suggested Labels:**
NewFeature

**Suggested Assignees:**

**Affected Product Version:**
MI1.2.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
The recommended approach is to use the CLI. We will consider this improvement if we get a considerable demand.
