### ISSUE TITLE
Prometheus statistics issue due to duplicate API Version

### ISSUE THREAD

**Issue by akAsara** [wso2/micro-integrator#2367]
**Description:**
If we configure an API service with a version, there is a duplicate API version inside Prometheus which expose micro-integrator statistics

**Suggested Labels:**
mi:1.2, Prometheus

**Affected Product Version:**
mi:1.2

**Steps to reproduce:**
1. Sample API service:-
```<?xml version="1.0" encoding="UTF-8"?>
<api context="/hello-world/v1.0" name="asara" version="1.0" version-type="context" xmlns="http://ws.apache.org/ns/synapse">
    <resource methods="GET" url-mapping="/hello">
        <inSequence>
            <payloadFactory media-type="json">
                <format>{"Hello":"World"}</format>
                <args/>
            </payloadFactory>
            <respond/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </resource>
</api>
```
2. Install and setup Prometheus 
3. Invoke the service and check the metrics through the Prometheus console
![Screenshot from 2021-08-05 18-20-28](https://user-images.githubusercontent.com/37328374/128353468-356d0c73-1962-4118-a1f3-3acdd0536f1a.png)

**Comment by sajithaliyanage** [comment]
Refer: https://github.com/wso2/micro-integrator/issues/2385
