### ISSUE TITLE
Template / Skeleton generation for Soap to Rest Conversion 

### ISSUE THREAD

**Issue by TanyaM** [wso2/micro-integrator#2390]
**Description:**
APIM allows in providing a WSDL url of a soap service which will then generate the rest resources and draft mediations for the soap to rest conversion. But MI being our integration component, this capability is not supported in MI. For a user who is  using only MI has to manually define rest resources, drag and drop integration constructs to create the conversion which is a cumbersome process. 
Hence adding the capability to generate a template / skeleton for the rest api will be a good addition to the MI product.

**Affected Product Version:**
MI 4.0.0

**Comment by arunans23** [comment]
Tracked via https://github.com/wso2/micro-integrator/issues/2416. Hence closing this.
