### ISSUE TITLE
JDBCUserStoreManager does not resolve the encrypted passwords before persisting the user to the database

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/micro-integrator#2398]
**Description:**
According to the current implementation of JDBCUserStoreManager, it does not resolve the credentials if they are encrypted using the cipher tool before persisting the user to the database [1]. Therefore, whenever the super admin credentials are configured in the deployment.toml as below, it considers the $secret{secret_key} as the original password value of the user and adds it accordingly.

```
[super_admin]
username = "test"
password = "$secret{secret_key}"
```

So, we need to fix this to support encrypted passwords in the user-mgt.xml file.

[1] - https://github.com/wso2-support/micro-integrator/blob/80f15b18eb384a980655734a44e7a5f798c7c1c4/components/org.wso2.micro.integrator.security/src/main/java/org/wso2/micro/integrator/security/user/core/jdbc/JDBCUserStoreManager.java#L1286

**Affected Product Version:**
wso2mi-1.2.0

**Steps to reproduce:**

1. Change the User store to RDBMS user store as instructed in documentation[1].
2. Add the following entry to the deployment.toml file.
```
[super_admin]
username = "admin"
password = "$secret{secret_key}"

[secrets]
secret_key = "[abc123]"
```
3. Run the following command at the <MI_HOME>/bin directory and use the wso2carbon as the keystore password.
```
./ciphertool.sh -Dconfigure
```
4. Then it will encrypt the password provided at the deployment.toml file.
5. Start the MI dashboard server.
7. Try to log in with the correct admin credentials.(username: admin/ Password:abc123). The login attempt will fail.
8. Try to login with username:admin/password: $secret{secret_key}. The login attempt will be successful.

**Comment by hisanhunais** [comment]
Fixed with https://github.com/wso2/micro-integrator/pull/2402
