### ISSUE TITLE
UnitTest fails when API protocol is HTTPS

### ISSUE THREAD

**Issue by isurul28** [wso2/micro-integrator#2411]
**Description:**
When we create an API with protocol  HTTPS in the integration project and create a test case for it. When we run the test case it fails. But the same test case work if we change the API protocol to HTTP. 
I also checked putting HTTPS with the proxy service. For proxy service with HTTPS the unit test works. 

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
 Integration Studio 8.0.0 , synapse-unit-test-maven-plugin - 5.2.27

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1.Create a API in integration project and change it protocol to https
2.Create a test case for it and run it. It will fail
3. Now go to  API and change the protocol to http and run the test case again and  You will see the test case is getting passed

**Related Issues:**

**Comment by tharakamd** [comment]
Fix with the PR : https://github.com/wso2/integration-studio/pull/881
