### ISSUE TITLE
Providing  W3C Trace Context headers support

### ISSUE THREAD

**Issue by akAsara** [wso2/micro-integrator#2415]
**Description:**

 W3C has introduced a set of common HTTP headers called W3C Trace context to overcome some issues such as lack of standardization which led to a jumble of mutually incompatible header formats between various vendors. W3C Trace context is a standard that makes distributed tracing easier to implement, more reliable, and ultimately more valuable for developers working with modern, highly distributed applications. 

Since the current Jaeger Client of micro integrator does not support the W3C Trace Context Propagation format and also the current implementation was tightly coupled to the open-tracing related interfaces, we need to add this feature for upcoming product releases.

**Suggested Labels:**
wso2 MI

**Comment by Vathsan** [comment]
We use Opentracing in MI to publish traces. Opentracing does not support W3C Trace context propagation. We may need to go with OpenTelemetry, https://opentelemetry.io/docs/instrumentation/java/manual/, to support this.

**Comment by gspadotto** [comment]
Hi, any progress about this functionality? Is it in the roadmap?

**Comment by NishanthiWi** [comment]
Hi Team,

Any update on this feature ?

Best Regards,
Nishanthi
