### ISSUE TITLE
Securing REST API question

### ISSUE THREAD

**Issue by sylim728** [wso2/micro-integrator#2439]
**Description:**

I follow the below documentation for the securing REST API testing 
https://ei.docs.wso2.com/en/latest/micro-integrator/use-cases/examples/rest_api_examples/securing-rest-apis/

However, at the part for "Test the API" no 2, the tutorial request to provide the credentials for user. But it don't have the example how the URL with credential look like.

![image](https://user-images.githubusercontent.com/91312395/134637253-76a6aa11-8e8f-465e-bf6c-fffc3e671298.png)

Anyone can suggest? Thanks and Regards
   
**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by Vathsan** [comment]
You may use postman to include the authorization header https://learning.postman.com/docs/sending-requests/authorization/#basic-auth.

If you are using curl you may invoke using,
curl -X GET -H 'Authorization: Basic YWRtaW46YWRtaW4=' http://127.0.0.1:8290/stockquote/view/IBM

**Comment by sylim728** [comment]
> You may use postman to include the authorization header https://learning.postman.com/docs/sending-requests/authorization/#basic-auth.
> 
> If you are using curl you may invoke using,
> curl -X GET -H 'Authorization: Basic YWRtaW46YWRtaW4=' http://127.0.0.1:8290/stockquote/view/IBM

Thanks for help, thanks
