### ISSUE TITLE
MI-Dashboard could not start after Update to latest version

### ISSUE THREAD

**Issue by SchroeerM** [wso2/micro-integrator#2531]
**Description:**
Currently we try to  implement the MI and the MI-Dashboard in our environment. We setted up the MI and Dashboard according to the current documentation of the version 4.0.0. As backend we use an Windows Maschine. We installed the MI itself as Windows Service using the YAJWG (according to documentation). The MI-Dashboard could only be ported to windows service by useing an specific version (above 4.0.1.3 i thought). So we updated the Dashboard and the MI with the current Windows Updater. After this change the MI Dashboard could not start anymore. The error said that the Dashboard could not find the correct toml file and after some research we found out that the Dashboard is looking for the toml file in the directory %MI_DASHBOARD%/../../../cfg/deployment.toml. This is an issue because the path should be something like %MI_DASHBOARD%/cfg/deployment.toml.

**Affected Product Version:**
MI-Dashboard 4.0.1.5

**OS, DB, other environment details and versions:**    
Windows, default database, Installation-Path D:/WSO2MI and D:/WSO2MIDASH. Every 

**Steps to reproduce:**
Install MI and MI-Dashboard on a fresh Windows Installation
Update MI and MI-Dashboard to latest Versions with the Updater
Modify MI and MI-Dashboard to run as Windows Service

**Comment by uarulraj486** [comment]
Hi SchroeerM
The Latest Mi driven by deployment.toml file configure the following an restart the miserver as well as dashboard. then access the dashboard URL. It shows the midashboard
[dashboard_config]
dashboard_url = "https://localhost:9743/dashboard/api/"

**Comment by SchroeerM** [comment]
Hi uarulaj486,

sorry but your answer has nothing to do with the initial request and would not fix it. Anyway we switched over to an competitor product because of this and about 20 other bugs that we founded by simply installing your software according to your documentation as well as the fact that you leave open a ticket from an potential customer 2 weeks open to answer with an solution that could not solve the problem.

Thanks,
Michael

**Comment by SchroeerM** [comment]
Ok, my fault. Sorry for that but this fact confirms me that use another product was the right descision in our case, cause it seemed that at WSO2 nobody is interested in gernerating new customers with support or simply help customers getting started. So again - sorry for my inconvenient post but it is very frustrating that two employees spends 1.5 Weeks (each) to setup a software that throws so much errors and had that much bugs by simply following the documentation.

**Comment by sachithKay** [comment]
Assuming you have the latest MI and MI-Dashboard versions, could you please try the following.
- Go to <Dashboard-HOME>/conf/config-parser/.metadata directory.
- Remove all existing properties files and restart the dashboard server.

**Comment by sachithKay** [comment]
closing the issue since an answer has been provided. Re-open if needed further assistance.
