### ISSUE TITLE
MI-4.0.0 Support to Deploy a Capp Using the Maven-Car-Deploy Plugin

### ISSUE THREAD

**Issue by Abshan** [wso2/micro-integrator#2544]
**Description:**
For MI-4.0.0 currently, remote capp deployment from the maven capp deployment plugin is not possible. Need to implement it.

**Suggested Labels:**
**Type/Task**, **Type/Improvement**

**Affected Product Version:**
MI-4.0.0

**Comment by chanikag** [comment]
Fixed with https://github.com/wso2-support/micro-integrator/pull/515

**Comment by mcarroa** [comment]
Hi,
I think the link is not available

**Comment by chanikag** [comment]
The PR for the wso2/micro-integrator repo is https://github.com/wso2/micro-integrator/pull/2427
