### ISSUE TITLE
[Jaeger Tracing ] In Jaeger Tracing Before payload and after payload span tags are not set as intended

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#2599]
**Description:**
In jaeger tracing before payload and after payload span tags are not set as intended for synapse mediators.

**Suggested Labels:**
Bug

**Affected Product Version:**
MI-4.0.0

**Steps to reproduce:**
1. Set up EI with open tracing
2. Enable **stat.tracer.collect_payloads= true**
3. Deploy and invoke the following sample API https://apim.docs.wso2.com/en/latest/integrate/examples/rest_api_examples/transforming-content-type/

**Related Issues:**
https://github.com/wso2/product-ei/issues/5215

**Comment by malakaganga** [comment]
Fixed
