### ISSUE TITLE
Support using Injecting parameters in Local Entry

### ISSUE THREAD

**Issue by minhtran-q** [wso2/micro-integrator#2607]
**Description:**
My project is using several connectors to integrate with third parties. And some of them require the connection to be configured as a Local Entry. Currently, the Inject parameter does not support Local Entry yet, so I think it will be supported in the future

**Affected Product Version:** wso2mi-4.0.0

**Steps to reproduce:**

```
<localEntry key="KAFKA_CONNECTION" xmlns="http://ws.apache.org/ns/synapse">
    <kafkaTransport.init>
        <connectionType>kafka</connectionType>
        <keySerializerClass>org.apache.kafka.common.serialization.StringSerializer</keySerializerClass>
        <name>KAFKA_CONNECTION</name>
        <valueSerializerClass>org.apache.kafka.common.serialization.StringSerializer</valueSerializerClass>
        <bootstrapServers>$FILE:kafkaBootstrapServers</bootstrapServers> #not supported yet
        <poolingEnabled>false</poolingEnabled>
    </kafkaTransport.init>
</localEntry>
```

**Comment by minhtranes** [comment]
Yes I encounter similar issue, it seems MI 4.0.0 didn't support parameters for Local Entry
