### ISSUE TITLE
Dependency on readiness probe for the MI Dashboard deployment

### ISSUE THREAD

**Issue by shefandarren** [wso2/micro-integrator#2631]
**Description:**
The MI Dashboard cannot fetch the artifacts from the MI server even though a heartbeat was received with the following log line in the dashboard side.

`INFO {HeartBeatDelegate} - New node mi-deployment-579775c77-8n6j9 in group : uoe_mi is registered. Inserting heartbeat information`

Upon troubleshooting this, it was identified that the dashboard is faced with a 'connection refused' when trying to obtain the access token from the MI server. This is due to the readiness probe defined in the deployment.yaml. Even setting the initialDelaySeconds to a lower value did not help. The only way around this is to do the dashboard deplopyment adhering to the readiness probe. 

Here, we need to redeploy the dashboard whenever changes are made to the micro integrator POD and that is not ideal. Is it possible to improve the overall functionality to dynamically check whether the K8s service is up so that the dashboard could fetch the artifacts?

**Affected Product Version:**

- wso2mi:4.0.0.41-centos

- wso2mi-dashboard:4.0.1.8-centos

**OS, DB, other environment details and versions:** 

- Minikube (server version:  v1.22.3)

**Steps to reproduce:**
Deploy a micro integrator and mi dashboard instance simultaneously.  Make sure to define the probes accordingly. A sample is shared below. 

        livenessProbe:
          tcpSocket:
            port: 8290
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 9201
          initialDelaySeconds: 10
          periodSeconds: 10

**Comment by Ponmanimaran** [comment]
Description:

wso2 mi4.0.0 is deployed in aws eks clusters and frequently facing dashboard connectivity issue with micro integrator.
`
[2022-04-04 07:18:10,056]  INFO {HeartBeatDelegate} - Node : dev_node_10 of group : mi_test has de-registered. Hence deleting node information
[2022-04-04 07:18:10,058]  INFO {HeartBeatDelegate} - Successfully deleted node where group_id : mi_test and node_id : dev_node_10.
[2022-04-04 07:18:10,059]  INFO {HeartBeatDelegate} - Deleting all artifacts and server information in node : dev_node_10 in group: mi_test
[2022-04-04 07:19:10,953] ERROR {LoginDelegate} - No running micro integrator instances found. Please start a server and login.`

It is working only for limited time, then the mi node is getting deregistered. Any work around or fix will be much helpful.

Thanks in Advance
