### ISSUE TITLE
Message processors does not start automatically

### ISSUE THREAD

**Issue by imsuneth** [wso2/micro-integrator#2642]
**Description:**
Message processors does not start automatically. Had to set the message processor status to ON manually from the MI dashboard.

**Affected Product Version:**
4.1.0-beta

**OS, DB, other environment details and versions:**    
macOS monterey 12.0.1

**Steps to reproduce:**
https://apim.docs.wso2.com/en/latest/integrate/examples/message_store_processor_examples/using-message-sampling-processor

**Comment by Nirothipan** [comment]
This issue is happening since the is.active param is added as false by default in the Integration Studio when not defined.
` <parameter name="is.active">false</parameter>`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<messageProcessor class="org.apache.synapse.message.processor.impl.sampler.SamplingProcessor" messageStore="MyStore" name="SamplingProcessor" xmlns="http://ws.apache.org/ns/synapse">
    <parameter name="sequence">send_seq</parameter>
    <parameter name="interval">20000</parameter>
    <parameter name="is.active">true</parameter>
</messageProcessor>
```
