### ISSUE TITLE
FilePollingConsumer does not support NONE value for ActionAfterProcess 

### ISSUE THREAD

**Issue by umerckx** [wso2/micro-integrator#2744]
The FilePollingConsumer allows NONE value for ActionAfterProcess, but it does not support it. 
If NONE is used, the file will be deleted after processing. This is not clear, can the code be adapted so NONE is supported? 

Same goes for ActionAfterFailure.

**Comment by dulanjalidilmi** [comment]
Hi @umerckx ,

Thank you for reporting this. In order to investigate the issue more, please provide us with following information.

1. Product Version
2. The use case and steps to reproduce

Best Regards
Dilmi

**Comment by malakaganga** [comment]
There hasn't been a response so closing the issue please reopen the issue if it's required.
