### ISSUE TITLE
Configure the retry interval for Kafka Inbound Endpoint

### ISSUE THREAD

**Issue by Menuka-Senevirathne** [wso2/micro-integrator#2943]
Hi Team,

As per the current implementation, there's no option to configure the interval for retries in Kafka Inbound Endpoint. This is already available for JMS as transport.jms.retry.duration [1]. It would be better if we can improve the retry interval for Kafka Inbound Endpoint as well in a way that it doesn't impact on rest of the operations. 

[1] https://ei.docs.wso2.com/en/latest/micro-integrator/references/synapse-properties/inbound-endpoints/polling-inbound-endpoints/jms-inbound-endpoint-properties/

Regards,
Menuka

**Comment by sajinieKavindya** [comment]
Fixed with https://github.com/wso2-extensions/esb-inbound-kafka/pull/61
