### ISSUE TITLE
XA datasources are not able to be defined via Integration Studio

### ISSUE THREAD

**Issue by AmilaJ** [wso2/micro-integrator#2972]
**Description**
Syntax to create data services is not working mentioned at https://apim.docs.wso2.com/en/4.1.0/integrate/examples/data_integration/distributed-trans-data-service/

And when tried with Design Mode also it is unable to be created.

**Steps to Reproduce**
Trying to create a MySQL XA darasource as mentioned
https://apim.docs.wso2.com/en/4.1.0/integrate/examples/data_integration/distributed-trans-data-service/

**Affected Component**
IntegrationStudio

**Version**
8.2.0

**Comment by arunans23** [comment]
Fixed with https://github.com/wso2/integration-studio/pull/1261
