### ISSUE TITLE
ClassNotFoundException - org.wso2.carbon.inbound.endpoint.EndpointListenerLoader cannot be found by org.wso2.micro.integrator.initializer_4.2.0.19

### ISSUE THREAD

**Issue by malakaganga** [wso2/micro-integrator#2977]
This can be reproduced with the JDK level 11.20 and can be resolved by passing the following JVM parameters in the start-up script of the product.

-Djdk.util.zip.disableZip64ExtraFieldValidation=true \
-Djdk.nio.zipfs.allowDotZipEntry=true \
As per the issue, it seems this behavior was triggered over a JDK-level update.

Rather than adding them manually(the customer has added the JVM parameters as a workaround) the customer is expecting an official fix for this.

Kindly let us know the possibility of releasing an official fix for this behavior.

If we are releasing an official fix for this, hope we may need to modify the start-up script for all the versions or we may have to implement a logic to detect the java version and act based on the JAVA version.

Furthermore, I have passed the same variable set in JDK 11.19, even if the parameters are not required. During this, I have not observed any issues either even if I have passed the pointed JVM options unnecessarily.

**Comment by resoli** [comment]
Same here.
