### ISSUE TITLE
[Salesforce-Inbound-Endpoint] Jetty client version does not support TLS 1.3

### ISSUE THREAD

**Issue by imedyaosandi** [wso2/micro-integrator#3036]
The current salesforce inbound (org.apache.synapse.salesforce.poll.class-2.0.4.jar) jetty client version(9.2.x) does not support TLS 1.3. Need to update the cometd.java.client.version to upgrade the jetty client version to 9.4.x[1].

[1] https://www.eclipse.org/lists/jetty-dev/msg03209.html

**Comment by chanikag** [comment]
This is fixed with https://github.com/wso2-extensions/esb-inbound-salesforce/pull/18
