### ISSUE TITLE
[MI 4.1.0] Upgrading the JDK 11 sub version in the official WSO2 MI docker image

### ISSUE THREAD

**Issue by ChinthakaJ98** [wso2/micro-integrator#3040]
Upgrade the JDK version used in the MI 4.1.0 default docker images to OpenJDK version 11.0.21.

**Related Issue:**
https://github.com/wso2-enterprise/wso2-mi-internal/issues/296

**Comment by chanikag** [comment]
@ChinthakaJ98 Is this task done?

**Comment by ChinthakaJ98** [comment]
Hi @chanikag,

Please note that this is fixed and the updated docker images were released on 3rd December 2023. Therefore closing this issue as it has been resolved.

Kind Regards,
Chinthaka
