### ISSUE TITLE
Deprecate chpassword scripts from MI

### ISSUE THREAD

**Issue by dulanjalidilmi** [wso2/micro-integrator#3043]
### Problem

bin/chpasswd.sh  and bin/chpassword.bat scripts are throwing following error.

`Error: Could not find or load main class org.wso2.carbon.core.util.PasswordUpdater`

 The reason for this issue is that we do not pack all kernel packages in MI. Here the script is searching for class PasswordUpdater.java[1], and this is packed with org.wso2.carbon.core_. This issue occurs since we do not pack org.wso2.carbon.core_ in MI. 

[1] https://github.com/wso2/carbon-kernel/blob/4.6.x/core/org.wso2.carbon.core/src/main/java/org/wso2/carbon/core/util/PasswordUpdater.java

### Solution

Remove chpassword scripts from distributions as they are not working for MI

### Affected Component

MI

### Version

All

**Comment by chanikag** [comment]
This is fixed with https://github.com/wso2/micro-integrator/pull/2901
