### ISSUE TITLE
Introducing a tomal mapping to update the service path axis2 parameter

### ISSUE THREAD

**Issue by cbabey** [wso2/micro-integrator#3053]
Requesting a tomal mapping to update the proxy service path URL. By default, the proxy services will be exposed with the “services” path URL.

Ex:
`https://localhost:8253/service/StockQuoteProxy?wsdl
`
The customer is required to change it to a custom name.

Ex:
`https://localhost:8253/soapservice/StockQuoteProxy?wsdl`

**Comment by GDLMadushanka** [comment]
Already added in https://github.com/wso2/micro-integrator/commit/437140a8ef03875e9b84cc1d297fd725f70c3598
