### ISSUE TITLE
Browser does not prompt for credentials due to incorrect WWW-Authentication header

### ISSUE THREAD

**Issue by asithamadhushanka12** [wso2/micro-integrator#3054]
Hi Team,

**Description:**

When using an API secured with basic auth using RESTBasicAuthHandler(org.wso2.micro.integrator.security.handler.RESTBasicAuthHandler) deployed in MI. When the API is invoked through the browser, the browser does not prompt for the user credentials.

In the Network trace we can see the MI sends the below response to the browser;

```
HTTP/1.1 401 Unauthorized
WWW_Authenticate: Basic realm="WSO2 EI"
Date: Tue, 12 Dec 2023 03:57:44 GMT
Transfer-Encoding: chunked
Connection: keep-alive
```

Mi version: 1.2.0

Thanks and best regards,
Asitha M

**Comment by GDLMadushanka** [comment]
Fixed by https://github.com/wso2/micro-integrator/pull/3055
