### ISSUE TITLE
All carbon_home files deleted after tmp folder deletion and restart

### ISSUE THREAD

**Issue by SiluniPathirana** [wso2/micro-integrator#3145]
Reproducing steps.

1. Start the server in a Windows environment and shutdown.
2. Delete the tmp folder from carbon_home.
3. Start the server again.
4. All the files (not folders) within the carbon_home will be getting deleted.
5.  Following block from micro-integrator.bat file is causing the issue.

rem ------------------ Remove tmp folder on startup -----------------------------
set TMP_DIR=%CARBON_HOME%\tmp
cd "%TMP_DIR%"
del *.* /s /q > nul
FOR /d %%G in ("*.*") DO rmdir %%G /s /q
cd ..

Since the 'cd "%TMP_DIR%"', line fails here, it is obvious that it will delete all the files.
I can see this is been already addressed in the .sh scripts like below,

TMP_DIR="$CARBON_HOME"/tmp
if [ -d "$TMP_DIR" ]; then
rm -rf "$TMP_DIR"/*
fi

**Comment by arunans23** [comment]
Fixed with https://github.com/wso2/micro-integrator/issues/3145
