### ISSUE TITLE
Cannot view or download carbon apps if the version has square brackets - WSO2 EI 6.3.0

### ISSUE THREAD

**Issue by Sumudu-Sahan** [wso2/micro-integrator#3146]
If there is square brackets in the version of the CAR file, could not able to view or download that CAR file after uploading through the carbon management console and showing a complete black screen.

**Reproducing Steps**
- Start the EI 6.3.0 server.
- Go to the carbon management console.
- Download the attached 
[testprojectCompositeExporter_1.0.0-[development].car.zip](https://github.com/wso2/micro-integrator/files/14443374/testprojectCompositeExporter_1.0.0-.development.car.zip)
 [1] and upload it. (Before uploading it, remove the .zip extension)
- Once it got deployed, try to view it or download it.
- Able to see a complete black screen.

Thanks and Regards,
Sumudu W.

**Comment by arunans23** [comment]
Master fix is not needed since MI does not have a carbon console anymore.
