### ISSUE TITLE
Is there any option to enable/disable the scheduled tasks in WSO2 mi 1.2.0 

### ISSUE THREAD

**Issue by sprakashpandian** [wso2/micro-integrator#3203]
### Description

Do we have any option to enable or disable the scheduled tasks without  stop the server or change the car file?

Created the scheduled task, which is running everyday 10 am. Need to change the schedule time without disturbing the running build.  

Please help on this.

### Affected Component

MI

### Version

1.2.0

### Environment Details (with versions)

Unix
Docker Container 
Amazon Cloud

### Suggested Labels

Micro Integrator

**Comment by malakaganga** [comment]
Hi @sprakashpandian ,

Please refer to the doc: https://mi.docs.wso2.com/en/latest/learn/examples/scheduled-tasks/task-scheduling-simple-trigger/
