### ISSUE TITLE
wso2esb to wso2mi migration

### ISSUE THREAD

**Issue by srinivaskancharla** [wso2/micro-integrator#3214]
### Description

Dears, 
We have been using wso2esb 5.0.0 for our projects. As i see from support life cycle the support has extended but not clearly said till which date. Could you confirm what is the support on wso2esb now.

Also wanted to migrate the solution from wso2esb to other possible module which are having regular updaates.
Our applicaiton is supported for two types of deployment
1. VM deployment ( where it uses wso2sb 5.0.0) --> here we want to replace wso2esb with latest wso2 modules.
2. container deployment( where it uses wso2mi 4.1.0) --> This is same code base but enabled container support by using wso2mi 4.1.0. code which is compatible in wso2esb is also compatible in wso2mi
3. What is the difference between wso2mi and wso2esb, if i use wso2mi what other features I will not get which are part of wso2esb.
4. Is there any steps documented for migrating wso2esb to wso2mi.

Please support for these technical queries. 

### Affected Component

MI

### Version

4.1.0

### Environment Details (with versions)

Deployment type : VM Deployment(Legacy)
As-is WSO2 Flavor : wso2esb 5.0.0.0

To-be wso2 flavor: wso2mi 4.1.0

### Suggested Labels

wso2esbtomi

**Comment by anupama-pathirage** [comment]
If you're still facing this issue, please feel free to raise your question in the `help-micro-integrator` channel on the [WSO2 Discord server](https://discord.com/invite/Xa5VubmThw)
