### ISSUE TITLE
MI 4.2 in cluster, GROUP_ID

### ISSUE THREAD

**Issue by jo6r** [wso2/micro-integrator#3233]
### Description

I have MI in cluster (coordination DB) , and I would like to create groups for MI instances. In the database, there is a column called GROUP_ID, which is always filled with the "default" value. I can't figure out how to set this up. There is no option in the deployment.yaml file. Is there any solution available? Apart from a separate database.

node1
```
[cluster_config]
node_id = "node-1"
```
node2
```
[cluster_config]
node_id = "node-2"
```

GROUP_ID|NODE_ID                                                 |IS_NEW_NODE|LAST_HEARTBEAT|
--------+--------------------------------------------------------+-----------+--------------+
default |                                                  node-1|          0| 1691587735347|
default |                                                  node-2|          0| 1691587733825|

### Steps to Reproduce

follow up https://ei.docs.wso2.com/en/latest/micro-integrator/setup/deployment/deploying_wso2_ei/ with more MI instances

### Affected Component

MI

### Version

4.2

### Environment Details (with versions)

docker, alpine:3.17.2

**Comment by anupama-pathirage** [comment]
If you're still facing this issue, please feel free to raise your question in the `help-micro-integrator` channel on the [WSO2 Discord server](https://discord.com/invite/Xa5VubmThw)
