### ISSUE TITLE
Automatic string to int convertion issue in WSO2MI4.1

### ISSUE THREAD

**Issue by subodhcjoshi82** [wso2/micro-integrator#3236]
### Description

I am getting issue to automatic String to int conversion in WSO2MI4.1 and when i search about this then found below fix but not in MI but wso2ei
[https://github.com/wso2/product-ei/issues/4364](wso2ei)

As per the solution they asked to add below property in **synapse.config**
```
# Disable auto conversion of strings to primitives
synapse.commons.json.json.output.autoPrimitive=false
```
But in WSO2MI **synapse.config** wont support this property.

How we can resolve this issue in WSO2MI?

### Affected Component

MI

### Version

4.0.1

### Environment Details (with versions)

Rockey Linux

### Related Issues

https://github.com/wso2/product-ei/issues/4364

### Suggested Labels

wso2mi

**Comment by chanikag** [comment]
You can enable/disable converting string to primitive types in the JSON output in XML to JSON transformations by setting the following configuration in $MI_HOME/conf/deployment.toml

```
[mediation]
synapse.enable_auto_primitive = false
```
