### ISSUE TITLE
Improving Builder Utilization in axis2.xml.j2 for defaultContentType Configuration

### ISSUE THREAD

**Issue by Abshan** [wso2/micro-integrator#3322]
The current implementation in `axis2.xml.j2` for setting the `defaultContentType` parameter in the Axis2 configuration file (axis2.xml) includes unnecessary quotation marks around the parameter attribute value. This practice prevents the utilization of the defined builder for the `defaultContentType` parameter.

For example,

In the axis2.xml.j2 file contains the following instruction to set the `defaultContentType` parameter value,
```
 {% if transport.default_content_type is defined %}
    <parameter name="defaultContentType" locked="false">"{{transport.default_content_type}}"</parameter>
 {% endif %}
```
So if we add the following configuration snippet to the `deployment.toml` file,
```
[transport]
default_content_type = "application/sample"
```
Then the above config would reflect in the `axis2.xml` file as shown below,
```
<parameter name="defaultContentType" locked="false">"application/sample"</parameter>
```
Because of the quotation marks around the parameter attribute value, the builder for defaultContentType is not being used. But, when we  remove the quotation marks from the axis2.xml.j2 file as shown below, the defined builder gets used.
```
 {% if transport.default_content_type is defined %}
    <parameter name="defaultContentType" locked="false">{{transport.default_content_type}}</parameter>
 {% endif %}
```
 This needs to be rectified.

**Comment by arunans23** [comment]
There is an alternative parameter that we can add in deployment.toml.  

[[transport.parameters]]
name = "DEFAULT_REQUEST_CONTENT_TYPE"
value = "empty/content"
