### ISSUE TITLE
[Bug]: Getting 404 for existing API when enabling PROMETHEUS

### ISSUE THREAD

**Issue by dilshanfardil** [wso2/micro-integrator#3655]
### Description

While enabling Prometheus and executing the cURL command to an existing API with a valid context and a resource, a 404 Not Found error was observed.

### Steps to Reproduce

1. Enabled the PROMETHEUS.

```
[[synapse_handlers]]
name="CustomObservabilityHandler"
class="org.wso2.micro.integrator.observability.metric.handler.MetricHandler"
```

2. Deploy 2 API with the below details
```
 API 1
API context: /abc/def
API Name: SampleABCDEF
URI teamplate: /resource-one

API 2:
API context: /abc
API Name: SampleABC
URI teamplate: /resource-two
```

3. Execute the curl command
```
 curl -i -X GET -H "Content-Type: application/json" -d '{"key":"val"}' http://localhost:8290/abc/def/resource-one
```

**Comment by Bhashinee** [comment]
Fixed with https://github.com/wso2/micro-integrator/pull/3673
