### ISSUE TITLE
Re-write test cases for admin services

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#366]
**Description:**
Test cases for admin services needs to be re-written after merging the micro-integrator management api.
Please refer: https://github.com/wso2/micro-integrator/pull/365

**Comment by sajithaliyanage** [comment]
Test case needs to re-write - https://github.com/wso2/micro-integrator/pull/408

**Comment by milindaperera** [comment]
Refer removal of local-entry related tests : https://github.com/wso2/micro-integrator/pull/425
API to retrieve deployed local-entries not available : https://github.com/wso2/micro-integrator/issues/426

**Comment by sajinieKavindya** [comment]
Refer removal of TemplateAdminService related tests : [#438](https://github.com/wso2/micro-integrator/pull/438)

**Comment by sajinieKavindya** [comment]
Refer removal of TemplateAdminService test: #438
Refer removal of RestApiAdminServiceTestCase and SequenceAdminServiceTestCase: #447

**Comment by chanikag** [comment]
Exclude
org.wso2.carbon.esb.car.deployment.test.ESBJAVA3611EndpointTestCase
org.wso2.carbon.esb.car.deployment.test.ESBJAVA4116CAppArtifactDeploymentFailureDueToNameTestCase
org.wso2.carbon.esb.car.deployment.test.CarbonApplicationReDeploymentTestCase 
Related PR https://github.com/wso2/micro-integrator/pull/461

**Comment by sachithKay** [comment]
Exclude Sample650TestCase. testLocalEntries.
https://github.com/wso2/micro-integrator/pull/473/

**Comment by prabushi** [comment]
Exclude RedirectTest as it requires the Admin API to check the MS/MP status.
https://github.com/wso2/micro-integrator/pull/482/commits/d33303372bdf4c6bcc4eb731598291ca2938ac8f

**Comment by prabushi** [comment]
API is required to check the whether a proxy service is faulty or not.
https://github.com/wso2/micro-integrator/pull/493/files

**Comment by chanikag** [comment]
org.wso2.carbon.esb.resource.test.sequence.SequenceMediaTypeTestCase.dynamicSequenceMediaTypeTest
org.wso2.carbon.esb.resource.test.endpoint.EndPointMediaTypeTestCase.dynamicEndpointMediaTypeTest
org.wso2.carbon.esb.resource.test.template.EndpointTemplateMediaTypeTestCase.dynamicEndpointTemplateMediaTypeTest
org.wso2.carbon.esb.resource.test.template.SequenceTemplateMediaTypeTestCase.dynamicSequenceTemplateMediaTypeTest

Related PRs : https://github.com/wso2/micro-integrator/pull/507, https://github.com/wso2/micro-integrator/pull/508

**Comment by sachithKay** [comment]
Test cases have been added to https://github.com/wso2/micro-integrator/tree/master/integration/management-api-tests/src/test/java/org/wso2/micro/integrator/api
