### ISSUE TITLE
[version upgrade] Carbon mediation version update to 4.7.0 or higher

### ISSUE THREAD

**Issue by milindaperera** [wso2/micro-integrator#388]
**Description:**
JSON message validation with using JSON schema using validate mediator is not working without the fix [1] released in 47.0. Also, this requires minimum kernel version upgrade to 4.5.0

[1] https://github.com/wso2/carbon-mediation/commit/fc37098b9c1ebb6edbc56632b6e455126e4e197a

**Comment by GDLMadushanka** [comment]
Please address TODO items in https://github.com/wso2/micro-integrator/pull/528 after fixing this issue
