### ISSUE TITLE
Reorganize the files in the distribution

### ISSUE THREAD

**Issue by a5anka** [wso2/micro-integrator#41]
Currently, the file structure in the distribution is very similar to the one we had with the micro integrator profile. Since we are creating a separate build for micro integrator we can move most of these files to top level. 

- [x] Document folder structure
  - [x] Update micro-integrator/doc/working-with-the-micro-integrator.md

**Comment by a5anka** [comment]
Copying external jars to `<MI_HOME>/lib directory` does not work. This needs to be fixed as well.

**Comment by malakaganga** [comment]
> Copying external jars to `<MI_HOME>/lib` directory does not work. This needs to be fixed as well.

I have fixed this issue with

https://github.com/wso2/micro-integrator/pull/68

and tested with a Handler and Class mediator
Also, I have verified the patch applying process as well and it is working fine.

**Comment by a5anka** [comment]
@malakaganga @nandika There are pending tasks in the issue. Therefore reopening the issue.

**Comment by a5anka** [comment]
@malakaganga We get an additional log in the startup after #68

```
[2019-04-16 10:21:46,615] [micro-integrator]  INFO - DefaultCryptoProviderComponent 'CryptoService.Secret' property has not been set. 'org.wso2.carbon.crypto.provider.SymmetricKeyInternalCryptoProvider' won't be registered as an internal crypto provider. Please set the secret if the provider needs to be registered.
```

Can you have a look?

**Comment by a5anka** [comment]
@malakaganga wso2server.sh and micro-integrator.sh does the same thing. Therefore it makes more sense to merge the two. We can just remove the micro-integrator.sh and rename wso2server.sh to micro-integrator.sh since the existing micro-integrator.sh does not do anything useful.

**Comment by malakaganga** [comment]
Fixed https://github.com/wso2/micro-integrator/issues/41#issuecomment-483612868
With https://github.com/wso2/micro-integrator/pull/92

Fixed https://github.com/wso2/micro-integrator/issues/41#issuecomment-483616786

> @malakaganga wso2server.sh and micro-integrator.sh does the same thing. Therefore it makes more sense to merge the two. We can just remove the micro-integrator.sh and rename wso2server.sh to micro-integrator.sh since the existing micro-integrator.sh does not do anything useful.

with 
https://github.com/wso2/micro-integrator/pull/90

Hence resolving the issue

**Comment by a5anka** [comment]
I am reopening this since we have not documented the folder structure anywhere which is a listed subtask of the issue.

**Comment by malakaganga** [comment]
With 
https://github.com/wso2/micro-integrator/pull/113 
I have updated the new folder-structure detail  in docs

**Comment by a5anka** [comment]
@malakaganga This is good. We additionally need some description of the files and folders exists in the distribution. Please refer https://github.com/wso2/ballerina-message-broker#folder-structure-of-the-distribution for an example.

**Comment by malakaganga** [comment]
> refer
This issue [1] is fixed with 
https://github.com/wso2/micro-integrator/pull/144/files

[1] https://github.com/wso2/micro-integrator/issues/41#issuecomment-485744511
