### ISSUE TITLE
Libthrift jar is duplicated in the distribution

### ISSUE THREAD

**Issue by a5anka** [wso2/micro-integrator#43]
There are two libthrift jars (libthrift_0.12.0.wso2v1.jar and libthrift_0.9.2.wso2v1.jar) in `wso2/components/plugins` folder.

libthrift_0.12.0.wso2v1.jar is coming from the carbon-mediation dependencies. libthrift_0.9.2.wso2v1.jar is from the analytics-common. We could not upgrade the libthrift version in analytics-common due to some failures in IS analytics components.

Related PRs
- https://github.com/wso2/analytics-is/issues/461
- https://github.com/wso2/carbon-analytics-common/issues/603

**Comment by Nirothipan** [comment]
With https://github.com/wso2/carbon-mediation/pull/1207 , carbon-mediation is updated to pack  libthrift_0.9.2.wso2v1.jar. Hence there are no duplicates in the pack.

We can track upgrading libthrift in https://github.com/wso2/product-ei/issues/3617. Hence closing this.
