### ISSUE TITLE
JDK 11 support

### ISSUE THREAD

**Issue by a5anka** [wso2/micro-integrator#44]
We need to make sure,

- [x] the distribution runs on JDK 11 (can be compiled with JDK 8)
- [ ] the distribution can be built and run using JDK 11

**Comment by sdkottegoda** [comment]
The product can be run in jdk 11 after the changed done in https://github.com/wso2/micro-integrator/pull/992

**Comment by Nirothipan** [comment]
Distribution cannot be build in JDK11 as it needs to run in JDK 8 as well. Hence closing
