### ISSUE TITLE
org.wso2.carbon.websocket.transport jar is not packed in micro integrator

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#457]
**Description:**
org.wso2.carbon.websocket.transport jar is not packed in micro integrator. Therefore it gives following error if the websocket transport is enabled.

INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - org.apache.axis2.AxisFault: Exception occured while loading the Axis configuration from /media/chanika/data/git/new/micro-integrator/integration/mediation-tests/tests-transport/target/carbontmp1561543520059/wso2mi-1.1.0-SNAPSHOT/conf/axis2/axis2.xml
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:183)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:65)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.micro.integrator.core.internal.ServiceComponent.initializeCarbon(ServiceComponent.java:319)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.micro.integrator.core.internal.ServiceComponent.activate(ServiceComponent.java:190)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.reflect.Method.invoke(Method.java:498)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.http.servlet.internal.Activator.registerHttpService(Activator.java:81)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.http.servlet.internal.Activator.addProxyServlet(Activator.java:60)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.equinox.http.servlet.internal.ProxyServlet.init(ProxyServlet.java:40)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.tomcat.ext.servlet.DelegationServlet.init(DelegationServlet.java:38)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1230)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:1174)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1066)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:5370)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5668)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1700)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1690)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.Thread.run(Thread.java:745)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: org.apache.axis2.deployment.DeploymentException: org.wso2.carbon.websocket.transport.WebsocketTransportSender cannot be found by axis2_1.6.1.wso2v35
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:712)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:124)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:332)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.wso2.carbon.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:181)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	... 40 more
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - Caused by: java.lang.ClassNotFoundException: org.wso2.carbon.websocket.transport.WebsocketTransportSender cannot be found by axis2_1.6.1.wso2v35
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:501)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:421)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:412)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.eclipse.osgi.internal.baseadaptor.DefaultClassLoader.loadClass(DefaultClassLoader.java:107)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.Class.forName0(Native Method)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at java.lang.Class.forName(Class.java:264)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.util.Loader.loadClass(Loader.java:261)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	at org.apache.axis2.deployment.AxisConfigBuilder.processTransportSenders(AxisConfigBuilder.java:686)
INFO  [org.wso2.carbon.automation.extensions.servers.utils.ServerLogReader] - 	... 43 more

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by a5anka** [comment]
Please enable `org.wso2.carbon.esb.websocket.inbound.transport.test` after fixing this
