### ISSUE TITLE
[Management API] API to check the status of connectors

### ISSUE THREAD

**Issue by chanikag** [wso2/micro-integrator#523]
**Description:**
In micro integrator there is no way to check status of connectors. This is related to
org.wso2.carbon.esb.connector.test.MediationLibraryServiceTestCase

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by a5anka** [comment]
I think having a way to list out the available connectors is enough. IMO we shouldn't allow users to enable/disable connectors while running. This breaks the immutable docker image concept.

**Comment by Nirothipan** [comment]
@a5anka on a separate note,  do we need to allow users to disable and enable Message Processors . Won't that affect the immutable concept

**Comment by a5anka** [comment]
@Nirothipan Message processors and connectors are bit different. Message processor is something that runs. But connectors is like a library the developers use to add functionality. Therefore IMO it is ok to add functionality to enable/disable message processors.

**Comment by chanikag** [comment]
@a5anka Currently when a connector is added to synapse-libs folder, it is by default disables, unless the enable is added to xml file deployed to imports folder. Then there should be a way to enable the connector by default.

**Comment by abeykoon** [comment]
+1 to add functionality to enable and disable "message processor" from admin console as well as viewing the status. 

We may deploy message storing functionality and message processing functionality in the same container as they are coherent. At the same time, we might need to disable processing while keeping message storing untouched. In that situation we cannot shutdown the container. We need a way to disable the processing only.

**Comment by a5anka** [comment]
@chanikag :+1: to enable all connectors available in MI by default. AFAIK we changed how connectors are deployed in MI. @milindaperera might know details on this.
