### ISSUE TITLE
Allow encrypting passwords and use their secret alias within synapse configuration

### ISSUE THREAD

**Issue by prabushi** [wso2/micro-integrator#588]
**Description:**
Allow encrypting passwords and use them within in the synapse configuration via an API.
https://docs.wso2.com/display/EI650/Working+with+Passwords+in+the+ESB+profile

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by prabushi** [comment]
we can use this approach. https://docs.wso2.com/display/EI650/Encrypting+Passwords+in+WSO2+Micro+Integrator

**Comment by prabushi** [comment]
Reopening this issue as the Secret Resolver is not getting initialized when we use an encrypted password within the configuration. Hence, password is not getting resolved for the following configuration even though we managed to encrypt the values. 

            ```
     <dbreport>
                <connection>
                    <pool>
                        <driver>com.mysql.jdbc.Driver</driver>
                        <url>jdbc:mysql://localhost:3306/DBNAME</url>
                        <user>root</user>
                        <password>{wso2:vault-lookup('MYSQL_PW')}</password>
                    </pool>
                </connection>
                <statement>
                    ......
                </statement>
            </dbreport>
```

**Comment by sajithaliyanage** [comment]
Fix: https://github.com/wso2/wso2-synapse/pull/1394

**Comment by rosensilva** [comment]
Fixed with https://github.com/wso2/wso2-synapse/pull/1394
