### ISSUE TITLE
org.wso2.SecureVaultPasswordRegEx property is not working

### ISSUE THREAD

**Issue by prabushi** [wso2/micro-integrator#593]
**Description:**
The property "org.wso2.SecureVaultPasswordRegEx" is not working in Micro Integrator, as it was initially implemented to validate the password in Management Console.
https://docs.wso2.com/display/EI650/Encrypting+Passwords+in+WSO2+Micro+Integrator#EncryptingPasswordsinWSO2MicroIntegrator-Updatingthepasswordvalidation

We will have to come up with an implementation to validate passwords while running the securevault script.

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
Closing since https://github.com/wso2/micro-integrator/pull/650 is merged
