### ISSUE TITLE
Add synapse unit testing framework client

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/micro-integrator#613]
**Description:**
Provide a built-in way to execute a unit test against a given synapse configuration artifact such as sequence, proxy, api, local entry, endpoints along with registry and connector resources

**Suggested Labels:**
- Type/Improvement
- Type/New Feature

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
Related PR - https://github.com/wso2/devstudio-tooling-esb/pull/989

**Comment by sdkottegoda** [comment]
Fixed
