### ISSUE TITLE
[version upgrade] Carbon kernel version upgrade to 4.5.0 

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/micro-integrator#621]
**Description:**
Upgrade the carbon-kernel version to 4.5.0 or higher in the Micro Integrator for the upcoming releases. 

**Suggested Labels:**
 - Severity/Critical

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sdkottegoda** [comment]
Closing since the kernel dependency was removed from MI
