### ISSUE TITLE
Add task coordination support in MI

### ISSUE THREAD

**Issue by RidmiR** [wso2/micro-integrator#624]

**Comment by Nirothipan** [comment]
**Requirements for clustered task scheduling**


- Availability of coordinator node ( which will be deciding the node to schedule task - Random / Roundrobin or etc. ).

- Pinned servers for task scheduling.

- Fail-safe mechanism for task ( tasks being rescheduled when the node which runs become unavailable or cannot connect to network).

**Comment by Nirothipan** [comment]
Scheme | Pros | Cons
-- | -- | --
Hazelcast | Not required to couple with DB | The code base is not in our control and when issues arise, we need to report to hazelcast and fix or might need to fork.
  |   | Different schemes are available and until we test all of them end to end , we aren’t sure about the issues.
  |   | There can be more than one coordinator in split brain scenarios.
  |   |  
Quartz Task Scheduler | Quartz will be doing the task scheduling and we need to do the configurations only. | No much active development.
  | It is already used in synapse. | Need to couple with a database.
  |   | Code-base is not in our control and need to be forked if required.
  |   | Node selection per task execution which will cause issues when caching jms connections. 
  |   |  
Zookeeper |   | Zookeeper ensemble requires minimum 3 node deployment which would be bulky.
  |   | Only the zookeeper leader can perform write operations and it would need additional communication when tasks are scheduled in non-leader nodes ( communicate to the leader to update task changed state and etc ).
  |   | Opens new socket connection for each watch operation ( this will increase proportional to the task count )
  |   |  
ETCD |   | Provides key value storage only and all the logic has to be implemented on our side ( leader election )
  |   |  
Carbon-coordination | Code is WSO2 owned, hence patching would be comparatively easy. | Coupled with Database

**Comment by Nirothipan** [comment]
**Considering the above facts, we are planning to move with the Carbon-coordination incorporating the following changes to it.**

- Removing kernel dependency ( Since Micro Integrator is independent of kernel).

- Using only RDBMS scheme ( Not zookeeper ).

**Comment by sdkottegoda** [comment]
Can we consider that this epic is done?

**Comment by Nirothipan** [comment]
> Can we consider that this epic is done?

Yes. Closing the issue .
