### ISSUE TITLE
[CLI Tool] Add new management api data points as commands

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/micro-integrator#639]
**Description:**
Currently, there are newly implemented data points in Management API which are not included in the CLI tool. New data points are list in here - https://github.com/wso2/micro-integrator/issues/603

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment]
Related PRs - 
https://github.com/wso2/micro-integrator/pull/647
https://github.com/wso2/micro-integrator/pull/649

**Comment by sdkottegoda** [comment]
Closing this since the issue is fixed
