### ISSUE TITLE
[ManagementAPI] Fix task resource implementation of management api

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#651]
**Description:**
Management api task resource (Management/tasks) does not list scheduled tasks correctly.
It lists tasks associated with MSMP but not scheduled tasks. Implementation has to be changed from 
```
String[] taskNames = configuration.getTaskManager().getTaskNames(); 
```
to
```
String[] taskNames = configuration.getStartups(); 
```

**Comment by sdkottegoda** [comment]
Closing since this is fixed by https://github.com/wso2/micro-integrator/pull/768
