### ISSUE TITLE
With command line "mi show" can't get information about Data Services

### ISSUE THREAD

**Issue by jpvadell** [wso2/micro-integrator#665]
With "mi show proxyservice" can't get the DSS information

There is a way to do this?

**Comment by Nirothipan** [comment]
This   "mi show proxyservice"  gives information about one or more Proxies.
To get details about DSS you may use
 **mi dataservice show**
this support was added later and it will be available in upcoming release.
https://github.com/wso2/micro-integrator/blob/master/cmd/README.md

**Comment by sdkottegoda** [comment]
This functionality is now available in MI 1.1.0 and you can find the [official documentation](https://ei.docs.wso2.com/en/latest/micro-integrator/administer-and-observe/using-the-command-line-interface/) for the usage of the command line tool of MI. 

I will be closing this issue for now. Please feel free to open this for any further concerns.
