### ISSUE TITLE
[CLI Tool] - README content is incorrect

### ISSUE THREAD

**Issue by RidmiR** [wso2/micro-integrator#693]
**Description:**
In CLI readme.md file "show" command usage description is wrong. As per the readme file, if the user wants to get the listed of the available artifacts, the command should be,

**mi [artifact] show**
But the command is wrong. its will show below error. 
<img width="407" alt="Screen Shot 2019-09-03 at 10 28 00 AM" src="https://user-images.githubusercontent.com/40847371/64145249-99c62900-ce35-11e9-859b-fad359a29135.png">

The correct command should be 
**mi show [artifact]**
<img width="416" alt="Screen Shot 2019-09-02 at 2 24 20 PM" src="https://user-images.githubusercontent.com/40847371/64102346-629c3d00-cd8d-11e9-9fe9-f82f55485415.png">

**Task:**
https://github.com/wso2/micro-integrator/issues/622

**Verison**
MI 1.1.0

**Comment by abeykoon** [comment]
Fixed with: https://github.com/wso2/docs-ei/pull/611
