### ISSUE TITLE
Facilitate event sink configuration in MI

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#783]
**Description:**
Event sinks can be added in EI from the Management Console. We can follow doc [1] to create an event sink in EI.
Currently, there is no way of creating an event sink configuration in MI. As an alternative, we can ask the users to manually place their event sink configurations (.xml files) in the event-sinks directory (MI_HOME/repository/deployment/server/event-sinks) as of EI.

[1] https://docs.wso2.com/display/ESB490/Working+with+Event+Sinks

**Comment by sdkottegoda** [comment]
We will be not support even-sinks since the only use case that involved the event-sink is the publish-even mediator. Publish event mediator was designed to publish data to DAS which is a product that is no-longer in use.
