### ISSUE TITLE
References declared inside arrays in the deployment.toml are not resolved properly

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#837]
**Description:**
References declared inside arrays in the deployment.toml are not resolved even though it works inside a single element. e.g

Following is not working
```
[keystore]
file_name = "wso2carbon.jks"

[[custom_transport.listener]]
keystore.file_name = "$ref{keystore.file_name}"
```
and, the following is working
```
[server]
hostname = "localhost"

[transport.tcp]
listener.enable = false
listener.port = 8000
listener.hostname = "$ref{server.hostname}"
```

**Suggested Labels:**
Bug

**Comment by malakaganga** [comment]
Since fixing this issue requires a design change and rather than using reference we can directly use a static value closing this issue
