### ISSUE TITLE
[Windows] - Commented out integration test cases which use admin.stub jar

### ISSUE THREAD

**Issue by RidmiR** [wso2/micro-integrator#858]
**Description:**
When running integration tests in windows, observed issue of **org.wso2.carbon.commons:org.wso2.carbon.logging.admin.stub:jar:4.7.6** does not exist. 

Until finding out the solution for this, commented out the tests which use the stub .jar

**Suggested Labels:**
MI 1.1.0

**OS, DB, other environment details and versions:**    
Windows 10

**Comment by sdkottegoda** [comment]
Closing this issue since test cases were not commented out.
