### ISSUE TITLE
Update Hospital-Service jar link in MI Docs

### ISSUE THREAD

**Issue by Vathsan** [wso2/micro-integrator#934]
**Description:**
In MI docs, for Hospital-Service backend service the existing jar link should be updated with 
Hospital-Service-2.0.0-with-dependencies.jar link. 
The PR for the change of jar can be found in [1].

After downloading the jar, it can be executed as shown below,
>java -jar Hospital-Service-2.0.0-with-dependencies.jar

[1] https://github.com/wso2-docs/WSO2_EI/pull/58

**Comment by Nirothipan** [comment]
Fixed with https://github.com/wso2-docs/WSO2_EI/pull/58
