### ISSUE TITLE
[ Docs ] - "Address Endpoint" page is not getting highlighted correctly when selected

### ISSUE THREAD

**Issue by sajinieKavindya** [wso2/micro-integrator#950]
**Description:**
While following the doc [https://ei.docs.wso2.com/en/7.0.0/micro-integrator/use-cases/examples/endpoint_examples/using-address-endpoints/](https://ei.docs.wso2.com/en/7.0.0/micro-integrator/use-cases/examples/endpoint_examples/using-address-endpoints/) and when "Address Endpoint" is selected from the side navigation bar, "Load Balance Endpoint" is the one getting highlighted.

![doc-issue-2](https://user-images.githubusercontent.com/17607360/65948065-2412a480-e457-11e9-8481-1eabfe19f00d.gif)

**Comment by sdkottegoda** [comment]
This issue has been fixed in the documentation.
