### ISSUE TITLE
[Doc]  Enterprise Integrator Documentation RabbitMQ Inbound Endpoint 

### ISSUE THREAD

**Issue by ajanthasingam** [wso2/micro-integrator#959]
**Description:**
The following changes have to be made in the corresponding doc [1]
Under Synapse Configuration:
    Remove the configuration of Scheduled Task
Under Build and Run:
    Under Create the artifacts:
          Change "Create an ESB Config project" to "Create an ESB Solution project"
    Change "Configure the ActiveMQ broker." to "Configure the  RabbitMQ broker."
    Remove "Set up the back-end service."

[1] - https://ei.docs.wso2.com/en/7.0.0/micro-integrator/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-rabbitmq-protocol/

**Comment by sdkottegoda** [comment]
This has been fixed in the latest documentation
