### ISSUE TITLE
[Doc]  Enterprise Integrator Documentation HL7 Inbound Endpoint 

### ISSUE THREAD

**Issue by ajanthasingam** [wso2/micro-integrator#960]
**Description:**
The following changes have to be made in the corresponding doc [1]
Under Build and Run:
    Under Create the artifacts:
        Change "Create an ESB Config project" to "Create an ESB Solution project"
    Remove "Configure the ActiveMQ broker."
    Remove "Set up the back-end service.

[1] - https://ei.docs.wso2.com/en/7.0.0/micro-integrator/use-cases/examples/inbound_endpoint_examples/inbound-endpoint-hl7-protocol-auto-ack/

**Comment by sdkottegoda** [comment]
Closing since the HL7 inbound is not supported in MI anymore.
