### ISSUE TITLE
Security policies applied to endpoint/proxy are not evaluated

### ISSUE THREAD

**Issue by Drifftr** [wso2/micro-integrator#971]
**Description:**
Even we apply a ws-security based security policy to an endpoint or a proxy, requests are sent without evaluating the policy. 

**Steps to reproduce:**
1. Apply security to endpoint/proxy using a policy.
2. Send requests to the protected endpoint/proxy. 
3. Requests will be sent through for any requests(For failure requests too)

**Comment by Nirothipan** [comment]
Fixed in https://github.com/wso2/micro-integrator/pull/979
