### ISSUE TITLE
[Windows] Startup takes unusual time for the first time

### ISSUE THREAD

**Issue by rosensilva** [wso2/micro-integrator#978]
**Description:**
Micro integrator takes about 35 sec to start in a windows environment for the first time after restarting windows.

**Comment by Nirothipan** [comment]
We observed this only in specific environment and wasn't able to reproduce in others. Hence reducing the priority.

**Comment by Vathsan** [comment]
Could not observe the issue using MI-4.0.0 in Windows 10 environment with JDK 11. Therefore closing the issue.
