### ISSUE TITLE
[Management API] Need to improve 'endpoints' Resource

### ISSUE THREAD

**Issue by menuka94** [wso2/micro-integrator#982]
**Description:**
The `/endpoint` resource does not return enough information. See below.

When the URL `https://localhost:9164/management/endpoints` is invoked, the response (for 2 deployed endpoints) returned is 

```json
{
    "count": 2,
    "list": [
        {
            "name": "SimpleEP",
            "type": "address"
        },
        {
            "name": "SimpleStockQuoteServiceEndpoint",
            "type": "address"
        }
    ]
}
```

We should, at least, return the fields `Name`, `Type`,  `Method`, and `URL`.

Furthermore, this is what's return when invoking `https://localhost:9164/management/endpoints?endpointName=SimpleEP`

```json
{
    "address": "http://localhost:9000/services/SimpleStockQuoteService",
    "advanced": {
        "suspendState": {
            "errorCodes": [],
            "maxDuration": 9223372036854775807,
            "initialDuration": -1
        },
        "timeoutState": {
            "errorCodes": [],
            "reties": 0
        }
    },
    "configuration": "<endpoint xmlns=\"http://ws.apache.org/ns/synapse\" name=\"SimpleEP\"><address uri=\"http://localhost:9000/services/SimpleStockQuoteService\"/></endpoint>",
    "name": "SimpleEP",
    "type": "Address Endpoint"
}
```

This needs to be improved to return useful information as well so that we can show meaningful information through the CLI/UI.

**Comment by sachithKay** [comment]
The only common attributes for every type of endpoints are, name and type. Method and URL are optional. Hence this implementation is valid. 
All relevant attributes are provided when retrieving the endpoint by name.
